pex-tool/pex

pex/pep425.py

* https://www.python.org/dev/peps/pep-0425/
* https://www.python.org/dev/peps/pep-3149/
Basically the original code assumed the `--with-pymalloc` flag would always be set. This is not always the case, and the `d` and `u` flags are also not considered (details in PEP3149).
Have modified the code so that all permutations are considered.

Support all potential abi tag permutations

---

pex/translator.py
tests/test_translator.py

I'm under the impression that this is a simple "typo" error, and the intention was also to pass through the parameter to the chained translators.
Of course it's possible that this was intentional and I'm really missing the point :-)
See https://rbcommons.com/s/twitter/r/1666/

Fix bug that caused pex not to cache the results of translation.

---

pex/crawler.py
pex/link.py
pex/package.py
pex/util.py

A few small touchups that improve the speed of dependency resolution when
many packages are already in the local cache.
- when dispatching multiple crawling threads:
- make each thread a bit more reactive by reducing the polling timeout from
100ms to 10ms
- do not wait for each of the workers threads to complet, just wait for them to complete their
workload.
Without this change, dependency resolution is guaranteed to take longer than 100ms per
dependency, which is a large amount of time for just checking a local zipfile's content.
- cache the result of a couple calls that are repeated many times:
- Link.from_filename
- Package.from_href
Each of this call is performed for each file in the cache, for each dependency that is resolved.
While both these calls are not especially expensive, when …

Speed up the best-case scenario of dependency resolution.

---

pex/bin/pex.py

This string formatting nicety was introduced in Python 2.7 and breaks
Python 2.6 users like myself. This change is forwards and backwards
compatible between all Pythons.

Support Python 2.6

---

CHANGES.rst
pex/bin/pex.py
pex/http.py
pex/version.py
setup.py
tests/test_http.py

* Adds an interpreter cache to the pex tool and self-resolves dependencies
(wheel, setuptools) should they be unavailable at runtime.  This fixes the
issue where "pex" would fail to run in a fresh virtualenv without doing
"pip install pex[whl]".
* Fixes test breakage with requests >= 2.5.2

Adds an interpreter cache to the pex tool.  Fixes #47 and #48.

---

pex/bin/pex.py
pex/common.py
pex/http.py
pex/interpreter.py
pex/pex.py
pex/pex_bootstrapper.py
pex/pex_info.py
pex/tracer.py
pex/variables.py
tests/test_http.py
tests/test_variables.py

Partially addresses #13.  To fully address, there should probably be a tutorial or at least an explicit link to the pex.variables api doc page.

Consolidate PEX environment variable handling and add --help-variables option

---

pex/installer.py
pex/testing.py

Removed setup.py from MANIFEST.in in pex/testing, which causes test_resolver to be an effective regression test.  Fixes #103.

Fix packager not including setup.py files in source distributions

---

pex/bin/pex.py

sys.exit instead of returning pex exit code.

---

pex/pex.py
tests/test_pex.py

The existing SystemExit handler causes an extraneous 'None' to be printed at exit when pex is used with twitter.common.app (and presumably sys.exit() is called with no arguments, which leads to SystemExit().code == None). This adds a None check on se.code.

Remove stderr print on SystemExit().code == None

---

CHANGES.rst
docs/buildingpex.rst
pex/commands/bdist_pex.py
pex/installer.py
pex/pex_builder.py
pex/pex_info.py
setup.py

This is my cut at bdist_pex with @msabramo's fixes rebased on top.  The main question is if the implemented/documented behavior is sane.  It seems reasonable to me but I'm also unsure about what potential customers think.
Addresses feature request #99.

Implement bdist_pex.

---

docs/index.rst

- This should stop the top Google link reading 'TLDR'

[docs] update header in index.rst

---

pex/pex.py

This causes the profile filename to be stored prior to cleaning the environment, just like how coverage manages it.
fixes #154

Fix #154 by storing profiling env var prior to env var deletion

---

tests/test_variables.py

Previously the test wasn't testing what it advertised and as a result
was papering over some test state setup issues.

Fixup `test_variables.test_rc_ignore`.

---

pex/resolver.py

```
[illuminati pex (master)]$ pex --no-pypi --find-links=http://science-binaries.local.twitter.com/home/third_party/python/ thrift==0.9.3 --platform=linux-x86_64
File "/Users/kwilson/Python/CPython-2.7.10/bin/pex", line 9, in <module>
load_entry_point('pex==1.1.0', 'console_scripts', 'pex')()
File "build/bdist.macosx-10.4-x86_64/egg/pex/bin/pex.py", line 509, in main
File "build/bdist.macosx-10.4-x86_64/egg/pex/bin/pex.py", line 471, in build_pex
File "build/bdist.macosx-10.4-x86_64/egg/pex/resolver.py", line 199, in resolve
File "build/bdist.macosx-10.4-x86_64/egg/pex/resolver.py", line 256, in build
File "build/bdist.macosx-10.4-x86_64/egg/pex/resolver.py", line 170, in build
pex.resolver.Untranslateable: Could not get distribution for …
```

Improve error messaging for platform constrained Untranslateable errors.

---

pex/crawler.py
tests/test_crawler.py

PageParser breaks if the links contain any escaped html characters. This fixes that bug.

Unescapes html in PageParser.href_match_to_url

---

pex/common.py
pex/compiler.py
pex/pex.py
pex/util.py
tests/test_pex.py
tests/test_util.py

The fixes are:
- os.link doesn't exist on windows. Always copy instead.
- NamedTemporaryFile doesn't work correctly on windows (see https://bugs.python.org/issue14243)
- sys.prefix is part of site.getsitepackages() on windows. Don't remove it.

Fixes to get pex to work on windows.

---

pex/package.py
tests/test_package.py

Version numbers can have + in them as a local version - `0.1-pex.1` & `0.1+pex.1` take completely different paths in pkg_resources.

Don't normalize version numbers as names.

---

pex/commands/bdist_pex.py

target wasn't defined in a branch.
I couldn't find any tests for bdist_pex though :(

Fix creating an environment pex via bdist_pex

---

pex/compatibility.py
pex/crawler.py
pex/finders.py
pex/http.py
pex/installer.py
pex/link.py
pex/resolver.py
pex/testing.py
pex/translator.py
pex/util.py
tests/test_environment.py
tests/test_http.py
tests/test_integration.py
tests/test_link.py
tests/test_pex.py
tests/test_pex_builder.py
tests/test_pex_info.py
tests/test_util.py
tests/test_variables.py

Now all the tests pass.
One thing I'm not sure about is in the first commit - perhaps we should do away with Link.local_path & make Link.path do the proper thing? I don't think there's a single user of Link.path that uses it for real urls. Let me know what you think.

More fixes for windows

---

pex/pep425.py
tests/test_pep425.py

Not quite sure how to test this short of running it across a whole bunch of libraries. I updated the test case accordingly.
Left the existing code pertaining to the cp3 abi tags as is in case we need to change the supported tags for cp2 and cp3 independently.
But it has been tested with the cryptography==1.2.3 issue mentioned in #213.

Add python 2.x abi tag support

---

pex/installer.py

Without this fix, pex will raise pex.resolver.Untranslateable due to
non utf-8 characters in setup.py or \__init\__.py:
$ pex -r requirements.txt -c foobar -o foobar.pex
**** Failed to install pygments-markdown-lexer-0.1.0.dev39. stdout:
**** Failed to install pygments-markdown-lexer-0.1.0.dev39. stderr:
File "<stdin>", line 7, in <module>
File "/tmp/virtualenv/lib/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 158: ordinal not in range(128)
File "/tmp/virtualenv/bin/pex", line 11, in <module>
sys.exit(main())
File "/tmp/virtualenv/lib/python3.4/site-packages/pex/bin/pex.py", line 509, in main …

open with utf-8 support

---

CHANGES.rst
setup.py

Add README and supported python versions to PyPI description

---

pex/bin/pex.py
tests/test_integration.py

Fix a bug introduced with --pex-root that raised an exception on
when --disable-cache was used.

Fix disable cache (#260)

---

pex/installer.py

Open setup.py in binary mode

---

RELEASE.rst

Convert @jsirois' quick how-to in https://github.com/pantsbuild/pex/issues/184 into a release doc for reference purposes.
Viewable here: https://github.com/kwlzn/pex/blob/3b07b80f81938d34f572677dd9e3c0796acffadd/RELEASE.rst

Document the release process.

---

pex/common.py
pex/util.py
tests/test_common.py

Improve failure modes for os.rename() as used in distribution caching.

---

pex/commands/bdist_pex.py
tests/test_bdist_pex.py

* Add unti test to make sure {pex_root} directory is not created
* Update the cache_dir in bdist_pex

Update cache dir when bdist_pex.run called directly (#274)

---

pex/pex.py
tests/test_integration.py

Setuptools does not require `console_scripts` entry points to call `sys.exit()` (or similar) to exit non-zero:
> The functions you specify are called with no arguments, and their return value is passed to `sys.exit()`, so you can return an errorlevel or message to print to stderr
This patch updates pex to follow the same behavior.
Fixes #137.

Don't ignore exit codes when using setuptools entry points

---

pex/compiler.py
pex/executor.py
pex/installer.py
pex/interpreter.py
pex/pex.py
pex/testing.py
tests/test_executor.py
tests/test_integration.py

Phase 1 of https://github.com/pantsbuild/pants/issues/3416.
- Add a new `pex.executor.Executor` class for normalized subprocess execution.
- Add new structured exception types for known failure modes of subprocess execution to provide actionable information to the end users on failure.
- Port over all known library usages of subprocess to `pex.executor.Executor`.
- Lightweight manual integration testing with `pants` master consuming `pex` master via local whl resolves.

Normalize and edify subprocess execution.

---

pex/commands/bdist_pex.py

Running bdist_pex results in the creation of a directory literally
named *{pex_root}*. Within it is a subdirectory named *interpreter*.
This fixes it by following behavior similar to that found at https://github.com/pantsbuild/pex/blob/master/pex/bin/pex.py#L536.

Fix bdist_pex interpreter cache directory

---

pex/commands/bdist_pex.py
tests/test_bdist_pex.py

Splitting on spaces will break on commands like:
python setup.py bdist_pex \
--pex-args="--python-shebang='#!/usr/bin/env python'"
This uses `shlex.split()` to do it safely.

Fix bdist_pex --pex-args

---

tox.ini

Enables the use of `tox -e py27-coverage-simple` for rapid iteration.

Repair the `py27-coverage-simple` tox env.

---

pex/executor.py
tests/test_executor.py

Addresses handling of @benley's case of attempted execution of a dir, which produced the following unhandled `AttributeError`:
```
File ".bootstrap/_pex/pex.py", line 328, in execute
File ".bootstrap/_pex/pex.py", line 260, in _wrap_coverage
File ".bootstrap/_pex/pex.py", line 292, in _wrap_profiling
File ".bootstrap/_pex/pex.py", line 371, in _execute
File ".bootstrap/_pex/pex.py", line 429, in execute_entry
File ".bootstrap/_pex/pex.py", line 434, in execute_module
File "/usr/lib/python2.7/runpy.py", line 180, in run_module
fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/nonexistent/.pex/install/pex_wrapper-0.0.0-py2.7.egg.355ab1e4a2649222db04cd7b5a7f2a400079ce2a/pex_wrapper-0.0.0-py2.7. …
```

Repair Executor error handling for other classes of IOError/OSError.

---

pex/version.py

Howdy friends,
Recently got bit by this bug when attempting to build a python3 ptpython pex.
Repro steps:
```
osx ~ ❯❯❯ pex pex -c pex -o ~/bin/pex  # clean pex build
osx ~ ❯❯❯ pex ptpython --python python3 -c ptpython -o ~/bin/ptpython
**** Failed to install ptpython-0.35 (caused by: NonZeroExit("received exit code 1 during execution of `['/export/apps/python/3.5.1/bin/python3.5', '-', 'bdist_wheel', '--dist-dir=/var/folders/4y/x7m68gms1cjcc8tpjlxcwz5h0005tq/T/tmpcoBD5s']` while trying to execute `['/export/apps/python/3.5.1/bin/python3.5', '-', 'bdist_wheel', '--dist-dir=/var/folders/4y/x7m68gms1cjcc8tpjlxcwz5h0005tq/T/tmpcoBD5s']`",)
):
stdout:
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/ptpython
copying ptpython/__init__.py …
```

Update wheel dependency to >0.26.0

---

pex/pex_bootstrapper.py
pex/version.py
scripts/coverage.sh

Kill zipmanifest monkeypatching.

---

pex/finders.py

In CPython 3.6, ``FileFinder`` has been moved from ``importlib._bootstrap`` to
a new ``importlib._bootstrap_external`` module.
To account for this, this commit switches to importing the more general
``importlib.machinery`` module instead of ``importlib._bootstrap``, which also
works with older CPython version (3.3+).

Adjusted FileFinder import to work with Python 3.6

---

pex/pex.py

Useful when merging pexes via PEX_PATH.

Expose a PEX instance's path.

---

pex/pex.py
tests/test_pex.py

Fixes #337.
Let me know what else I can do to get this accepted.

Make sure namespace packages (e.g. virtualenvwrapper) don't break pex

---

pex/bin/pex.py
pex/package.py
pex/resolvable.py
pex/resolver.py
tests/test_package.py
tests/test_pex_binary.py
tests/test_resolvable.py
tests/test_resolver.py

this is an implementation of adding constraint support to pex:
https://pip.pypa.io/en/stable/user_guide/#constraints-files
As the "-c" keyword is already used, this implementation opts for "--constraint" by itself.
It works pretty well:
```
pex requests --constraints constraints.txt -o /tmp/requests.pex
```
with the constraints file
```
requests==2.12.1
aiohttp==1.2.0
```
resulted in a pex that had requests versioned 2.12.1, but not aiohttp.
I really wanted to start the conversation with this PR: I'm new to the Pex code and didn't know the best place to implement this, so I wanted to get feedback on an approach before doing a bunch of work to add tests.
One issue along the way: conflicts arose when attempting to reference the same package twice:
```
pex requests requests==2.12.1 -o …
```

--constraints in pex

---

pex/pex.py

Add dummy flush method for clean interpreter exit with python3.6

---

.travis.yml
pex/bin/pex.py
pex/iterator.py
pex/package.py
pex/requirements.py
pex/resolver.py
pex/resolver_options.py
pex/testing.py
pex/version.py
setup.py
tests/test_iterator.py
tests/test_package.py
tests/test_pex_binary.py
tests/test_requirements.py
tests/test_resolver.py
tox.ini

This change both allows control over whether prereleases are allowed
when resolving requirements and changes the default from allowing
prereleases to disallowing them - in line with pip behavior.
Support includes a pip-alike `--pre` cli option, support for `--pre` in
requirements.txt files, and API support for consumers of the pex
library, notably pants.
This closes #28.

Add support for controlling prerelease resolution.

---

CHANGES.rst
pex/package.py
pex/version.py
setup.py

This dependency was not included in the pex `.bootstrap/` previously
leading to issues with use of pex as a library. We use the vendored
version from setuptools for now - which it leaks through its API. Notes
are added in the right spots to deal with setuptools de-vendoring of
`packaging` in its newest releases when we upgrade setuptools next.
Closes #354

Ensure `packaging` dependency is self-contained.

---

pex/http.py

Fix CacheControl import.

---

pex/crawler.py
pex/http.py
tests/test_crawler.py

Lack of redirects support is notable when local PyPI server is used
with fallback to official one. For example, that's how pypiserver
implementation works.
On the PyPI pages all the package links are relative, not absolute.
What means that we cannot use original request url to construct full
package url to fetch it, we should respect the url to where we were
redirected.
Without redirects resolution we end with the urls which our pypiserver
cannot process and the HTTP 404 response obliviously will never match
the md5 package digest, so we'll fail on verification stage in anyway.
This fixes #200 #270

Follow redirects on HTTP requests

---

pex/resolver.py
tests/test_resolver.py

Ref: https://github.com/pantsbuild/pex/issues/178
The error is as follows:
1. Two resolvables, one pinned, the other not.
2. First pex run with clean cache works.
3. Change the pinned version.
4. Second pex run fails with Unsatisfiable.
The problem is that the non-pinned resolvable locates the cached dep
and only returns it. Since that version doesn't match the pinned
version, we fail. This fixes that behavior by returning both the
cached version and all uncached pypi packages for unpinned
resolvables.
We change the pinned version to test the use case where you have a
cached version of a dep and then you transitively pull in another
requirement that either has a tighter bound or a pin on a version not
found in the cache.

Fix corner case in cached dependency resolution

---

pex/bin/pex.py
pex/resolver.py
tests/test_resolver.py

* Add unit test and patch code to pass unit test
Bug description:
1. Exact resolvable and inexact resolvable
2. First run completes, pushes exact resolvable into cache
3. Second run fails with Unsatisfiable
Reproduce:
$ pex psutil psutil==3.2.1 -o test.pex
$ pex psutil psutil==3.2.1 -o test.pex
Could not satisfy all requirements for psutil:
psutil, psutil==3.2.1
The bug manifest itself in #178 because by default --cache-ttl is
set to None. This doesn't change those semantics. The default is still
None, so we simply don't return an exact resolvable found in cache
if the --cache-ttl isn't set. Doing so also fixes another bug where
--cache-ttl is set, there is an exact resolvable found in cache, but
it is expired.
It should be noted that this patch could affect the performance of
default pex …

Fix bug in cached dependency resolution with exact resolvable

---

pex/pex.py
pex/util.py
tests/test_util.py

Fixes #302
before:
```
[omerta pex (kwlzn/osxtras)]$ pex --version
pex 1.2.3
[omerta pex (kwlzn/osxtras)]$ pex six -o /tmp/six_broke.pex
[omerta pex (kwlzn/osxtras)]$ PEX_VERBOSE=9 PEX_PYTHON=/usr/bin/python /tmp/six_broke.pex 
pex: Detected PEX_PYTHON, re-exec to /usr/bin/python
...
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from six import wraps
File "<console>", line 1, in <module>
ImportError: cannot import name wraps
>>> import six; six.__file__
'/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.pyc'
>>>
```
after:
```
[omerta pex (kwlzn/osxtras)]$ tox -e …
```

Treat .pth injected paths as extras.

---

pex/bin/pex.py
pex/iterator.py
pex/package.py
pex/requirements.py
pex/resolver.py
pex/resolver_options.py
tests/test_package.py

This is a fix for #372
Reading the packaging code there was a semantic difference between "prereleases=None" and "prereleases=False"; this sets the default from False to None, like it is in pip; that way, you'll get a prerelease version if you explicitly specify it (with an inclusive operator).

Change prerelease default to None

---

pex/resolver.py
tests/test_resolver.py

Not sure if this is the best way to do this or test this, but while investigating another bug I noticed caching resolver always ignored prerelease versions, as it constructed it's own iterator and didn't take into account the options passed on resolve. This fixes that and tests it.

Pass allow_prerelease to other iterators (Static, Caching)

---

pex/resolver.py
tests/test_resolver.py

If an inexact dependency is specified, and a transitive dependency
with either a pin or a tighter bound is found later, Ambiguous
Resolvable can be raised. This is because the latest package is added
to processed_packages and then by the time the transitive dep runs
through the while resolvables loop, it's version doesn't match the
one found in processed_packages and Ambiguous Resolvable is raised.
This patch fixes it by 1) not raising an error if the packages don't
match and 2) after all resolvables are processed, loop back through
distributions and recreate the correct list of distributions from
resolvable_set.packages().
Fixes: #366

Potential fix for Ambiguous Resolvable bug in transitive dependency resolution

---

pex/pex_builder.py

We're finding some cases in our project (https://github.com/thought-machine/please) where the output .pex sometimes has different content for the same inputs, which harms incrementality; we think this should help that.

Sort keys in PEX-INFO file so the output is deterministic.

---

pex/resolver_options.py

Similarly to WheelTranslator and EggTranslator, pass the platform to SourceTranslator. Without it, SourceTranslator takes the current platform.

Pass platform for SourceTranslator

---

pex/version.py

In https://github.com/pantsbuild/pex/pull/355 package.py was updated to assume that the Requirement class has the specifier attribute.
The specifier attribute wasn't added to the Requirement class until setuptools 20.3 https://github.com/pypa/setuptools/commit/de4bdcffb9f11769465ba3b6bb67cfb8a5b196e2
The error when there is an older setuptools is
```
Exception message: Requirement instance has no attribute 'specifier'
```

Minimum setuptools version should be 20.3

---

.gitignore
pex/bin/pex.py
pex/resolver.py
pex/testing.py
tests/test_integration.py
tests/test_resolver.py

This revives and extends the prior attempt in #201 to forklift the multi-interpreter/platform resolve behavior from pants directly into pex to better support general usage via `pex(1)` (and transitively, the Heron team's Bazel+pex integration).
Fixes #68.

Add first-class support for multi-interpreter and multi-platform pex construction.

---

pex/bin/pex.py
tests/test_pex_binary.py
tests/test_pex_builder.py

This PR adds a new CLI option, `-p` or `--preamble-file`, that is used to provide a preamble to the pex builder object.
We use pex via its API in the internal build tooling at NerdWallet (👋, we're neighbors!).  We've been leveraging it for multi-platform support, but now that #394 / 1.2.9 has landed the only thing missing from the CLI that we leverage is the preamble in the builder, which was pretty easy to hook up.  Once this PR has landed we can remove all of the API integration and just rely on the `pex` CLI!
The CLI option and the PEXBuilder preamble functionality are covered by tests.
Local functional testing:
```
(pex-foo) 
evanborgstrom@evanborgstrom /tmp/preamble — u:34 j:1 (21:49:54 08.16)
#536 ❯❯❯ echo 'print "foo!"' > preamble
(pex-foo) 
evanborgstrom@evanborgstrom …
```

Allow passing a preamble file to the CLI

---

.travis.yml

Travis python environments are now modernized enough that this is not
needed.

Kill explicit `setuptools` install with `tox`.

---

.travis.yml
pex/common.py
pex/pex_bootstrapper.py
pex/testing.py
tests/test_pex_bootstrapper.py
tests/test_pex_builder.py
tests/test_util.py

Also use in one spot in the `pex.testing` module where we weren't
before.

Leverage `pex.common.open_zip`.

---

.travis.yml
docs/buildingpex.rst
pex/commands/bdist_pex.py
pex/compatibility.py
pex/http.py
pex/interpreter.py
pex/pep425.py
pex/pex_builder.py
setup.py
tests/test_compatibility.py
tests/test_http.py
tests/test_pex.py
tests/test_pex_builder.py
tox.ini

Kill support for python 2.6.

---

.travis.yml
pex/executor.py
setup.py
tox.ini

This allows for an upgrade in subprocess robustness when available that
Pants will leverage for one. Also formalize the pex optional
dependencies with `extras_require`, mainly for documentation purposes.

Leverage `subprocess32` when available.

---

pex/bin/pex.py
pex/pex.py
pex/pex_info.py
tests/test_integration.py

Problem:
Pex environments rely on the PEX_PATH environment variable to resolve modules from other pexes when composing them into a single pex. Python scripts that re-execute (like a server listening for fs changes, a Jupyter notebook)  throw an ImportError upon re-exec due to environment scrubbing that removes this PEX_PATH information. 
Solution:
Add a --pex-path argument to the pex client and plumb the data through to the pex-info metadata. Resolve pexes to compose into the current pex being built by reading from the new pex_path property of the pex-info metadata. This will ensure a self-contained environment that does not lose context on a python script re-exec. 
Relates to: https://github.com/pantsbuild/pants/issues/4682

Create --pex-path argument for pex cli and load pex path into pex-info metadata 

---

pex/bin/pex.py
pex/resolver_options.py
tests/test_pex_binary.py
tests/test_resolver.py

Pex takes a `--pre` option from the command line, but it does not pass
it correctly during build. We need to propagate it to resolver to get
the correct behavior.
Fixes #423

Fix handling of pre-release option.

---

pex/pex.py
pex/pex_info.py
pex/util.py
tests/test_integration.py
tests/test_util.py

Replace all usages of self._vars.PEX_PATH with a unified pex path composed from merging pex_path in PEX-INFO and PEX_PATH set in the environment. 
Problem:
pex_info.pex_path was being overwritten in _activate() in pex.py by the path set in the environment. 
Solution: 
Implement a util function to merge the paths into a single pex path for usage throughout pex.py, giving priority to the PEX-INFO pex path if both are set.

Improve PEX_PATH handling in pex.py

---

pex/pex_bootstrapper.py
pex/variables.py
tests/test_integration.py

Currently, if an application packaged as a pex builds and runs a product pex as part of its functionality (i.e. a Pants pex that builds and runs pexes), the interpreter selection logic in a product pex will short-circuit because the flag telling it to do so has already been set in the initial bootstrapping logic of the main app's pex. Consequently, when the main app runs a product pex as part of its functionality, the interpreter selection in accordance with a pexrc for the product pex is skipped because the environment (`os.environ`) now contains the `SHOULD_EXIT_BOOTSTRAP_REEXEC` flag set to `"True"` from the bootstrap phase of the main app's pex. 
This is because `SHOULD_EXIT_BOOTSTRAP_REEXEC` (the flag governing whether or not to re-exec) was being set in an ENV object variable, which …

Change PEX re-exec variable from ENV to os.environ

---

pex/pex.py

Since the last release `inherit_path` is a (non-empty) string and the path is therefore no longer scrubbed.
FYI, I realize it would be preferable to have a regression test for this and to run the tests prior to opening a PR, however I'm having hard time getting the tests to run behind the Chinese firewall.

scrub path when not inheriting

---

pex/resolver.py
tests/test_resolver.py

When resolving for a specific interpreter version, the pex resolver fails to resolve universal requirements that transitively require libraries with interpreter constraints that conflict with the target interpreter version (see: https://github.com/Julian/jsonschema/blob/master/setup.py#L43 ).
The short term solution is to allow the caller of pex.resolver#resolve to supply a blacklist dict that maps package name -> interpreter constraint, enabling the resolver to skip blacklisted requirement names at resolve time if the target interpreter conforms with the interpreter constraint. The long-term solution is to be addressed by https://github.com/pantsbuild/pex/issues/456. 
It is now possible for systems that build pex files (Pants) via the pex api to blacklist certain requirements that are …

Add blacklist handling for skipping requirements in pex resolver

---

tests/test_integration.py
tests/test_resolver.py

before:
```
[omerta pex2 (master)]$ tox -e style
GLOB sdist-make: /Users/kwilson/dev/pex2/setup.py
style create: /Users/kwilson/dev/pex2/.tox/style
style installdeps: twitter.checkstyle
style inst: /Users/kwilson/dev/pex2/.tox/dist/pex-1.3.2.zip
style installed: gitdb==0.6.4,GitPython==0.3.2rc1,pep8==1.4.5,pex==1.3.2,pyflakes==0.7.2,smmap==0.9.0,twitter.checkstyle==0.1.0,twitter.common.app==0.3.0,twitter.common.collections==0.3.0,twitter.common.contextutil==0.3.0,twitter.common.dirutil==0.3.0,twitter.common.lang==0.3.0,twitter.common.log==0.3.0,twitter.common.options==0.3.0,twitter.common.process==0.3.0,twitter.common.string==0.3.0,twitter.common.util==0.3.0
style runtests: PYTHONHASHSEED='3976592587'
style runtests: commands[0] | twitterstyle -n ImportOrder /Users/kwilson/dev/pex2/pex …
```

Repair style issues in master.

---

pex/compiler.py
pex/link.py
pex/pex_builder.py
pex/pex_info.py
pex/resolvable.py
tests/test_finders.py
tests/test_pex_builder.py

```
[omerta pex2 (master)]$ tox -e isort-check
GLOB sdist-make: /Users/kwilson/dev/pex2/setup.py
isort-check create: /Users/kwilson/dev/pex2/.tox/isort-check
isort-check installdeps: isort
isort-check inst: /Users/kwilson/dev/pex2/.tox/dist/pex-1.3.2.zip
isort-check installed: futures==3.2.0,isort==4.3.4,pex==1.3.2
isort-check runtests: PYTHONHASHSEED='1082216549'
isort-check runtests: commands[0] | isort -ns __init__.py -rc -c /Users/kwilson/dev/pex2/pex /Users/kwilson/dev/pex2/tests
ERROR: /Users/kwilson/dev/pex2/pex/link.py Imports are incorrectly sorted.
ERROR: /Users/kwilson/dev/pex2/pex/pex_builder.py Imports are incorrectly sorted.
ERROR: /Users/kwilson/dev/pex2/pex/compiler.py Imports are incorrectly sorted.
ERROR: /Users/kwilson/dev/pex2/pex/pex_info.py Imports are incorrectly …
```

Repair isort-check failure in master.

---

.travis.yml
pex/pex_builder.py
pex/testing.py
tox.ini

This helped reveal the cause of #470

Better error handling for missing setuptools.

---

docs/api/index.rst
docs/buildingpex.rst
pex/bin/pex.py
pex/environment.py
pex/finders.py
pex/interpreter.py
pex/package.py
pex/pep425tags.py
pex/platforms.py
pex/resolver.py
pex/resolver_options.py
pex/testing.py
tests/test_integration.py
tests/test_interpreter.py
tests/test_pep425tags.py
tests/test_pex_binary.py
tests/test_pex_bootstrapper.py
tests/test_platform.py
tox.ini

This PR includes two parts:
1) a squash merge of #316 that implements partial manylinux support and ABI targeting.
2) a squash merge of a fast-follow retrofit of #399 that completes manylinux support and ABI targeting, fixes all broken tests, adds tests and corrects a few breaking issues.
_N.B. #316 has already been reviewed, so feel free to review only the second commit in the "Commits" view._
The second part of this change provides the following:
- Puts manylinux support behind a feature flag for operational purposes (with implicit support for manylinux in any linux platform targeting).
- Carries forward the `Platform` abstraction w/ the notion of the new extended form and adds test coverage.
- Removes manual `Resolver._identity` construction in favor of `PythonInterpreter.identity` …

Complete manylinux support in pex.

---

.travis.yml

This eliminates testing for python3.3, based on these deprecation warnings and issues seen in https://travis-ci.org/pantsbuild/pex/jobs/380524527#L504 :
```
Installing setuptools, pip, wheel...
Complete output from command /home/travis/build/p....tox/py33/bin/python - setuptools pip wheel:
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
...
Collecting wheel
wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
```

Eliminate the python3.3 shard.

---

RELEASE.rst

This is more aggressively cached by pip as of the new warehouse backend for PyPI.

Update RELEASE.rst pip usage for cache avoidance

---

.travis.yml
tests/test_bdist_pex.py
tox.ini

Use pytest keyword collection to omit integration tests by default. Use a new tox env to pass a positional arg that overrides the default POSARGS for py.test in tox.ini. 
I only did {py27, py26, pypy}-requests because that is what runs when you run a local `tox` command, but I am happy to add more.

Isolate integration tests onto their own shard

---

pex/bin/pex.py
tests/test_integration.py

Pex supports adding sources and resources directly via the PEXBuilder API, but not the CLI. This adds flags to allow adding sources and resources via directories.
Fixes #490
Fixes #491 
I paired on this with @dotordogh! 
Two questions came up while working on this
- what should happen if the output location is inside the input path?
- it looks like if the entry point doesn't exist, pex won't complain. Maybe it should?

Add resource / source bundling to pex cli

---

pex/version.py
tox.ini

After a long release hiatus, `wheel` has cut more releases beyond our currently pinned version that should be innocuous to consume: https://github.com/pypa/wheel/blob/master/CHANGES.txt

Bump wheel version to latest.

---

docker/base/Dockerfile
docker/user/Dockerfile
docker/user/create_docker_image_user.sh
dtox.sh

Although this could be used as a stepping stone to containerized
Travis CI, in the short term it helps me have a working test
environment. The `pex.testing.ensure_python_interpreter` fails to
install CPython 2.7.9, 2.7.10, etc. on Arch Linux atm.

Introduce a controlled env for pex testing.

---

pex/interpreter.py
pex/testing.py
tests/test_interpreter.py

The `PythonInterpreter.from_binary` method now caches by a full stable
key over all input parameters fixing previously order-dependent caching.
In addition, an `include_site_extras` argument is added to allow the
caller to request a bare interpreter (by passing `False`) with none of
the extra distributions installed in the interpeter `site-packages`
directory.
Fixes #509
Fixes #510

Fix `PythonInterpreter` caching and ergonomics.

---

.travis.yml

All of our shards are now and foreseeably `language: python`.

Simplify `.travis.yml`.

---

pex/archiver.py
pex/common.py
tests/test_common.py

Previously, a zipped pex would lose permission bits when exracted to the
filesystem for `--not-zip-safe` pexes or `PEX_FORCE_LOCAL` runs. This
was due to an underlying bug in the `zipfile` stdlib tracked here:
https://bugs.python.org/issue15795
Work around the bug in `zipfile.Zipfile` by extending it and running a
chmod'ing cleanup whenever `extract` or `extractall` is called.
Fixes #527

Fix pex extraction perms.

---

pex/installer.py
pex/testing.py
tests/test_installer.py

Fix installers to be insensitive to extras iteration order.

---

pex/pex.py
pex/testing.py
tests/test_pex.py

Previously, if a PEX had a custom interpreter, it was not threaded
through to the environments it activated. Add a test that the
designated interpreter is used.
Fixes #522

Fix PEX environment setup.

---

pex/common.py
tests/test_common.py

Failing tests are added that now pass.
Fixes #536

Preserve perms of files copied to pex chroots.

---

pex/testing.py
pex/version.py

We now just exclude the island where setuptools ran a disruptive
de-vendoring experiment.

Expand the range of supported setuptools.

---

pex/pex.py
tests/test_pex.py

It's surprising when using a pex in python interpreter mode that `-` is
not recognized as a program coming from stdin as regular python
interpreter would. Add support for this with a test.
The surprise of this missing feature was rightly identified in the
context of https://github.com/pantsbuild/pants/pull/6275.

Support `-` when running as an interpreter.

---

.travis.yml
pex/finders.py
pex/testing.py
tests/test_finders.py
tests/test_integration.py
tox.ini

Support -c for plat spec dists in multiplat pexes.

---

pex/pex.py
pex/testing.py
tests/test_integration.py
tests/test_pex.py

Previously we polluted the third party import space with any third
party dependencies of the pex bootstrap code (currently a subset of
setuptools). We now unimport all third_party code in bootstrap and
place bootstrap at the end of `sys.path` before handing off to user
code to allow their custom versions of overlapping third party code
to be imported.
Added a failing test that the demoted_bootstrap code now fixes.
Fixes #437.

Cleanup bootstrap dependencies before handoff.

---

pex/common.py

I was experiencing an error of "TypeError: must be type, not classobj"
on the line using `super()._extract_member()` below.
This error appears to be due to the `zipfile.ZipFile` class never inheriting from
`object` which is a requirement since py2.2 (2001).
Since the use of `super()` in `PermPreservingZipFile()` depends on
`object` being somewhere in the inheritance tree, I am including it in
the class definition of `PermPreservingZipFile()`. My testing of this patch
locally has proven to solve the "TypeError" I was seeing.

Fix for super() usage on "old style class" ZipFile

---

pex/pex.py
pex/testing.py
tests/test_pex.py

Previously only root 3rdparty packages copied into the bootstrap were
unimported leaving subpackages in-place. This could lead to a mismatch
in 3rdparty package API expectations when a re-imported 3rdparty root
package from the user PEX sys.path was from a different version of the
3rdparty package.
Fixes #550

Fixup `PEX.demote_bootstrap`: fully unimport.

---

pex/pex.py
tests/test_pex.py

This emulates the behavior of the python interpreter as we already do for
`-` and <file>.
Fixes #547

Add support for `-m` and `-c` in interpreter mode.

---

.travis.yml
pex/testing.py
scripts/ci.sh
tests/test_interpreter.py

Add OSX shards.

---

pex/bin/pex.py
pex/testing.py
tests/test_installer.py
tests/test_integration.py
tests/test_interpreter.py
tests/test_pex.py
tests/test_pex_bootstrapper.py

Master is currently timing out trying to fetch and build 7 interpreters.
Since We have no need for seven, constrain the interpreter count. Along
the way fix a flaky test that exposed production code not setting up all
interpreters.

Minimize interpreter bootstrapping in tests.

---

tests/test_integration.py

I ran into the following in `test_jupyter_appnope_env_markers` this am`:
```
Could not satisfy all requirements for prompt-toolkit<2.0.0,>=1.0.4:
prompt-toolkit<2.0.0,>=1.0.4(from: ipython<6), prompt-toolkit<2.1.0,>=2.0.0(from: jupyter==1.0.0->jupyter-console)
```

Apply more pinning to jupyter in IT.

---

pex/pex_builder.py
pex/testing.py
tests/test_bdist_pex.py

Previously clone copied distributions twice. One copy was made by the
underlying `Chroot`, and then another was manually performed. The
manual copy was only needed to update the internal `_distributions`
set, so just do that.
A test that failed before the fix is added to ensure distributions with
unwriteable files can be cloned.
Fixes #570

Fix PEXBuilder.clone.

---

tests/test_integration.py

The jupyter dist is just a meta-dist with fully unconstrained deps on ~6
other dists. This test was added to test environment marker support in
pex, which ipython - not jupyter - leverages heavily.

Narrow the env marker test.

---

pex/bin/pex.py
pex/resolver.py
tests/test_integration.py

PR #571 regressed the half-broken state of having
`--interpreter_constraint` selected interpreters not setup to also
having `--python` selected interpreters also not setup. In addition,
PR #568 incorrectly classified the current Platform passed by
`resolve_multi` as a user-specified extended platform specification
breaking custom interpreter resolution. Fix both and add tests that
failed prior to this combination of fixes.
A more comprehensive fix is tracked in part by #579.

Fix resolve regressions introduced by the 1.4.8.

---

pex/interpreter.py
pex/pex_info.py

Kill an unused type in `PexInfo` as well as our last remaining use of
`pkg_resources.get_platform`. Also kill unused `COMPATIBLE_SETUPTOOLS`
constants in `PythonInterpreter`.

Cleanup `PexInfo` and `PythonInterpreter`.

---

pex/bin/pex.py
pex/environment.py
pex/resolver.py
tests/test_environment.py
tests/test_integration.py
tests/test_pex.py
tests/test_resolver.py

We've had support for environment markers on the resolve side for a
while and with just a little plumbing we can now support multi-python
pexes with environment-specific requirements.
Fixes #456

Support environment markers during pex activation.

---

pex/environment.py
pex/resolver.py
tests/test_integration.py

Previously, only transitive requirements were filtered.
Fixes #456 
Fixes #122

Filter top-level requirements against env markers.

---

pex/testing.py

During my local testing, I hit an exception that the pyenv versions required for certain tests do not exist in the pyenv registry. I needed to `git pull` to fix this, and this change runs a git pull in pyenv every time there is an update to pyenv/pyenv/master.
There is probably a better way to do this - perhaps running `pyenv install --list` and searching for the versions we want would be sufficient and obviate the need for a `rev-list` or `pull`. However, the method used in this change is a bit more dynamic and adaptable to new versions we might wish to test with in the future (but also adds some overhead for git ops).
cc: @jsirois

Update pyenv if neccesary

---

tests/test_integration.py

Ensure the entrypoint function used to test both entrypoints and modules
explicitly tests that it's the import that works and then chains the
appropriate return / `__main__` behavior to express the result of the
test.

Fix *_custom_setuptools_useable ITs.

---

pex/pex.py
tests/test_integration.py

Currently the exit code from an entrypoint is swallowed, so running pex
always exits 0.
Tested with:
```
tox -e py27-package
dist/pex27 -e pytest:main pytest -D /path/to/failing/test/dir
```
before this PR, this exits 0, after it exits 1.
I'm not sure how to properly integration test this, as it is in the
outer-most wrapper layer of the pex binary, so looks like it's bypassed
by the way we tend to test things?

Pex exits with correct code when using entrypoint

---

pex/fetcher.py
tests/test_fetcher.py
tests/test_http.py
tests/test_iterator.py
tests/test_package.py

As of April 13th, 2018, pypi.org is the cannonical URL for PyPI.
The domain pypi.python.org still exists and redirects to pypi.org,
but might be disabled in the future.
https://packaging.python.org/guides/migrating-to-pypi-org/

Update PyPI default URL to pypi.org

---

pex/environment.py
tests/test_environment.py

In #582 and #592 support for environment markers was added to the pex
runtime. In so doing, the resolver was fixed to record full requirement
strings into PEX-INFO. Since part of those full requirement strings
could now include environment markers that selected for active extras,
a bug was introduced since we did not also add the active extras to the
environment marker evaluation environment.
This change adds a failing test that is fixed by properly setting up the
environment marker environment to include active extras.
Fixes #615.

Fixup PEXEnvironment extras resolution.

---

pex/environment.py

A quick, surface level fix for #598.

Repair unhandled AttributeError during pex bootstrapping.

---

pex/bootstrap.py
tests/test_pex.py

Previously, if the bootstrap appeared on sys.path multiple times it
would not be fully demoted.
Fixes #633

Ensure bootstrap demotion is complete.

---

pex/bin/pex.py
pex/installer.py
pex/testing.py
pex/vendor/__init__.py
tests/test_bdist_pex.py
tests/test_environment.py
tests/test_inherits_path_option.py
tests/test_integration.py
tests/test_pex.py
tests/test_pex_builder.py
tests/test_resolvable.py
tests/test_resolver.py
tests/test_util.py

This is the single bit of pex build-time that needs interpreters setup
with extras. Encapsulate setup there where it's safe to rely on the
vendor package and simplify the pex API as a result as evidenced by test
simplification.
Fixes #632

Setup interpreter extras in InstallerBase.

---

pex/finders.py
pex/vendor/_vendored/wheel/wheel/metadata.py

These bad escape sequences were causing `DeprecationWarning`s when running Pants with Python 3.
Invalid entries found through the regex `'re\..*\\'`, and equality to original string tested by comparing the two in a REPL.

Fix invalid regex and escape sequences causing DeprecationWarning

---

pex/__main__.py

Today I went to run pex using [pip-run](https://pypi.org/project/pip-run), but found that running `python -m pex` results in the usual error:
```
python3: No module named pex.__main__; 'pex' is a package and cannot be directly executed
```
Of course, one can use `python -m pex.bin.pex` but that's unintuitive. How about let the pex package also supply the pex command?

Allow pex to be invoked using runpy (python -m pex).

---

docs/recipes.rst

Issue: https://github.com/pantsbuild/pex/issues/657

Add recipe to use PEX with requests module and proxies.

---

pex/interpreter.py
tests/test_interpreter.py

We currently don't expect interpreter binaries to have a name such as `python3` or `python2`. However those are valid names for interpreters.
Ex:
```
$ python3 -c 'import sys; print(sys.executable)'
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
```
Add entry to support those filenames.

Fix interpreter finding

---

pex/http.py

At least some Python Index servers return a simple format of packages page, redirecting to <path>/<package> to <path>/+simple/<package>.
So there is a different result between `pex` run using `urllib` and using `requests` - in one case it errors.

Add User-Agent header when resolving via urllib

---

CHANGES.rst
pex/version.py

Prepare the 1.6.2 release.

---

pex/testing.py

Instead of trying to emulate running the pex command, actually just run
it. This is ~5% slower but perfectly robust to oddities of attempting
to run main "live".
Fixes #669.

Make `run_pex_command` more robust.

---

pex/bin/pex.py

Currently, it will try to resolve a path to an interpreter in `PEX_PYTHON_PATH` even if `PEX_IGNORE_RCFILES` is set.

Honor PEX_IGNORE_RCFILES in to_python_interpreter()

---

pex/third_party/__init__.py
pex/vendor/__init__.py
tox.ini

isort had a regression in 4.3.11 that it no longer respects `skip_glob` as we intended. See https://github.com/timothycrosley/isort/issues/885.
This motivated the problem, although there is reason to pin isort regardless of this regression. Linters and autoformatters often change their behavior with new releases. When this happens, we don't want someone's PR to fail due to an unrelated upstream change in that tool's behavior.
Pin isort to 4.3.10, the most recent release that does not have the `skip_glob` issue. Once this issue gets resolved, the version can be upgraded.
Also fix bad imports that weren't caught with our original isort runs.
Finally, convert CLI flags to use long names.

Pin isort version in CI

---

pex/bin/pex.py
pex/interpreter_constraints.py
pex/pex_bootstrapper.py
tests/test_integration.py

Resolves https://github.com/pantsbuild/pex/issues/655. 
We would expect a list of constraints, such as `['CPython>=2.7,<3', 'CPython>=3.4']`, to OR the separate list entries, i.e. allow an interpreter that satisfies any of these distinct requirement strings. Instead, we always AND lists of constraints.
Always `OR` a list of interpreter constraints. If the user wants `AND`, they may do so within the single requirement string via `,`, e.g. `'CPython>=2.7,<3'`.

OR interpreter constraints when multiple given

---

pex/bin/pex.py
pex/environment.py
pex/fetcher.py
pex/glibc.py
pex/pep425tags.py
pex/pex_bootstrapper.py
pex/pex_info.py
pex/pex_warnings.py
pex/third_party/__init__.py
pex/variables.py
tests/test_integration.py
tests/test_pex_bootstrapper.py
tests/test_pex_warnings.py
tests/test_platform.py

Previously warnings were emitted to stderr unconditionally, but now
both build-time and run-time controls are provided. At build-time
--no-emit-warnings can be specified and a pex will be produced that
does not emit warnings. At run-time, PEX_EMIT_WARNINGS and PEX_VERBOSE
can be used to toggle warning behavior.
Fixes #677

Provide control over pex warning behavior.

---

pex/pex_bootstrapper.py
tests/test_integration.py

Solves issue #656, where if no `PEX_PYTHON_PATH` and no `PEX_PYHON` are configured, we still honour `--interpreter-constraint` flag when bootstrapping a PEX.
There is an integration test that worked only when applied the last commit, but there is a lot of nuance to running it that I'd like a hand with. In particular, I'd like to know if there's a way of:
- Specifying "please ignore system-wide settings for PEX_PYTHON_PATH" in a test **or** Specifying 
"please override PEX_PYTHON_PATH with `None`". I think the first one should be easy to implement with a command-line flag defined in the same place as `--rcfile`.
- Specifying "This test only runs on Python3.5", because I need two different interpreters to play with (one for the environment that the pex runs in, another one to pass to …

Honor interpreter constraints even when PEX_PYTHON and PEX_PYTHON_PATH not set

---

pex/pex_bootstrapper.py

This was eliminated in #680 since it was (locally) unused but it turns
out it was used over in lambdex. The long term fix allowing safe
removal of the API is tracked by:
https://github.com/wickman/lambdex/issues/5.
Fixes #684

Restore `pex.pex_bootstrapper.is_compressed` API.

---

.travis.yml

The tox 3.8.1 release requires `-v` and `-e <env>` be passed as
seperate arguments where, before, `-ve <env>` was accepted. Since we
float our tox dependency in CI to match our lack of a bound on
developer tox installs, update to the new CLI syntax since it is
compatible with old tox too.

Correct .travis.yml tox syntax to work for 3.8.1+.

---

pex/glibc.py
pex/pep425tags.py
pex/platforms.py
scripts/style.sh
tests/test_environment.py
tests/test_integration.py
tests/test_pep425tags.py
tests/test_platform.py
tox.ini

Previously, we'd pass a single version to `get_supported` when we knew
one which would lead to a single tag being generated for the abi3 case
instead of one per previous minor version.
As part of this change, we need a more modern version of the
pep425tags.py we had copied from pip that allows passing multiple
versions to `get_supported`. Ideally, we'd use the version embedded in
our vendored setuptools code and this is tracked by #696. Extra code
had been added to pep425tags to implement `get_supported_for_any_abi`
and handle manylinux. This is now inlined in platforms.py, which was
the only user,  the door to using undisturbed copies in #696.
Fixes #539

Use all compatible versions when calculating tags.

---

RELEASE.rst
tox.ini

Switch releases to a single multi-pex.

---

pex/pex_bootstrapper.py
tests/test_pex_bootstrapper.py

Previously, `sys.executable` would be ignored if:
1. Selection fell back to `PATH` scanning.
2. The `sys.executable` was not on `PATH`.
3. No interpreters on `PATH` met interpreter contraints for the pex in
question.
We now always include the current interpreter as a candidate when
falling back to a `PATH` scan.
Fixes #700

Fix pex bootstrap interpreter selection.

---

pex/third_party/__init__.py

Hello!
I know pex doesn't officially support windows, but there seems to be a regression in pex 1.6.0 with windows with respect to the way the vendoring works. Specifically, the regex for iterating the zip path in the vendoring uses the os separator, which has two problems on windows (where the separator is `\`):
1. `\` is an escape sequence, so unless the separator is added twice in the string, it uses it to escape the character immediately after the separator, causing the regex compilation to fail.
1. The path in the zip file uses unix separators (`/`), so using the os separator is actually wrong.
This PR addresses this by updating the regex to replace windows separators (`\`) in the prefix var with the unix separator.

When iterating over Zipfiles, always use the Unix file separator to fix a Windows issue

---

tests/test_pex.py

Mechanically generated using `tox -eisort-run,style`. I'm not sure how
this got past CI.

Fix import sorting.

---

pex/variables.py
tests/test_variables.py

Before this change a `PexInfo` constructed with pexrc files ignored
would be subject to mutation through the side-effects of later
`os.environ` mutation. Guard against this by consistently copying the
environment the `PexInfo` is constructed with and add tests that ensure
the guard works.
Noticed working #710.

Make sure `PexInfo` is isolated from `os.environ`.

---

pex/pex.py

Addresses: https://github.com/pantsbuild/pex/issues/714

Make a copy of globals() before updating it.

---

pex/common.py
tests/test_integration.py

Per https://github.com/pantsbuild/pex/issues/716, we want to make Pex builds reproducible / deterministic.
As the first step in that process, we add failing acceptance tests that will act as the indicator of whether the issue is complete or not. As we get tests passing, such as the base test of no args, we will unskip those tests to avoid any regressions.
Here, we test the major permutations of building a Pex via `-o my-name.pex`, per https://pex.readthedocs.io/en/stable/buildingpex.html#saving-pex-files. We use Python's [`filecmp`](https://docs.python.org/3/library/filecmp.html) for a byte-by-byte comparison.
We must also add a `safe_sleep()` function to ensure Python 2 is not flaky, as `time.sleep()` is not guaranteed to run for the specified time until Python 3.5.

Add failing acceptance tests for reproducible Pex builds

---

README.rst

These newly documented commands are highly useful for Pants developers, and not immediately obvious for people who have no worked with Pex or used tox before.
However, we also want people reading the Tox docs and not solely relying on our guide, so we try to strike a balance between the two.

Document how Pex developers can run specific tests and run Pex from source

---

pex/bin/pex.py
tests/test_integration.py

Until Python 3.7 via https://www.python.org/dev/peps/pep-0552/, `.pyc` files were never reproducible because they included the timestamp. See the discussion at https://github.com/pantsbuild/pex/issues/716#issuecomment-487821354.
We are aiming to ensure reproducible builds a la https://github.com/pantsbuild/pex/issues/716 so that we can safely remote PEXes in CI. Reproducible builds also play an important role in security, per https://reproducible-builds.org.
Allow users to toggle on and off `.pyc` files via the new `--compile` / `--no-compile` flag.
We currently default to including `.pyc`, because this has been the precedent for 9 years. In a future release, e.g. 1.70, we will change the default to not include `.pyc` so that builds are reproducible by default, but people can still opt …

Introduce new `--no-compile` flag to not include .pyc in built Pex due to its non-determinism

---

tests/test_integration.py

If the `run_pex_command` failed, this would not be surfaced until `zipfile.py` would try to read the zipfile and find that the file is not existing.
Instead, we should eagerly assert that the command worked and output stdout and stderr if it did not.

Refactor reproducible build tests to assert the original pex command succeeded

---

pex/http.py
pex/variables.py
tests/test_http.py

By default, `requests` does not use a connect/read timeout. See https://2.python-requests.org/en/master/user/quickstart/#timeouts and https://github.com/pantsbuild/pants/pull/7659.
Fixes #26.

Add timeout when using requests.

---

pex/bin/pex.py
pex/common.py
pex/pex_builder.py
tests/test_common.py
tests/test_integration.py
tests/test_pex_builder.py

Part of https://github.com/pantsbuild/pex/issues/716 to make built PEXes be reproducible.
One of the major sources of unreproducibility is timestamps embedded into the zipfile. Python's `zipfile.py` uses the current system time when creating a new zipfile, per https://github.com/python/cpython/blob/45e92fc02d57a7219f4f4922179929f19b3d1c28/Lib/zipfile.py#L509. So, the Pex cannot be reproducible if built after the original run.
Introduce a new flag `--use-system-time` / `--no-use-system-time` that will toggle whether we use a deterministic timestamp or keep the default behavior of using the current system time. We will default to `--use-system-time` for now to keep prior behavior, and then in a future release like 1.70 will switch over to default to reproducible builds.
If …

Add new `--no-use-system-time` flag to use a deterministic timestamp in built PEX

---

pex/pex_info.py
tests/test_integration.py

Even though `PexInfo` stores its requirements as an `OrderedSet`, when getting converted into a `list` in the `dump()` function, the requirements were losing their deterministic order for an unclear reason.
Specifically, the acceptance test diverged with `PEX-INFO`, with both files having different orders for their requirements. 
```
"requirements": ["six==1.12.0", "cryptography==2.6.1", "cffi!=1.11.3,>=1.8", "asn1crypto>=0.21.0", "pycparser"]
["six==1.12.0", "cryptography==2.6.1", "asn1crypto>=0.21.0", "cffi!=1.11.3,>=1.8", "pycparser"]
```
Sort the requirements when being dumped to ensure we always have a consistent result.
We also make `interpreter_constraints`'s output always be sorted, as it is internally stored as a set so by definition is not deterministic in ordering.

Fix PexInfo requirements using a non-deterministic data structure

---

tests/test_integration.py

The `-c` acceptance test was failing not due to unreproducibility, but because the Pex was failing to be built in the first place. It simply needed to have the corresponding Python file be created to get working. Note that the failing test passed locally on macOS and an Ubuntu VM, but was failing in Travis—it now passes universally.
We also add a test to cover using `-c` from a 3rd party dependency, as we were originally only testing when building from source. Both are important cases to ensure reproducibility.

Fix reproducible build test improperly using the -c flag and add a new test for -c

---

README.rst
pex/environment.py
tests/test_integration.py

This is a fix to the way we load pkg_resources, along with an integration test which fails on master since the setuptools vendoring in #624, but is fixed by the change in #713. This can be merged before that one to fix the failures induced in several 3rdparty packages, while #713 can be left to understanding and testing the separate but related problem that this change also happens to fix.

add delayed pkg_resources import fix from #713, with an integration test

---

pex/common.py

Automatically generated with `tox -eisort-run`. It's not clear how the
bad sort hit master - CI currently has a shard that runs `tox -v -e
isort-check` and that command properly fails on master.

Fixup import sorting.

---

pex/environment.py

Re-arrange namespace declaration logic slightly and provide a more
detailed explanation of the case we're being careful about.

Tighten up namespace declaration logic.

---

pex/resolver.py
pex/testing.py
tests/test_integration.py
tests/test_pex_builder.py
tests/test_resolver.py

The change in #582 introduced a bug where requested extras were not
preserved for local `setup.py` resolvables. Add failing tests for this
and fix.
Fixes #736

Fix resolution of `setup.py` project extras.

---

pex/interpreter.py
pex/pex_bootstrapper.py
pex/variables.py
tests/test_integration.py
tests/test_pex_bootstrapper.py
tests/test_variables.py

Ensure `PEX_PYTHON` and `PEX_PYTHON_PATH` are actually scrubbed from the
environment of the pex process when re-exec'd fixing #710. Also
uniformize re-exec interpreter selection to ensure that the current
interpreter is preferred when it meets any constraints fixing #709.
Fixes #709
Fixes #710

Fixup pex re-exec during bootstrap.

---

pex/environment.py
pex/pex.py
pex/pex_info.py
pex/testing.py
pex/util.py
tests/test_environment.py
tests/test_integration.py
tests/test_pex.py
tests/test_pex_info.py
tests/test_util.py

As referenced in #749 , I ran into a situation where `pkg_resources` was imported too early before `sys.path` was finalized, occurring in the situation where a pex in my `PEX_PATH` needed to invoke: `pkg_resources.get_distribution`.  This was failing because a namespace package caused `pkg_resources` to be imported before the other pexes were merged into the environment 
Therefore, wait until all deps from all pexes (i.e. pexes in `PEX_PATH`) have been resolved before attempting to declare the namespace packages. This ensures `sys.path` is finalized before `pkg_resources` is possibly imported.

Fix pkg resource early import

---

pex/pex.py
pex/testing.py
tests/test_integration.py
tests/test_pex.py

Previously we would fail to scrub any extras modules imported by the pex
bootstrapping code. Add failing unit and integration tests and fix this
with a missing scrub step to check modules (previously only packages
were scrubbed).
Fixes #745

Fix `sys.path` scrubbing of pex extras modules.

---

pex/pex.py
tests/test_pex.py

Guard against modules with a `__file__` of `None`.

---

pex/bin/pex.py
pex/pex.py
pex/pex_bootstrapper.py
pex/pex_info.py
pex/testing.py
pex/variables.py
tests/test_integration.py
tests/test_pex.py

Previously Pex would inherit `PYTHONPATH` by default despite the default
`--inherit-path` setting being false. This was buggy behavior running
against the primary Pex goal of providing an isolated execution
environment. Now, to use PYTHONPATH to amend the `sys.path` of a
running is accomplished by either of:
```
PEX_INHERIT_PATH=prefer PYTHONPATH=... ./my.pex
PEX_INHERIT_PATH=fallback PYTHONPATH=... ./my.pex
```
Update corresponding settings documentation and fix pex to consider
PYTHONPATH when adjusting sys.path.
Fixes #707

Include `PYTHONPATH` in `--inherit-path` logic.

---

pex/sorter.py
tests/test_resolvable.py
tests/test_sorter.py

`Iterator.iter()` iterates over the set of links returned from `Crawler.crawl()`. This means the hash seed randomization potentially changes the order, when there are two packages equivalent in both version, package type (wheel, etc), platform tags, and they're both remote.
Ideally, these would not be any different, so it's not really a correctness issue, but I am using pex's resolver internals to store the actual URLs used, and they flap over time between different-but-equivalent ones.
(And in case it's relevant: to be honest I tried running the integration tests locally, but they were failing before this change, and it didn't look related. Are they known to fail on macOS (10.14)?)

Avoid reordering of equivalent packages from multiple fetchers

---

pex/interpreter.py
tests/test_interpreter.py

On gentoo linux, my python binaries have the 'm' suffix, and then are symlinked from the non-suffixed versions:
usr/bin/python3.5 -> python3.5m
/usr/bin/python3.5m
/usr/bin/python3.6 -> python3.6m
/usr/bin/python3.6m
etc.
PEP-3149 indicates this is okay, so pex should probably support it.
I updated a test, but already have a bunch of tox failures on master so it's hard to know if it passes:
"15 failed, 61 passed, 3 skipped, 1 xfailed in 198.12 seconds"
I'll dig into that in another branch hopefully =)

PythonInterpreter: support python binary names with single letter suffixes

---

pex/bin/pex.py
pex/interpreter.py
pex/interpreter_constraints.py
pex/pex_bootstrapper.py
tests/test_pex_bootstrapper.py

Preiously we made some effort towards this, but were not thorough.
Fix all interpreter selection logic to be both lazy and bias towards
re-using the current interpreter, only falling back to picking the
minimum version compatible interpreter from all possible compatibile
interpreters as the very last step.
Addresses item 1 in #782.

Bias selecting the current interpreter.

---

pex/bin/pex.py
tests/test_integration.py

This follows up on the decision to switch Pex defaults to do so made
in #718.

Pex defaults to reproduceable builds.

---

pex/pex_bootstrapper.py
tests/test_pex_bootstrapper.py

Biasing interpreter selection towards the current interpreter was
implemented in #783 but not test was added. Add a test that fails due to
a bug in path trimming logic and fix the bug.

Fix `iter_compatible_interpreters` path biasing.

---

pex/bin/pex.py
pex/pip.py
pex/platforms.py
pex/resolver.py
pex/testing.py
pex/variables.py
tests/test_integration.py
tests/test_interpreter.py
tests/test_pex.py
tests/test_pex_binary.py
tests/test_pex_bootstrapper.py
tests/test_platform.py
tests/test_resolver.py

Three aspects of current platform handling are fixed:
1. Ensure that `Platform.supported_tags` returns the full range of tags
when the platform is current. This uses the special no-arg form of
`pep425tags.get_supported` which consults the local interpreter to
return the broadest possible set of tags. Also ensure that we always
pass all compatible versions when the platform is not current to
generate the broadest possible set of tags for the foreign platform.
2. Ensure that the resolver interprets 'current' to mean any local
interpreter instead of just the current runtime interpreter. This is
faithful to prior behavior where a PEX built for the 'current' platform
would always work on the current machine.
3. Fix the PEX cli when run with a fully foreign set of `--platform`s.
Previously the …

Fix current platform handling.

---

tests/test_integration.py

The `test_interpreter_selection_using_os_environ_for_bootstrap_reexec`
test needed to be updated to include `pex.testing`'s new `pytest`
requirement.

Fix tests/test_integration.py.

---

pex/pip.py
tests/test_integration.py

Previously we did not do this and could thus confusingly fail resolves
against explicitly requested insecure repos.
Fixes #812

Implicitly trust explicitly requested repos.

---

pex/bin/pex.py
pex/interpreter.py
pex/resolver.py
tests/test_resolver.py

Previously the cache was only used by pip for http queries. Now we also
use the cache to skill wheel installs in their isolated chroots.
Fixes #809
Fixes #811

Use the resolve cache to skip installs.

---

pex/bin/pex.py
pex/compatibility.py
pex/distribution_target.py
pex/interpreter.py
pex/jobs.py
pex/pex_builder.py
pex/pip.py
pex/platforms.py
pex/resolver.py
pex/testing.py
tests/test_integration.py
tests/test_jobs.py

The three major phases of a pex resolve: download, build and install,
are delegated to pip subprocesses. As such, we can easily parallelize
these operations only needing to take care of shared portions of the
filesystem the processes might mutate. In the end this is only relevant
to the build and install phases which are natural points to cache
results in a shared filesystem cache. The install phase is already
cached in this way (#815) and we add caching for the build phase as
well, both utilizing (posix in the end) guarantees around `os.rename`.
The atomic shared directory updates are achieved with `AtomicDirectory`
and the subprocess parallelization is acheived using the new `jobs`
module and request / response data object pairs to coordinate parallel
pip jobs.
Example speedups:
+ PEX …

Parallelize resolve.

---

pex/bin/pex.py
pex/common.py
pex/environment.py
pex/pex_builder.py
pex/pex_info.py
pex/resolver.py
pex/util.py
pex/variables.py
tests/test_common.py
tests/test_environment.py
tests/test_integration.py
tests/test_unified_install_cache.py
tests/test_variables.py

Previously these caches were seperate. Downloaded wheels and sdists were
cached in `~/.pex/build` and wheels unzipped from zipped pexes at
runtime were cached to `~/.pex/install`.
Now the caches are unified by the resolver such that any wheel installs
performed by it can be seen by zipped PEXes on the same machine when
they go to potentially unzip wheel distributions stored within at PEX
boot time.
N.B.: The cache is not unified in the other direction. If a zipped PEX
is executed on the same machine a PEX build resolve later happens on,
any intersecting wheels will be re-downloaded, built and installed by
the resolve finally unifying the caches from that point forward.
Fixes #820

Unify PEX buildtime and runtime wheel caches.

---

setup.py

We no longer use requests or CacheControl as optional enhancements, our
vendored pip does and it vendors those in.

Cleanup extras_require.

---

pex/environment.py
pex/finders.py
pex/pex.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/testing.py
pex/util.py
tests/test_bdist_pex.py
tests/test_environment.py
tests/test_finders.py
tests/test_integration.py
tests/test_pex.py
tests/test_pex_builder.py

We no longer used any of this in production except for one `PEXBuilder`
API which is converted to use `pex.pip` to install zipped wheels when
encountered so that they can be found by standard `pkg_resources`
finders.
Tests that use zipped wheels are similarly updated.

Kill `pkg_resources` finders monkey-patching.

---

pex/bin/pex.py
pex/environment.py
pex/package.py
pex/pex_builder.py
pex/pip.py
pex/resolver.py
pex/testing.py
pex/variables.py
tests/test_finders.py
tests/test_integration.py
tests/test_unified_install_cache.py

Previously, pip might warn in red that versions were mismatched but
we would get no failure until pex runtime resolution. Improve pex
runtime resolution error messages and implement pex buildtime
resolution sanity checks when --no-ignore-errors.
At buildtime we now get:
```
$ python -mpex wheel pantsbuild.pants==1.24.0.dev2
Failed to resolve compatible distributions:
1: pantsbuild.pants==1.24.0.dev2 requires wheel==0.31.1 but wheel==0.33.6 was resolved
```
And the corresponding runtime error is now:
```
$ PEX_IGNORE_ERRORS=false python -mpex wheel pantsbuild.pants==1.24.0.dev2 --ignore-errors
Failed to execute PEX file. Needed linux_x86_64-cp-38-cp38 compatible dependencies for:
1: wheel==0.31.1
Required by:
pantsbuild.pants==1.24.0.dev2
But this pex only contains: …
```

Fix pex resolution to respect --ignore-errors.

---

pex/vendor/__init__.py
pex/vendor/__main__.py
tests/test_vendor.py

This will support using a patched version of pip pending acceptance
of patches upstream.
Work towards #823.

Support VCS urls for vendoring.

---

pex/third_party/__init__.py
tests/test_third_party.py

Previously we would de-vendor pex once per CLI invocation in a new
temporary directory. Now we de-vendor once per pex version under the
pex root (~/.pex/isolated/...) by leveraging existing hashing and atomic
directory creation tools.

De-vendor pex just once per version.

---

tox.ini

This was missed in #826 but noticed creating #842 where pex.pex startup
was slower than expected due to not using the current (python 3.8)
interpreter and instead proceeding to find all interpreters and then
select the min.

Fix `tox -epackage` to create pex supporting 3.8.

---

pex/common.py

Fallback to copy if there is an EPERM or EXDEV error when calling os.link()

Handle EPERM when Linking

---

pex/common.py

This follows up on #852 to provide more explanation of how a copy can
succeed where a hard link fails due to apparent permission issues.

Explain hard link EPERM copy fallback.

---

pex/interpreter.py
pex/jobs.py
pex/resolver.py
tests/test_bdist_pex.py

This speeds up both pex builds and pex executions on machines with
multiple interpreters and `--interpreter-constraint`s in-play.
Work towards #782.

Parallelize interpreter discovery.

---

pex/interpreter.py
tests/test_pex_bootstrapper.py

Previously, Pex encounered hard to diagnose errors when selected
interpreters were pyenv shims. These shim files can represent a
different interpreter on different executions which broke Pex's
assumption that a given binary always corresponded to a given python
version.
Since we already shell out to an interpreter to gather its
`PythonIdentity`, we now include collecting the real final interpeter
path from `sys.executable` there. This allows pex to see through a shim
to the underlying `$PYENV_ROOT/versions/<version>/bin/python*`
interpreter which conforms to the expectation of a given binary
corresponding to a given python version.
See: https://github.com/pyenv/pyenv/issues/1112
Debugged working #856 which hit otherwise un-explainable errors in
`tests/test_pex_bootstrapper.py`.
Work …

Harden PythonInterpreter agains pyenv shims.

---

.travis.yml
pex/testing.py
tests/test_integration.py
tests/test_interpreter.py
tests/test_pex.py
tests/test_pex_binary.py
tests/test_pex_bootstrapper.py

It turned out the fundamental issue was a bad version of curl which was
actually hinted at by the dump originally included in #477. We've since
updated our linux image to bionic which happened to fix the issue moving
to a newer curl as a side-effect.
This change re-enables disabled tests as well as converting a test
skipped previously due to this blanket issue to a more specific,
legitimate skip. The `.travis.yml` is also cleaned up a bit.
The hint this might be worth pursing came from:
https://github.com/unbit/uwsgi/issues/37#issuecomment-10295067
Fixes #477

Re-enable pyenv interpreter tests under pypy.

---

scripts/package.py
tox.ini

Previously we had to keep these values in sync and failed to do so often
enough leading to released Pex PEXes that would fail to run under
interpreters they should run under.

Ensure Pex PEX contraints match pex wheel / sdist.

---

pex/distribution_target.py
pex/resolver.py
pyproject.toml
tests/test_resolver.py

Previously we failed to do this and would erroneously fail resolves as
a result.
Fixes #851

Respect env markers when checking resolves.

---

pex/vendor/__main__.py
tox.ini

- Force specific versions of setuptools and wheel to be used
when running pip during vendoring.
- Force the vendor-check test to run on python 3.8.
These address issues in our tests, where re-vendoring pip caused
slight differences in its metadata, causing the `git diff` check to
fail.

Improve hermeticity of vendoring.

---

tests/test_integration.py

In some tests we just checked that expected invocation failures
happened. These tests would continue to pass if the failure reason
changed from the one we expected.
This change makes the tests check the invocation's stderr for the
expected failure output.
It adds a TODO to verify whether one of those tests is intended to
fail for the reason checked (a wheel compatibility issue).

Check expected pex invocation failure reason in tests.

---

pex/resolver.py

If a requirement is resolved vacuously due to a platform constraint
(e.g., 'pathlib2; python_version < "3"' when we're on Python 3) then
it is not an error to not have a resolved dist.

Fix the resolve check in the presence of platform constraints.

---

pex/resolver.py

This reverts commit 89f026c729b9c96806a6a30501eb34ff66d0f2c9.
That change was based on a misreading of the error, not realizing that it
was already fixed in #861, but that the fix wasn't present when the error
manifested.

Revert "Fix the resolve check in the presence of ... (#877)"

---

pex/third_party/__init__.py

Previously we used filesystem operations, which assumes
that the pex code is available on the filesystem. This is
not the case, e.g., when bootstrapping a zipped pex file.
This change replaces the os.walk-based implementation
with one that uses equivalent pkg_resources operations.

Use pkg_resources when isolating a pex code chroot.

---

pex/interpreter.py
tests/test_interpreter.py

The exception class already existed, it just wasn't used.
Due to caching, the interpreter may or may not fail
in find_binary(), so the calling code might fail at some
later stage.
This change causes us to fail eagerly and consistently if
the binary doesn't exist on disk.

Error eagerly if an interpreter binary doesn't exist.

---

pex/interpreter.py
tests/test_interpreter.py

Useful in the Pants interpreter selection tests.

Add a clear_cache() method to PythonInterpreter.

---

pex/vendor/README.md
pex/vendor/__init__.py
pex/vendor/_vendored/pip/pip/_internal/index/collector.py

New version is still a patched 20.0.dev0, with a new patch
to fix a performance issue.
Fixes #887

Revendor pip

---

pex/interpreter.py
tests/test_bdist_pex.py

Previously the test relied upon the tox venv interpreter (which
implicitly builds and installs the pex wheel) being the interpreter that
executed the `python setup.py bdist_pex ...` command. This assumption
could be violated when running under `pyenv` which OSX CI shards do.
Instead, explicitly add pex to the `PYTHONPATH` of the interpreter and
let distutils know about `bdist_pex` via `--command-packages`.
Fixes #896

Convert `bdist_pex` tests to explicit cmdclass.

---

pex/bin/pex.py

If PEX_ROOT is set, its value is shown in the --pex-root help string
```console
$ export PEX_ROOT="$HOME/.cache/pex"
$ pex --help 2>&1 | grep .-root
--pex-root=PEX_ROOT   Specify the pex root used in this invocation of pex. [Default: ~/.cache/pex]
```

Show pex-root from env as default in help output

---

pex/pip.py
pex/resolver.py

Now that `AtomicDirectory` is used to do the install there will always
be a fresh empty dir to install to and so there will never be a need to
overwrite an existing installation or upgrade it.

Kill `Pip.spawn_install_wheel` `overwrite` arg.

---

pex/pip.py

Pex will want to warn about deprecated support for Python 2.7 some day,
but it is not Pips job to do so on our behalf. Our support cycles are
independent since we vendor in a given version of Pip for ~as long as
we want / need.

Silence pip warnings about Python 2.7.

---

pex/interpreter.py

This was added when it was though it would be useful for Pants. It
turned out not being used / needed.

Remove unused Interpreter.clear_cache.

---

pex/third_party/__init__.py

We implement devendoring of a dist by pointing to its
directory under pex/vendor/_vendored, either in an
isolated copy, or in the executing source tree.
Previously we deleted the `__init__.py` in the top-level dir
before yielding it as a de-vendored root. Presumably this
was done because root-level `__init__.py` files are neither
required nor useful, and only exist because we add them
when vendoring.
However we do sometimes treat those vendored roots as nested,
non-root packages. Specifically, in pex.third_party._Loader.load_module, 
we attempt to load modules using the full path from our root. E.g.,
pex.vendor._vendored.setuptools.pkg_resources.
If we delete the `__init__.py` from pex.vendor._vendored.setuptools
(say in a cached isolated pex exposure dir), then a subsequent
attempt to …

Don't delete the root __init__.py when devendoring.

---

pex/dist_metadata.py
pex/environment.py
pex/resolver.py
tests/test_integration.py

Previously Pex did not properly handle activation of wheels with
`Requires-Python` metadata restricting the wheel use to certain Python
interpreter versions.
Fixes #898

Respect `Requires-Python` in `PEXEnvironment`.

---

pex/bin/pex.py

Pants shows the pex error to the end user, and this
extra context is very helpful.

Add detail in interpreter selection error message.

---

pex/bin/pex.py
pex/interpreter_constraints.py
pex/pex_bootstrapper.py
tests/test_integration.py
tests/test_pex_bootstrapper.py

Centralize messaging in a new exception type and incorporate this in the
CLI and at PEX runtime. API users can use the new structured exception
type as they wish.
Fixes #922

Improve interpreter not found error messages.

---

pex/bin/pex.py
pex/pex_builder.py
pex/pex_info.py
tests/test_integration.py

Adding the option to set the PEX root in in built PEXes.
The option already existed for use from the PexInfo API but was not
exposed to the CLI.
Work towards #746
Work towards #926

Adding `--runtime-pex-root` option.

---

pex/compatibility.py

This appears unused, but takes about 20ms to import:
Before this change:
```
pex$ mkdir -p trivial && echo 'print("Hello")' > trivial/trivial.py && python3.6 -m pex -D trivial -m trivial -o trivial.pex && multitime -n 50 python3.6 ./trivial.pex >/dev/null
===> multitime results
1: python3.6 ./trivial.pex
Mean        Std.Dev.    Min         Median      Max
real        0.494       0.032       0.448       0.486       0.600
user        0.433       0.027       0.395       0.428       0.518
sys         0.056       0.005       0.049       0.055       0.072
```
After this change:
```
pex$ mkdir -p trivial && echo 'print("Hello")' > trivial/trivial.py && python3.6 -m pex -D trivial -m trivial -o trivial.pex && multitime -n 50 python3.6 ./trivial.pex >/dev/null
===> multitime results
1: python3.6 …
```

Remove second urllib import from compatibility

---

pex/bin/pex.py
pex/pex.py
pex/pex_info.py
pex/testing.py
scripts/package.py
tests/test_integration.py
tests/test_pex.py
tests/test_variables.py

Previously, `PEX_*` environment variable stripping incorrectly stripped
`PEX_*` environment variables in host process when the `PEX.run` API was
used. This is fixed and an option to not strip pex environment variables
at all is added to `PexInfo` / the Pex CLI. This new option is used to
publish a Pex PEX that supports control via environment variables.
Fixes #180
Fixes #925
Work towards #926

Fix `PEX_*` env stripping and allow turning off.

---

pex/bin/pex.py
pex/common.py
pex/pex_bootstrapper.py
pex/pex_info.py
pex/pex_warnings.py
pex/pip.py
pex/variables.py
tests/test_common.py
tests/test_integration.py
tests/test_pex_info.py
tests/test_variables.py

In the past, portions of the pex cache could be controlled individually
but this was no longer the case in practice nor was it desirable. Unify
all cache handling under the PEX_ROOT and deprecate `--cache-dir` to
codify the new single pex cache as the PEX_ROOT.
Also add best-effort support for always finding a a viable PEX_ROOT even
when the configured value is not writeable. In conjunction with
`--runtime-pex-root` this provides for both a Pex CLI and created PEXes
that should always work wrt having a viable PEX_ROOT but still display a
warning if a suboptimal alternate had to be used.
Fixes #746
Fixes #816
Fixes #926

Sanitize PEX_ROOT handling.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.7 release.

---

pex/pip.py
pex/third_party/__init__.py
tests/test_third_party.py

Previously, the pip.pex was re-created once per Pex CLI run. Now it is
created once per unique Pex distribution.
Perf result difference for a single distribution PEX indicates this
shaves off ~600ms of overhead for a warm cache (after the 1st run of the
Pex CLI at a given version):
Before (Pex 2.1.7):
```
$ multitime -s 2 -n 10 python -m pex psutil -o psutil.pex
===> multitime results
1: /home/jsirois/.venv/pex1.6/bin/pex psutil -o psutil.pex
Mean        Std.Dev.    Min         Median      Max
real        2.044       0.008       2.030       2.046       2.060
user        1.690       0.038       1.636       1.700       1.751
sys         0.220       0.039       0.164       0.210       0.273
```
After:
```
$ multitime -s 2 -n 10 python -m pex psutil -o psutil.pex
===> multitime results
1: …
```

Cache pip.pex.

---

pex/bin/pex.py

Hi 👋 
We ran into the following exception during a pex build recently:
```
07:31:25  IsADirectoryError: [Errno 21] Is a directory: '/home/jenkins/workspace/project-PR-123/python'
```
This happened because we specify `--python=python` on the pex command line (some of our projects build for different interpreters) and the project had a directory named "python" at the root of their project.
This is fairly easy to reproduce:
```
$ mkdir /tmp/pex
$ cd /tmp/pex
$ mkdir python
$ pex -o pex.pex --python=python pex
File "/Users/eborgstrom/bin/pex/.bootstrap/pex/pex.py", line 393, in execute
File "/Users/eborgstrom/bin/pex/.bootstrap/pex/pex.py", line 325, in _wrap_coverage
File "/Users/eborgstrom/bin/pex/.bootstrap/pex/pex.py", line 356, in _wrap_profiling
File …
```

Ensure the interpreter path is a file

---

pex/bin/pex.py
pex/pex_builder.py
pex/pex_info.py

This adds a `PexInfo.unzip` toggle and `--unzip` `--no-unzip` in the
CLI to mark a PEX file that should be unzipped before execution.
Combined with a stable PEX_ROOT cache, this can offer improved startup
latency in both cold and hot cases.
Work towards #930.

Support an unzip toggle for PEXes.

---

pex/bin/pex.py
pex/pex.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pex_info.py
pex/variables.py
scripts/package.py
tests/test_integration.py
tests/test_pex_info.py

Preserve `sys.argv[0]` as the original PEX zip file path and allow
runtime control of the unzip mode with `PEX_UNZIP`.
With these affordances in place, change the Pex PEX to ship in unzip
mode assuming the standard use will be multi-use with a stable
`PEX_ROOT`.

Better support unzip mode PEXes.

---

pex/bin/pex.py
pex/pex_builder.py
tests/test_pex_builder.py

This can greatly speed up repeatedly creating a pex when
no requirements have changed. A build tool (such as Pants)
can create a "requirements pex" that contains just a static
set of requirements, and build a final pex on top of that,
without having to re-run pip to resolve requirements.

Support for copying requirements from an existing pex.

---

pex/environment.py

PR #828 introduced a bug in the code that gathers the
requirers of requirements that failed to be resolved
(so that we can display those requirers in an error message.)
Specifically, reqs_by_key's values are lists of requirements,
so we need to call update() on each such value separately.

Fix runtime resolve error message generation.

---

pex/interpreter.py

Sort the keys in the INTERP-INFO json files and ensure interpreter hard
links get their own INTERP-INFO file.

Make the interpreter cache deterministic.

---

scripts/package.py
tox.ini

Add output of the packaged Pex sha256 hash and its size. Also add a new
serve tox environment for packaging a Pex PEX and wheel and then serving
them over http. The latter is useful for testing Pex with downstream
consumers like Pants.

Improve Pex packaging.

---

.travis.yml
tests/test_bdist_pex.py
tox.ini

Pin virtualenv just under 20.0.5 which is broken for Pex tests when run
under Python 2.7.
Along the way, tidy up tox tool installation by doing it in its own
venv.
Also document, update and align all Python versions used in the various
shards while killing use of pyenv shims.
Finally, kill no longer needed (and unwittingly unused) OSX specific env
vars intended to help pyenv compile ssl libs.
Fixes #967

Constrain the virtualenv version used by tox.

---

scripts/package.py
tox.ini

This significantly speeds up `--server` launch for local integration
testing when there are many local interpreters that match Pex
requires-python.

Add a `--local` mode for packaging the Pex PEX.

---

pex/resolver.py
tests/test_resolver.py
tox.ini

This change introduces download and install APIs that the existing Pex
resolve / resolve_multi APIs are composed from.
The new APIs will be used by Pants to split traditional resolution
(download in Pip terms) from compilation and install of wheels from the
downloaded distributions.
In the future the APIs could be used to support Pex CLI subcommands that
distinguish these two phases of creating a PEX allowing resolution on
one machine and building on another; thus adding a new way to handle
creation of multi-platform pexes without resorting to pre-built wheel
repositories.

Split Pex resolve API.

---

pex/environment.py
pex/vendor/__init__.py
tests/test_environment.py

PEX issue: https://github.com/pantsbuild/pex/issues/964
This PR updates `PEXEnvironment.can_add` to split the whole wheel filename in order to gather up the trailing three tags. The previous implementation was overly naive and failed when a wheel filename included a (valid) build tag.

Fix wheel filename parsing in PEXEnvironment.can_add

---

pex/environment.py
tests/test_environment.py

My previous PR (#965) unintentionally removed handling for invalid wheel names (e.g. `"foo.whl"` or `"foo-bar.whl"`). This PR restores the previous functionality, namely returning `False` for (a subset of) bad wheel filenames.
I made the conservative choice to only reject filenames with < 3 wheel components (matching the previous behavior), but there's a valid argument to made for rejecting wheels with < 5 components, per [PEP 427](https://www.python.org/dev/peps/pep-0427/#file-name-convention).
---
Previous implementation: https://github.com/pantsbuild/pex/blob/2f048d8df0dbcebdc24d2355bf58130baa35de0f/pex/environment.py#L221-L225

Restore handling for bad wheel filenames to `.can_add()`

---

pex/bin/pex.py
pex/network_configuration.py
pex/pip.py
pex/resolver.py
pex/variables.py
pex/vendor/__init__.py
pex/vendor/_vendored/pip/pip/_internal/cli/cmdoptions.py
pex/vendor/_vendored/pip/pip/_internal/cli/req_command.py
pex/vendor/_vendored/pip/pip/_internal/index/collector.py
pex/vendor/_vendored/pip/pip/_internal/network/session.py

Also add back the `--cache-ttl` option from Pex 1.x and plumb the header
needed to make it so.
Also remove long-ignored `PEX_HTTP_RETRIES` and `PEX_HTTP_TIMEOUT` env
var support.
Fixes #94
Fixes #803

Expose Pip network configuration.

---

.travis.yml
tox.ini

This works, but I can't explain why the prior did not. Moving on with
the fix though since real green is better than the current early exit
green due to not being able to find Python 3.8 and having our tox.ini
configured for `skip_missing_interpreters = True`. Patch that by adding
`--skip-missing-interpreters=false` to our tox invocations in CI.

Fix Tox not finding Python 3.8 on OSX.

---

pex/resolver.py

When running pex within a chroot environment, the symlinks generated by `pex/pex/resolver.py` use the absolute path within the chroot in the path for the symlinks' targets. These symlinks are invalid paths to any program that accesses the wheel cache outside of the chroot. (This was seen within a remote execution environment with Buildfarm.)
Switch to using relative paths for the symlinks.
Fixes https://github.com/pantsbuild/pex/issues/978.

use relative paths within wheel cache

---

pex/pex.py
pex/variables.py
tests/test_pex.py

If set, we add these path elements to PEX's runtime sys.path.
This allows code in the pex to interact with code outside the
pex (for example, running pytest in a pex on code outside it).

A PEX_EXTRA_SYS_PATH runtime variable.

---

pex/distribution_target.py
pex/interpreter.py
pex/pip.py
pex/resolver.py

When pip encounters an existing file during any of its file operations
it prompts for an action if `--exists-action` has not been set. Pex was
supplying a download directory to pip that was degenerate for
interpreters with the same abi and same major and minor versions (e.g.:
2.7.6 and 2.7.18). We ensure the download directory is unique per
interpreter and further configure the `--exists-action` to abort to get
fail fast behavior and smoke out regressions or any remaining issues in
this vein.
Fixes #983

Ensure pip download dir is uncontended.

---

pex/bin/pex.py
pex/platforms.py

This adds a prompt to use --platform explain as a hack to get more
information from a platform parse error. Also add examples to the parse
error message to cover OSX and PyPy covering the other major variants
we support.

Improve --platform help.

---

pex/bin/pex.py
pex/distribution_target.py
pex/environment.py
pex/interpreter.py
pex/pex_info.py
pex/platforms.py
pex/variables.py
tests/test_integration.py
tests/test_pex_binary.py

Introduce new APIs to get a PythonInterpreter's associated platforms
directly and use this to implement resolution of specified platforms to
local interpreters when possible if --resolve-local-platforms is
specified.
Fixes #996.

Add support for resolving --platform locally.

---

pex/bin/pex.py
tests/test_integration.py

Before:
```
1: python -m pex --disable-cache --interpreter-constraint=CPython>=3.6 cryptography -o t.pex
Mean        Std.Dev.    Min         Median      Max
real        7.541       0.258       7.283       7.378       7.967
user        21.989      0.609       20.890      21.887      23.020
sys         5.979       0.169       5.690       5.918       6.237
```
After:
```
1: python -m pex --disable-cache --use-first-matching-interpreter --interpreter-constraint=CPython>=3.6 cryptography -o t.pex
Mean        Std.Dev.    Min         Median      Max
real        6.217       0.478       5.820       6.118       7.592
user        11.233      0.349       10.593      11.292      11.751
sys         3.538       0.106       3.305       3.542       3.675
```
This is expected to be particularly useful for …

Add `--use-first-matching-interpreter`

---

pex/bin/pex.py
tests/test_integration.py

Restrict the runtime interpreter to match the buildtime interpreter
by the crude means of relying on the pythonX.Y shebang.

Fix --use-first-matching-interpreter at runtime.

---

pex/common.py
pex/third_party/__init__.py
pex/util.py
tests/test_common.py
tests/test_integration.py

Previously they did not which led to PEP-420 namespace packages not
working in `--zip-safe` context.
Fixes #1021

PEX zips now contain directory entries.

---

pex/interpreter.py
pex/interpreter_constraints.py
pex/jobs.py
pex/pex_bootstrapper.py
pex/resolver.py

Surface all broken interpreters and a link to known breaks and
workarounds tracked in #1027.

Improve UnsatisfiableInterpreterConstraintsError.

---

mypy.ini
pex/bin/pex.py
pex/common.py
pex/compatibility.py
pex/compiler.py
pex/interpreter.py
pex/pex_info.py
pex/testing.py
tests/test_bdist_pex.py
tests/test_common.py
tests/test_compatibility.py
tests/test_compiler.py
tests/test_executor.py
tests/test_finders.py
tests/test_inherits_path_option.py
tests/test_interpreter.py
tests/test_jobs.py
tests/test_pex_binary.py
tests/test_pex_bootstrapper.py
tests/test_pex_builder.py
tests/test_pex_info.py
tests/test_pex_warnings.py
tests/test_platform.py
tests/test_resolver.py
tests/test_third_party.py
tests/test_unified_install_cache.py
tests/test_util.py
tests/test_variables.py
tests/test_vendor.py

Now all tests have full coverage except for `test_environment.py`, `test_pex.py`, and `test_integration.py`, which are saved for a dedicated followup.
Why start with tests? These are the call-sites of much of our production code, and this will help to ensure that when we add types to our production code, the hints reflect reality. The tests also are "roots", which makes it easier to add hints to than adding hints to code with lots of dependees.
Python 2 lets you freely mix unicode and bytes :/ Pex uses this abundantly, in contrast to Pants's (awkward) use of `future` to ensure that Py2 always used the exact same type as Py3.
Originally, this PR added `from __future__ import unicode_literals`, but that was reverted to instead optimize for fewer code changes. PEX's Py2 support works well as …

Add type hints to most tests

---

pex/common.py
pex/testing.py
tests/test_environment.py
tests/test_integration.py
tests/test_pex.py
tests/test_util.py

Now that we have full type coverage for the tests, we'll get useful validation when adding hints to our source code that the hints line up.

Add type hints to the remaining tests

---

mypy.ini
pex/dist_metadata.py
pex/interpreter.py
pex/interpreter_constraints.py
pex/pex_warnings.py
pex/platforms.py
pex/testing.py
pex/variables.py
tests/test_variables.py

Unfortunately, so long as we require Python 2, we cannot use `namedtuple` robustly with MyPy because it does not support annotating the fields of a named tuple. So, we recreate namedtuple through our own conventional class. This can be fixed once we require Python 3 to run. See https://github.com/pantsbuild/pex/issues/1041.

Add type hints to variables.py and platforms.py

---

pex/common.py
pex/compiler.py
pex/interpreter.py
pex/testing.py
pex/tracer.py
pex/util.py
pex/variables.py
tests/test_finders.py
tests/test_integration.py
tests/test_util.py

Also clean up some prior type hints to use `cast`, type vars, and type aliases.

Add type hints to `util.py` and `tracer.py`

---

pex/interpreter.py
pex/typing.py
tests/test_interpreter.py

This adds support for a path filter to allow unification of Pex
buildtime and runtime interpreter discovery. The PythonInterpreter
public API family of `iter`, `iter_candidates` and `all` is
type-annotated and tests are added for `iter_candidates`. To support
proper annotation of iter_candidates helpers, `@overload` support is
added for Python 2.7.
Work towards #1043

Path filter for PythonInterpreter.iter_candidates.

---

pex/bin/pex.py
pex/resolver.py

@jsirois read my mind in https://github.com/pantsbuild/pex/issues/1033#issuecomment-699590960 after I asked why Pex couldn't resolve for an interpreter it doesn't have locally. This was in fact already possible, and he suggested a documentation fix to make it more clear. These changes make it clear that:
- `platform{,s}` takes precedence over `interpreter{,s}` when resolving wheels
- `interpreter{,s}` are used to seed `platform{,s}` if not provided
- matching `interpreter{,s}` must be provided for all `platform{,s}` if any distributions need to be built from source
Closes #1033.

slightly demystify the relationship between platforms and interpreters in the library API and CLI

---

pex/interpreter.py

Unfortunately, OSX framework Python interpreters have had launch schemes
that could lead to misreported `sys.executable`. We no longer trust
`sys.executable` when caching interpreters or reading them from the
cache.
Fixes #1009

Do not rely on `sys.executable` being accurate.

---

pex/bin/pex.py
pex/interpreter_constraints.py
pex/pex_bootstrapper.py
tests/test_pex_bootstrapper.py

Previously, `iter_compatible_interpreters` let its use of
`PythonIntepreter.iter_candidates` leak outside its direct control.
This allowed the heterogeneous iterator returned by `iter_candidates` to
end up in places that did not know about its heterogeneous nature.
Expand `iter_compatible_interpreters` to accept an optional
`valid_basenames` filter so that interpreter selection at Pex buildtime
and at PEX runtime can share the same code path and use this unification
to localize consumption of the heteogeneous iterator.
Fixes #1043.

Fix use of `iter_compatible_interpreters`.

---

pex/pip.py

Previously `--cert` did not propagate correctly through Pip. Work around
this by passing the option via environment variable.
Fixes #1058

Fix `--cert` for PEP-518 builds.

---

pex/pex_info.py
pex/pex_warnings.py
pex/pip.py
pex/tracer.py
pex/typing.py
pex/variables.py
tests/test_pex_builder.py
tests/test_variables.py

Re-structure `strip_defaults` to allow typing to reflect real usage and
simplify call sites.
Fixes #1059

Fix Variables typing.

---

pex/common.py
pex/environment.py
pex/interpreter.py
pex/pex_builder.py
pex/pip.py
pex/resolver.py
pex/third_party/__init__.py
pex/util.py
tests/test_common.py
tests/test_environment.py

Use this new mode to ensure directories Pex creates that contain Python
code are created exactly once so that the implicit Python bytecode
compilation process is not thwarted by racing directory creation.
Fixes #1051

Add atomic_directory exclusive mode.

---

pex/pip.py
pex/resolver.py

In order to work around https://github.com/pypa/pip/issues/5502 fully,
we extract a `PackageIndexConfiguration` class that handles arrangement
of Pip command line flags and enviornment variables to effect the most
hermetic means possible of conveying `--cert` and `--client-cert` to Pip
and its subprocesses.
Fixes #1058

Fix handling of `--cert` and `--client-cert`.

---

pex/interpreter.py
pex/testing.py
tests/test_integration.py
tests/test_interpreter.py

The prior fix for #1009 undid the fix in #860. Re-enable that fix
for any case that's clearly not in the context of a macOS Framework
Python build. Also add tests for pyenv shims to prevent further
regressions.

Honor `sys.executable` unless macOS Framework.

---

pex/bin/pex.py
tests/test_integration.py

This allows for explicit control of the temporary directory both Pex
and its subprocesses use.
Fixes #1067

Add a `--tmpdir` option to the Pex CLI.

---

pex/bin/pex.py
pex/environment.py
pex/inherit_path.py
pex/pex.py
pex/pex_info.py
pex/variables.py
tests/test_environment.py
tests/test_inherits_path_option.py
tests/test_pex.py

Factor out an enum-like class that encodes legacy bool behavior
centrally and use this to provide the same validation in
`--inherit-path` and PEX_INHERIT_PATH.
Fixes #921

Encapsulate `--inherit-path` handling.

---

pex/bin/pex.py
tests/test_integration.py

This was a misfeature added to support a Pants use case, which is implemented another way.
This never worked very robustly:
> To be clear though, there are many corners this will not work for including mismatching abi (python2.7m vs python2.7mu) when the PEX contains platform specific wheels, etc.
If a user only wants to resolve for one interpreter, they should use `--python` or a finer grained `--interpreter-constraints`.
We don't use a proper deprecation due to https://github.com/pantsbuild/pex/issues/584. We'll call attention to this in the release notes.

Remove `--use-first-matching-interpreter` misfeature

---

pex/bin/pex.py
tests/test_integration.py

Closes https://github.com/pantsbuild/pex/issues/1012.
Currently, PEX defaults to searching the $PATH when `--interpreter-constraint` and/or `--resolve-local-platforms` are used. (Otherwise, it uses the current interpreter or `--python`).
You can specify `PEX_PYTHON_PATH`, but this has several issues:
* Env vars should only be used for runtime, not build time. We break that separation here.
* This only works if `PEX_IGNORE_RCFILES` is not set to true. Pants must set this option, meaning Pants cannot leverage this mechanism.
* The behavior doesn't work as expected if running Pex as a Pex: https://github.com/pantsbuild/pex/issues/1075
Instead of further using `PEX_PYTHON_PATH`, we add a proper `--python-path` flag. In a followup, we can remove the `PEX_PYTHON_PATH` mechanism.

Add `--python-path` to change interpreter search paths when building a PEX

---

pex/util.py
tests/test_util.py

Previously `dir_hash` (and `pex_hash`) were able to observe in-flight
bytecode compilation which would lead to observe-delete-failedhash
sequencing.
Fixes #1051

Fix `dir_hash` vs. bytecode compilation races.

---

docs/rtd/requirements.txt

Otherwise rtd uses a really old version.

Pin sphinx requirements for doc generation.

---

pex/bin/pex.py
pex/interpreter.py
pex/pex_bootstrapper.py
tests/test_interpreter.py

Currently, our naive `min()` means that Pex will choose 3.6.3 instead of 3.6.8, for example. This is not ideal because the newer patch will have important bug fixes, and should still be backward compatible.
For macOS users, there's an added benefit of this PR that the problematic system Pythons usually use older patch versions. A user is likely to have installed a more modern patch with both Homebrew and Pyenv; this PR means that Pex will correctly prefer those over the broken system Python.
This does not solve https://github.com/pantsbuild/pex/issues/430; we will still always prefer the minimum major/minor version, i.e. `3.6.1` is preferred over `3.6.0`, and both are preferred over `3.7.*`.

Prefer more recent patch versions in interpreter discovery.

---

pex/interpreter.py
pex/pex_bootstrapper.py
tests/test_interpreter.py

Before, this unexpectedly fails:
```
$ PATH=/Library/Developer/CommandLineTools/usr/bin/python3 PEX_IGNORE_RCFILES=true /Users/eric/.pyenv/versions/3.8.5/bin/python ./pex --interpreter-constraint='CPython>=3.7' --python-path='/Users/eric/.pyenv/versions/3.8.5/bin/python' -- -c 'import sys; print(sys.executable)'
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/bin/python3.7
```
But this succeeds:
```
$ PATH=/Library/Developer/CommandLineTools/usr/bin/python3 PEX_IGNORE_RCFILES=true /Library/Developer/CommandLineTools/usr/bin/python3 ./pex --interpreter-constraint='CPython>=3.7' --python-path='/Users/eric/.pyenv/versions/3.8.5/bin/python' -- -c 'import sys; print(sys.executable)'
/Users/eric/.pyenv/versions/3.8.5/bin/python3.8
```
This issue is that we …

Fix `--pex-python` when it's the same as the current interpreter

---

pex/common.py
pex/util.py
pex/vendor/__init__.py

Fix runtime vendoring bytecode compilation races.

---

pex/pex.py
tests/test_pex.py

Since the lack of an explicit close is intended, we suppress the
warning.
Fixes #1101

Fix ResourceWarning for unclosed /dev/null.

---

pex/resolver.py
pex/testing.py
tests/test_integration.py
tests/test_resolver.py

Elide environment markers for arbitrary equality (distributions with
non-standard versions).
Fixes #940

Fix spurious `InstalledDistribution` env markers.

---

pex/resolver.py
tests/test_integration.py

Previously `Requires-Python` metadata was unconditionally mapped to
`python_version` environment marker clauses. This was incorrect for any
`Requires-Python` clauses that included version information beyond
`X.Y` and prevented activation of requirements in PEX files at runtime
in some cases. A previously failing test is added for the pandas case
that revealed this issue.
Fixes #1017

Fix `Requires-Python` environment marker mapping.

---

pex/pex_bootstrapper.py
tests/test_pex_bootstrapper.py

Previously, if the current interpreter was valid and contained in a
path directory entry, all sibling interpreters in that same directory
went undiscovered. A test is added that fails without the fix.
Fixes #1109

Fix `iter_compatible_interpreters` with `path`.

---

pex/variables.py

The work to fix #1059 in #1061 introduced DefaultedProperty but failed
to account for these when generating PEX_ environment variable help.

Fix `--help-variables` docs.

---

pex/requirements.py
tests/test_integration.py
tests/test_requirements.py

Previously, we did not handle the case where a local project directory
basename was not a well formed requirement project name. Pro-actively
parse the local project directory basename to separate out any
requirements parts for further parsing and add regression tests for
this.

Fix req parsing for local archives & projects.

---

pex/common.py
tests/test_common.py

An upcoming change to support creating virtualenvs from PEX files
requires this.

Add an `is_exe` helper.

---

pex/dist_metadata.py
tests/test_dist_metadata.py
tests/test_environment.py

This is needed to support #1020 and #1108.

Add a `requires_dists` function.

---

pex/interpreter.py
pex/interpreter_constraints.py
pex/pex_bootstrapper.py
tests/test_interpreter.py

Previously this always used `os.path.realpath` which follows symlinks
and breaks out of venvs created by Python 3. Although this is fine for
PEX use since it scrubs the `sys.path` anyhow, it will not be fine for
upcoming use when creating venvs from PEX files.

Fix `PythonInterpreter` binary normalization.

---

pex/bin/pex.py
pex/pex.py
pex/pex_builder.py
pex/pex_info.py
pex/tools/__init__.py
pex/tools/__main__.py
pex/tools/command.py
pex/tools/commands/__init__.py
pex/tools/commands/info.py
pex/tools/main.py
pex/variables.py
scripts/package.py
tests/test_pex_info.py

Add a new `--include-tools` option to include any pex.tools in generated
PEX files. These tools are activated by running PEX files with
PEX_TOOLS=1. The `Info` tool seeds the tool set and simply dumps the
effective PEX-INFO for the given PEX.
Work towards #962 and #1115

Add support for PEX runtime tools & an info tool.

---

pex/interpreter.py
tests/test_integration.py
tests/test_interpreter.py
tests/test_pex_bootstrapper.py

This fixes binary canonicalization to handle virtual environments
created with virtualenv instead of pyvenv. It also adds support for
resolving the base interpreter used to build a virtual environment.
The ability to resolve a virtual environment intepreter will be used to
fix #1031 where virtual environments created with
`--system-site-packages` leak those packages through as regular sys.path
entries otherwise undetectable by PEX.
Work towards #962 and #1115.

Improve `PythonInterpreter` venv support.

---

pex/interpreter_constraints.py
pex/pex_bootstrapper.py
pex/testing.py
tests/test_integration.py

Virtual environments created with --system-site-packages can break PEX
sys.path scrubbing. Avoid this class of environment leaks by breaking out
of venvs unless PEX_INHERIT_PATH has been requested.
A test is added that fails for virtualenv-16.7.10 without the fix.
Fixes #1031

Escape venvs unless PEX_INHERIT_PATH is requested.

---

pex/bin/pex.py
pex/interpreter.py
pex/pex.py
pex/tools/commands/__init__.py
pex/tools/commands/interpreter.py
pex/tools/main.py

The tool can be used to print information about the preferred
interpreter(s) for a PEX. This tool is now referenced as the way to
find out about `--platform` strings and `--interpreter-constraint`
strings.

Add an interpreter tool.

---

pex/environment.py
pex/pex.py
pex/tools/commands/README.venv.md
pex/tools/commands/__init__.py
pex/tools/commands/venv.py
pex/tools/commands/virtualenv.py
pex/tools/commands/virtualenv_16.7.10_py
scripts/embed_virtualenv.sh
tests/tools/commands/test_venv.py
tox.ini

Add a `venv` tool to create a virtual environment from a PEX file. The
virtual environment is seeded with just the PEX user code and
distributions applicable to the selected interpreter for the local
machine. The virtual environment does not have Pip installed by default
although that can be requested with `--pip`.
The virtual environment comes with a `__main__.py` at the root of the 
venv to emulate a loose pex that can be run with `python venv.dir` just
like a loose pex. This entry point supports all the behavior of the
original PEX file not related to interpreter selection, namely support
for PEX_SCRIPT, PEX_MODULE, PEX_INTERPRETER and PEX_EXTRA_SYS_PATH.
A sibling `pex` script is linked to `__main__.py` to provide the
maximum performance entrypoint that always avoids interpreter …

Add a venv tool.

---

pex/tools/commands/__init__.py
pex/tools/commands/digraph.py
pex/tools/commands/graph.py

By default this renders svg which is useful since it includes clickable
links to the PyPI page for each node when viewed in a modern browser.

Add a dependency graph tool.

---

pex/tools/commands/venv.py
tests/tools/commands/test_venv.py

This brings the venv pex script up to parity with PEX files.
Fixes #1136

Implement PEX_INTERPRETER special mode support.

---

pex/resolver.py

LegacyVersion is deprecated so we switch to doing our own exception
handling to deal with glob version matches.
Fixes #1150

Remove our reliance on packaging's LegacyVersion.

---

pex/bin/pex.py
pex/common.py
pex/environment.py
pex/interpreter.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pex_info.py
pex/testing.py
pex/tools/commands/graph.py
pex/tools/commands/venv.py
pex/tools/commands/virtualenv.py
pex/util.py
pex/variables.py
pex/venv_bin_path.py
tests/test_integration.py
tests/test_pex_binary.py
tests/test_pex_info.py
tests/test_unified_install_cache.py
tests/test_variables.py

The new --venv execution mode builds a PEX file that includes pex.tools
and extracts itself into a venv under PEX_ROOT upon 1st execution or any
execution that might select a diffrent interpreter than the default.
In order to speed up the local build and execute case, --seed mode is
added to seed the PEX_ROOT caches that will be used at runtime. This is
important for --venv mode since venv seeding depends on the selected
interpreter and one is already selected during the PEX file build
process.
Fixes #962
Fixes #1097
Fixes #1115

Support a --venv mode similar to --unzip mode.

---

tests/test_unified_install_cache.py

There is a small typo in tests/test_unified_install_cache.py.
Should read `original` rather than `orignal`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, orignal -> original

---

pex/dist_metadata.py
tests/test_dist_metadata.py

In addition to extracting this metadata from Distributions, retrofit support
for loading metadata from uninstalled wheels and sdists which will be needed
to fully support requirements parsing needs.
Work towards #899, #1020 and #1108.

Support project_name_and_version metadata.

---

pex/pip.py
tests/test_integration.py

Unfortunately, the useful information is sent to stdout which we suppress
since stdout is used to emit alot of other information that would be noise
for Pex users. Until https://github.com/pypa/pip/issues/9420 is resolved
we work around this by plucking the information out of a --log file.
Fixes #1159

Surface Pip dependency conflict information.

---

pex/bin/pex.py
pex/requirements.py
tests/test_integration.py
tests/test_requirements.py

This retrofits parse_requirement_file to accept either a file path or
an URL and fixes plumbing of the is_constraints marker for URL sources.
The Pex CLI support for -r and --constraints is now at parity with Pip
-r / -c.

Add support for -r / --constraints URL to the CLI.

---

pex/environment.py
pex/interpreter.py
pex/pex.py
tests/test_environment.py
tests/test_integration.py

This removes our dependency on pkg_resources Environment / WorkingSet in
favor of performing our own recursive resolve of runtime distributions
to activate using distribution metadata. This fixes an old test bug
noticed by Benjy but, more importanty, sets the stage to fix #899, #1020
and #1108 by equipping PEXEnvironment with the ability to resolve the
appropriate transitive set of distributions from a root set of
requirements instead of the current full set of transitive requirements
stored post-resolve in PexInfo.

PEXEnvironment recursive runtime resolve.

---

pex/requirements.py
pex/resolver.py
tests/test_integration.py
tests/test_requirements.py

In order to fix #899, we need to map local project requirements to built
wheels after the fact in order to learn the project name and version and
thus the full requirement needed for PexInfo metadata. In order to do
this with confidence, break up the ReqInfo type into three seperate
types to cover the three main parse cases.

Tighten requirements parsing.

---

pex/bin/pex.py
pex/environment.py
pex/requirements.py
pex/resolver.py
tests/test_environment.py
tests/test_integration.py
tests/test_resolver.py

Previously we recorded the post-resolve exact requirements of all
resolved distributions. This necessitated a good deal of work to recover
environment markers and still left out any top-level environment markers
specified in direct requirements / requirement files passed to Pex. Now
we record all requirements as we received them, only filling in project
name and version for local loose-source requirements in our resolve
post-processing. This saves time (~O(500ms) for medium to large PEX
builds) and fixes bugs.
Fixes #899

Record original requirements in PEX-INFO.

---

pex/distribution_target.py
pex/environment.py
pex/pex.py
pex/pip.py
pex/resolver.py
pex/testing.py
pex/tools/commands/venv.py
tests/test_environment.py

Instead of requiring a PythonIntepreter to resolve distributions in a
PEXEnvironment, a DistributionTarget is enough. This allows for
resolving distributions from a PEXEnvironment given only a Platform
which we need to support resolving from a `--pex-repository` for
foreign platforms in #1108.

PEXEnvironment for a DistributionTarget.

---

pex/bin/pex.py
pex/distribution_target.py
pex/environment.py
pex/resolver.py
pex/util.py
tests/test_resolver.py

Introduce a `--pex-repository` option to the Pex CLI to switch
requirement resolution from using index servers and find-links
repositories to using a local PEX file with pre-resolved requirements.
This can be useful when a number of projects share a consistent resolve
via a shared requirement file. You can resolve the full requirement file
into a requirements PEX and then later resolve just the portions needed
by each individual project from the fully resolved requirements PEX.
Fixes #1108

Support resolving from a PEX file repository.

---

pex/pip.py

Pex accepts this warning in order to implement the `--pex-repository`
feature. User's should not have to see the warning since they are just
along for the ride.

Suppress `pip debug` warning.

---

pex/bin/pex.py
pex/common.py
pex/pex_builder.py
tests/test_common.py
tests/test_pex_builder.py

This avoids copying dists from ~/.pex/installed_wheels to a PEXBuilder
tmpdir before finally zipping up the tmpdir. Instead, with just a single
symlink added to the PEXBuilder tmpdir for each dist, the zip is created
directly from the sources under ~/.pex/installed_wheels providing a
modest speed up when building large PEX files.

Use symlinks to add dists in the Pex CLI.

---

pex/resolver.py

Make it clear local projects can't be resolved from PEX repositories in
general. Previously you might take the error to mean the particular
local project was not resolvable from the particular PEX repository.

Improve PEX repository error for local projects.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.25 release.

---

pex/dist_metadata.py
pex/requirements.py
tests/test_requirements.py

Previously a file (not directory) in the CWD with the same name as the
project name of a requirement being resolved would lead to an error.
Modify the requirement parsing stress test to cause this error and fix
parsing so the test passes.
Fixes #1188

Requirement parsing handles local non-dist files.

---

pex/common.py
tests/test_common.py
tests/test_pex_builder.py

Previously, when a relative path was given to `Chroot.symlink`, the
underlying symlink would be created as relative. This led to issues when
the CWD changed between Chroot creation time and Chroot resolution time.
Fix `Chroot.symlink` to use absolute symlink paths.
Fixes #1192

Support relative paths in `Chroot.symlink`.

---

pex/resolver.py
tests/test_resolver.py

Previously environment markers were not considered when calculating
which resolved distributions satisfied direct requirements leading
to spurious AssertionErrors.
Fixes #1196

Fix resolve post-processing to use markers.

---

pex/pip.py

There was never a need to use pkg_resources.Environment to find our
vendored distributions for exposure to the Pip PEX.

Simplify construction of Pip PEX.

---

.github/workflows/release.yml
tox.ini

This leaves out both CHANGES transcription to the Github Release body
and an update of the RELEASE.rst to reflect this new infra until after
any kinks are worked out.

Automate most of a Pex release.

---

pex/compatibility.py
tests/test_environment.py
tests/test_integration.py
tests/test_pex.py
tests/test_pex_binary.py
tests/test_pex_builder.py
tests/test_resolver.py
tests/test_util.py

Save for two tests that exercise pex_warnings and Python 2.7 EOL
warnings.

Fix all test warnings.

---

pex/pex_builder.py
tests/test_integration.py

Previously the PexInfo metadata itself was left out of the calculation.
This could lead to `unzip` and `venv` mode collisions.
Add a previously failing test and fix.
Fixes #1218

Make `PexInfo.pex_hash` calculation more robust. 

---

pex/interpreter.py
pex/tools/commands/virtualenv.py
tests/test_integration.py
tests/test_interpreter.py

The PyPy3 `venv` module doesn't work for Pex `--venv` mode so we use
virtualenv instead.
Addresses most of #1210.

Fix PyPy3 `--venv` mode.

---

.github/workflows/release.yml

This adds support for manually triggering the workflow and fixes the
github-release job to perform a full clone so git describe works.

Fixup the Release workflow.

---

pex/pex_builder.py
pex/pex_info.py
pex/variables.py
tests/test_integration.py

Virtual environments are now rebuilt when PEX_PATH is mutated.
Fixes #1225

Fix --venv mode to respect PEX_PATH.

---

mypy.ini
pex/compatibility.py
pex/orderedset.py
pex/requirements.py
scripts/typecheck.sh
tests/tools/commands/test_venv.py
tox.ini

This upgrades MyPy to latest and fixes types. It also switches to
passing MyPy a complete list of files to check to avoid syntax errors
encountered parsing (forthcoming) vendored code which happen earlier
than our previous MyPy config could handle:
```ini
[mypy-pex.vendor._vendored.*]
ignore_errors = True
```

Upgrade MyPy to 0.800.

---

pex/tools/commands/venv.py
tests/tools/commands/test_venv.py

Add a test that passes for multiprocessing fork mode but fails for both
spawn and forkserver modes and fix the pex script to gaurd against non
`__name__ == '__main__'` mode to fix.
Fixes #1236

Fix venv pex script for use with multiprocessing.

---

pex/tools/commands/venv.py
tests/tools/commands/test_venv.py

Ensure PEX file contents are materialized in venvs as durable files.
Previously, distributions were handled correctly but PEX sources and
resources were not. A test is added that exercised the bug but is now
fixed.
Fixes #1239

Ensure PEX files aren't symlinked in venv.

---

.github/actions/run-tox/action.yml
.github/workflows/ci.yml
pex/testing.py
tox.ini

Previously these lived in the root of each pantsbuild/pex clone. Beyond
being inefficient, this caused problems with pip wheel when building
Pex via `tox -epackage`. Introduce a new `~/.pex_dev` cache as the
default but allow this to be controlled with `_PEX_TEST_PYENV_ROOT`.
Setup CI to configure `_PEX_TEST_PYENV_ROOT` and have it point to the
prior standard of `.pyenv_test` which works well for CI caching needs.

Move the pyenv interpreter test cache.

---

pex/interpreter.py
pex/jobs.py
pex/testing.py
tests/test_interpreter.py

Previously, running Pex in a directory with a different version of Pex
installed could lead to interpreter identification failures. Plug this
isolation leak by adding a failing test and fixing it.
Fixes #1231

Harden Pex interpreter identification.

---

pex/bin/pex.py
pex/pex_bootstrapper.py
pex/pex_info.py
pex/tools/commands/venv.py
pex/tools/commands/virtualenv.py
tests/tools/commands/test_venv.py

Add support for creating venvs using copies instead of symlinks.
Fixes #1230

Support venvs that can outlive their base python.

---

pex/pex_bootstrapper.py
tests/test_integration.py

When PEX bootstrap involved finding an interpreter, the
`--runtime-pex-root` was not propagated and interpreter identification
files would leak into the default `PEX_ROOT`.
Add a failing test that is fixed by proper PEX_ROOT propagation during
PEX bootstrapping.

Fix `--runtime-pex-root` leak in pex bootstrap.

---

pex/tools/commands/venv.py
tests/tools/commands/test_venv.py

This is useful when using Pex to install a system wide application to a
location where not all users will have permission to create bytecode
files.

Support pre-compiling a venv.

---

pex/third_party/__init__.py
pex/util.py
tests/test_integration.py

Previously isolation was only correct for Pex when it was loaded from a
distribution installed loose on a filesystem. Now isolation works when
Pex is loaded from a PEX zipfile as well.
Fixes #1232

Fix Pex isolation.

---

pex/pex_bootstrapper.py
pex/tools/commands/venv.py
tests/test_integration.py

The default path length to a `--venv` mode PEX python used in shebangs
for the venv `pex` script and venv console scripts is 102 characters
starting from the PEX_ROOT. Add to that 2 characters for '#!' and 4 for
the trailing ' -sE' we add and that leaves just 20 characters for the
path to the PEX_ROOT (e.g.: /home/jane/.pex) before these scripts start
failing on machines where the shebang length limit is 128 bytes, which
is not uncommon amongst Linux distributions.
Fix this for forseeable cases by keeping the existing cache structure,
which has a primary key path component of the pex hash which is cheap to
compute (pre-computed), convenient for debugging and ~guaranteed unique,
and introducing a "jump table" of venv dir symlinks in
PEX_ROOT/venvs/short. This jump table is computed once at …

Guard against too long `--venv` mode shebangs.

---

pex/tools/commands/virtualenv.py

Previously the number of newlines was doubled. Although this
caused no functional problems, it was a distraction.

Fix venv script shebang rewriting.

---

pex/common.py
pex/dist_metadata.py
pex/pip.py
tests/test_integration.py

Two sources of non-reproducibility remained:
1. When zipping a PEX file, symlinked directory walks were not sorted.
2. When installing wheels in chroots, Pip direct_url.json retained a
system-specific path that varied as PEX_ROOT varied.
The first is fixed with an explicit sort and the second is fixed by
simply deleting problematic direct_url.json files post-install.
Concludes the #1249 audit for PEX files.

Fix PEX file reproducibility.

---

pex/dist_metadata.py
tests/test_dist_metadata.py
tests/test_integration.py

We now warn when encountering legacy Requires metadata but otherwise
ignore it in line with the PyPA tools.
Fixes #1201

Fix Requires metadata handling.

---

pex/environment.py
pex/pex.py
pex/pex_builder.py
pex/pex_info.py
pex/resolver.py
pex/testing.py
pex/tools/commands/graph.py
pex/tools/commands/repository.py
pex/tools/commands/venv.py
tests/test_integration.py
tests/test_pex_builder.py

Include the distributions found in any PEXes present on the PEX_PATH in
the search for console scripts at PEX build time.
Fixes #1257

Support console scripts found in the PEX_PATH.

---

pex/bootstrap.py

Although there is currently no identified way this can happen, this fix
is known to work for one victim of #1272.
Fixes #1272

Guard against concurrent re-imports.

---

pex/pex.py
pex/testing.py
pex/tools/commands/venv.py
tests/test_integration.py
tests/test_pex.py

Previously we did not invoke module entrypoints identically to Python
which could lead to unexpected errors using the pickle module.
Now we match Python for all cases except a PEX in zipapp mode with a
module entrypoint. This is a case that is also not handled by Python
itself since its zipapp module requires a function entrypoint; ie
mod:func.
Fixes #1018

Fix module entrypoints.

---

pex/bin/pex.py
tests/test_pex_binary.py

Allow command line arguments to be specified in a file which is passed
on the command line with an @ symbol before the filename.
Add a corresponding tests for this behavior which verifies that two
requirements files can be passed in this manner.
closes #1271

allow cli arguments to be specified in a file

---

pex/bin/pex.py
pex/common.py
pex/environment.py
pex/interpreter.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pip.py
pex/platforms.py
pex/resolver.py
pex/testing.py
pex/third_party/__init__.py
pex/util.py
tests/test_common.py

It now always yields the associated `AtomicDirectory` object to allow
callers complete access to the atomic directory state.
Work towards #1276.

Re-structure `atomic_directory`.

---

pex/pex_bootstrapper.py
pex/tools/commands/virtualenv.py
tests/test_pex_bootstrapper.py

Previously the `python-config` and various activation scripts had bad
paths embedded that prevented proper operation.
Fixes #1276

Fix auto-created `--venv` core scripts.

---

pex/tools/commands/venv.py

Use the same environment variable trick used by pex_bootstrapper to
ensure we never enter aninifinite re-exec loop. Also check more valid
venv python path variants by resolving symlinks in the parent
directories of the known valid pythons.
Fixes #1285

Ensure venv pex does not enter a re-exec loop.

---

pex/environment.py
tests/test_environment.py

When a resolve failed at the stage of determining roots it left alot
of context on the floor. Add that context in the error message when
available.

Improve resolve error information.

---

.github/workflows/ci.yml
pex/__init__.py
scripts/package.py
tox.ini

Flit parsing of `pex/__init__.py` stopped working with our
fully-qualifed `pex.version` import. Switch the import to a relative
import and beef up CI with a check that creating distributions works.

Fix Pex dist publishing.

---

.github/actions/run-tox/action.yml
pex/interpreter.py
pex/pex.py
pex/pip.py
pex/testing.py
tests/test_integration.py
tox.ini

Some macOS system interpreters mis-report their platform for the
purposes of wheel generation and consumption. Ensure the all macOS
interpreters report a proper platform with the major and minor version
components of the mac release via a sysconfig backdoor present in
CPython 2.7 through 3.9.
Add a previously failing test that is fixed by this change.
Fixes #1294

Fix wheel building for certain macOS system interpreters.

---

pex/common.py
pex/pex_builder.py
tests/test_common.py

Previously building a PEX zip could observe in-flight bytecode
compilation and crash in an observe and load race.
Fixes #1297

Fix bytecode compilation race in PEXBuilder.build.

---

pex/bin/pex.py
tests/test_integration.py

This enables seeding and finding out all pertinent information about
the seed atomically. Previously, seed users like Pants would need to
concoct fragile or unsafe ways to determine the PEX_ROOT used by a
seeded PEX.

Add support for `--seed verbose`.

---

pex/bin/pex.py
pex/tools/main.py
tests/test_packaging.py

Add uniform `-V` / `--version` support and ensure pex-tools displays
argument defaults.

Spruce up `pex` and `pex-tools` CLIs.

---

pex/environment.py
pex/pep_503.py
pex/resolver.py
tests/test_integration.py

Previously the keys used to lookup requirements were not PEP-503
conformant and could lead to different results than resolves via Pip
which is PEP-503 conformant.
Fixes #1302

Fix --pex-repository requirement canonicalization.

---

.github/workflows/release.yml

Eric noticed both the actions/create-release and
actions/upload-release-asset GitHub repositories had been archived. This
converts our two-step create and upload into one step using the
reccomendd replacement action.

Migrate to softprops/action-gh-release.

---

pex/third_party/__init__.py

Previously, when Pex isolated itself it could observe in-flight bytecode
compilation temporary files and fail in an observe / copy race with temp
file creation / deletion.
Fixes #1303

Fix Pex isolation to avoid temporary pyc files.

---

pex/environment.py
pex/pep_503.py
pex/resolver.py
tests/test_integration.py

Previously direct requirements with `.` in the name would fail to record
as direct requirements for resolves handled via Pip.
Fixes #1311

Fix PEX direct requirements metadata.

---

.github/workflows/release.yml

The `fail_on_unmatched_files` parameter is documented at
https://github.com/softprops/action-gh-release#inputs, but GitHub
actions emits the following warning:
```
Unexpected input(s) fail_on_unmatched_files, valid inputs are
[body, body_path, name, tag_name, draft, prerelease, files]
```

Remove unused fail_on_unmatched_files parameter.

---

pex/common.py

Previously PEX processes could fail spuriously due to tmpdir tear down.
Fixes #1321

Ignore errors removing tmpdirs on exit.

---

pex/common.py
pex/interpreter.py
pex/pyenv.py
pex/testing.py
tests/test_interpreter.py

Previously shims were improperly cached without regard to their
activation status. Now a dedicated Pyenv class is used to test if an
interpreter binary is a pyenv shim, and, if so, resolve it to its
activated version if any. This fixes cache keying and also improves
bulk interpreter identification by allowing de-duping active shims and
skipping inactive shims.
An existing test is updated and expanded to test for this as well as
verifying the pyenv version configuration hierarchy of methods.
Fixes #1324

Fix pyenv shim identification.

---

pex/pex.py
pex/pex_builder.py
pex/pex_info.py
pex/pip.py
pex/resolver.py
pex/testing.py
pex/tools/commands/venv.py
tests/test_integration.py

Switch to running Pip from a venv so that its sys.executable is
naturally isolated. This leads to properly isolated subprocesses
being spawned by Pip itself.
Fixes #1336

Better isolate Pip.

---

pex/interpreter.py

Previously it was assumed the MACOSX_DEPLOYMENT_TARGET sysconfig var
was always a string and that has proven to be false.
Fixes #1337

Fix MACOSX_DEPLOYMENT_TARGET handling.

---

tests/test_integration.py

The latest release breaks `test_entry_point_targeting`.

Pin `autopep8` in integration test.

---

pex/common.py
pex/interpreter.py
pex/pex_builder.py
pex/tools/commands/graph.py
pex/tools/commands/interpreter.py
tests/tools/commands/test_interpreter_command.py

Convert `-v` from a boolean to a counter and display more information
for `-vv` (tags) and` -vvv` (environment markers and venv affiliation).
This should be useful for debugging various issues in the field.

Support more verbose output for interpreter info.

---

pex/third_party/__init__.py
pex/vendor/__init__.py
tests/test_pip.py
tests/test_third_party.py

Previously we'd see:
```
rm -rf ~/.pex
$ pex pex -cpex -opex.pex
/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/tools/commands/venv.py:141: PEXWarning: Encountered collision building venv at /home/jsirois/.pex/venvs/short/4bd8ddd4 from /home/jsirois/.pex/pip.pex/46820cb5af0dcf9295a4e7f30184cc0e9fa063dc:
1. /home/jsirois/.pex/venvs/7fbdc9731d96d42f0de338b2dfbc6bbed1c938e7/832e95f85413646e8b7b056ab4e60414f83d7397.01034f69a38943809913ffdfd28dd5bf/lib/python3.9/site-packages/constraints.txt was provided by:
/home/jsirois/.pex/pip.pex/46820cb5af0dcf9295a4e7f30184cc0e9fa063dc/.deps/setuptools/constraints.txt
/home/jsirois/.pex/pip.pex/46820cb5af0dcf9295a4e7f30184cc0e9fa063dc/.deps/wheel/constraints.txt
pex_warnings.warn(message)
```

Fix Pex emitting warnings about its Pip PEX venv.

---

pex/bin/pex.py
pex/pex.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pex_info.py
pex/variables.py
tests/test_execution_mode.py
tests/tools/commands/test_interpreter_command.py

Previously you could not ask a `--venv` PEX to run in unzip mode. This
regularizes all PEX files so that they can be asked to operate in unzip
mode or venv mode whenever possible (venv mode requires the PEX was
built with `--include-tools` or `--venv`).
Work towards #1343.

Fix execution modes.

---

pex/tools/commands/venv.py
tests/tools/commands/test_venv.py

Previously these were silently ignored which was confusing at best.
Fixes #1343

Warn for PEX env vars unsupported by venv.

---

pex/commands/bdist_pex.py

Always print out the pex command output regardless of failure or success.
Fixes #1356

Do not suppress pex output in bidst_pex

---

pex/distribution_target.py
pex/interpreter.py
pex/pex_bootstrapper.py
pex/pip.py
tests/test_distribution_target.py
tests/test_pip.py

Previously, if a `--platform` resolve was being executed with an
interpreter that matched the platform, a regular full-featured
interpreter resolve was performed. This prevented, for example,
resolving using a CPython 3.8 interpreter on a manylinux2014 capable
host for deployment to a host that is only manylinux2010 capable. The
`--resolve-local-platforms` option exists to force this sort of
fallback to a full-featured interpreter resolve when that is desired.
Fixes #1355

Allow --platform resolves for current interpreter.

---

pex/bin/pex.py
tests/test_pex_binary.py

Previously this could not be used since the `--manylinux` option always
expected one argument.

Fix `--no-manylinux`.

---

pex/distribution_target.py
pex/pip.py
pex/platforms.py
pex/testing.py
pex/tools/commands/venv.py
tests/test_pip.py
tests/test_platform.py

Previously we relied on Pip, but it turns out Pip does not correctly
handle environment markers for `--platform` + `--implementation` +
`--python-version` + `--abi` (aka "foreign") resolves. Instead of
waiting on resolution of https://github.com/pypa/pip/issues/10050, patch
Pip's vendored copy of `packaging` to see a default environment that
corresponds to what we know about the foreign platform. It turns out
what we know covers the most commonly used environment markers making
this workaround both safe and useful in practice.
Fixes #1366

Fix `--platform` resolve handling of env markers.

---

.github/workflows/ci.yml
pex/testing.py
tests/test_environment.py
tests/test_integration.py
tests/test_interpreter.py
tests/test_pex.py
tests/test_pex_bootstrapper.py
tests/test_pip.py
tests/test_resolver.py
tests/tools/commands/test_interpreter_command.py
tests/tools/commands/test_repository.py
tests/tools/commands/test_venv.py

The older Python 3 interpreters are becoming problematic to install
and run. Move the 3.5 and 3.6 versions to 3.7 and 3.8 latest
respectively.

Modernize test pyenv interpreters.

---

.github/workflows/ci.yml
pex/testing.py
tests/test_integration.py

This upgrades to https://github.com/pantsbuild/actions/pull/2 which sets
`LD_LIBRARY_PATH` to include exposed Pythons lib dirs under linux. It
also discontinues using `--enable-shared` to build pyenv pythons under
linux.
Fixes #1391

Fix flaky Linux Pythons in CI.

---

pex/commands/bdist_pex.py
tests/test_bdist_pex.py

--bdist-all is broken and only creates the first entry in console_scripts.
This commit fixes this issue and adds a couple of regression tests.

Fix --bdist-all handling multiple console_scripts

---

pex/compatibility.py
pex/fetcher.py
pex/requirements.py
pex/resolver.py
tests/test_integration.py
tests/test_requirements.py

Lock file generation will need to download and hash dists when their
hashes are not presented in PEP 503 link fragments and we'll also need
to download dists directly if we optimize the resolving from a lock file
case when the lock file contains urls ala PEP-665.

Extract URLFetcher for reuse with lock files.

---

README.rst

As a new user to PEX, this example is _really_ hard to parse and figure out what it does, because everything is named `pex`:
```bash
$ pex pex -c pex -o pex.pex
```
This PR just renames each part of that command to be explicit about what it's specifying:
```bash
$ pex pex -c pex_entry -o pex-executable.pex
```
I also added subsections with titles to the examples section for quick reference, and added an example of a `console_scripts` entry point in `setup.py` and a link to the Python packaging documentation to make it even easier for other users to grok the example and get started using pex immediately, instead of having to delve deeper into the Python packaging rabbithole.

Improve examples and add example subsection titles

---

pex/common.py
pex/testing.py
pex/tools/commands/repository.py
tests/test_integration.py
tests/tools/commands/test_repository.py

Wheels are now extracted with a deterministic timestamp by default but
the same option that the main Pex CLI has is added to control this.
Fixes #1408

Support deterministic repository extract tool.

---

pex/pex_info.py
pex/pip.py
pex/tools/commands/virtualenv.py
tests/test_integration.py

This fixes installed wheel chroots by re-writing Python script shebangs
to use the standard `#!python` placeholder which removes a
system-specific path from the installed wheel chroots shipped in PEX
files; leading to broader circumstances under which a PEX build is
reproducible. A set of failing test permutations are added to the
`test_reproducible_*` integration tests which this un-reification fixes.
Fixes #1407.

Un-reify installed wheel script shebangs.

---

pex/common.py
pex/finders.py
pex/pex.py
pex/pip.py
pex/tools/commands/venv.py
tests/test_common.py
tests/test_finders.py
tests/test_integration.py

It turns out some distributuions ship native executables using
distribution "scripts" (like py-spy), and these caused script re-writing
and execution to fail. Adds a failing integration test using py-spy that
this change fixes.
Follow-up on #1381.

Don't attempt to parse binary scripts.

---

pex/requirements.py
tests/test_requirements.py
tests/test_resolver.py

Add failing tests for an url with environment marker appended that work
under Pip and previously failed under Pex.
Fixes #1415

Fix Pip proprietary URL env marker handling.

---

pex/bin/pex.py
pex/pip.py
pex/resolver.py
tests/test_bdist_pex.py
tests/test_environment.py
tests/test_pex.py
tests/test_resolver.py

Kill ~unused resolve and rename resolve_multi to resolve.
Eliminate ResolvedDistribution alias in favor of InstalledDistribution
which better reflects the shap of the distribution (not a wheel, but an
installed wheel). Fix test-use fallout.
Closes #969

Clean up resolver internal APIs.

---

pex/compatibility.py
pex/pip.py
pex/resolver.py

Two fixes:
1. Avoid warnings about universal newlines.
These flood the end of the unit test log for all unit test environments
except py27 and pypy2 as it stands.
2. Fixup an errant import of collections.Sequence.

Cleanup test warnings.

---

tests/integration/test_issue_729.py

These started failing due to a google-crc32c release that changed the
build system for its native extension:
https://github.com/googleapis/python-crc32c/issues/83

Fix PyPy integration tests in CI.

---

pex/interpreter.py
pex/jobs.py
tests/test_bdist_pex.py
tests/test_jobs.py

This allows collecting results from a Job's side-effects and will be used to
convert resolve information from Pip verbose logs into lock file data.

Add `SpawnedJob.and_then` API.

---

pex/bin/pex.py
pex/common.py
pex/environment.py
pex/pex.py
pex/pex_builder.py
pex/spread.py
pex/tools/commands/venv.py
pex/util.py
tests/integration/test_integration.py
tests/integration/test_spread.py
tests/test_execution_mode.py

Beyond the top level `pex` and `__main__.py` files, the layout is an
implementation detail, but the current structure sheds some light on the
cache-friendly characteristics:
Given loose sources:
```
$ cat src/main.py
from pex.version import __version__; print(__version__)
```
A spread layout PEX looks like:
```
$ python -mpex pex -Dsrc -emain -opex.spread.venv --spread \
--seed verbose --venv prepend | jq .
{
"pex_root": "/home/jsirois/.pex",
"python": "/usr/bin/python3.9",
"pex": "/home/jsirois/.pex/venvs/d2f743b9c1ebb156f794419c01b3422653cbdb61/2d1d404c3de23b1810386195be7410700b1feb14/pex"
}
$ tree -a pex.spread.venv
pex.spread.venv
├── .bootstrap
├── .deps
│   └── pex-2.1.46-py2.py3-none-any.whl
├── __main__.py -> src/__main__.py
├── pex -> __main__.py
├── PEX-SPREAD-INFO
└── src
├── …
```

Introduce the spread app layout.

---

pex/bin/pex.py
pex/dist_metadata.py
pex/locked_resolve.py
pex/pip.py
pex/resolver.py
tests/integration/test_locked_resolve.py
tests/test_bdist_pex.py
tests/test_environment.py
tests/test_pex.py
tests/test_resolver.py

For now this data is only used in test_locked_resolve, but it forms the
basis for adding lock generation support to Pex.
This is the core of the work for #1401. The remaining work is wiring a
CLI option to generate a lock file (needs to be able to store multiple
platform specific locks since a single resolve can generate many) and
consume the lock file.

Enrich resolve and download with lock data.

---

pex/pex_builder.py
tests/test_pex_builder.py

Previously, files in the spread could be symlinks pointing out of the
spread directory into the PEXBuilder chroot. This would lead to dangling
links when the PEXBuilder chroot was garbage collected.
Also, previously, the cached bootstrap zip and installed wheel chroot
zips created by PEXBuilder did not honor the PEX_ROOT when set via env
var.
Add previously failing tests for both of these leaks.

Fix two leaks in spread mode PEXes.

---

pex/locked_resolve.py
pex/pip.py
tests/integration/test_locked_resolve.py

This makes way for cross-platform as a style to be added later but
a CLI option to be plumbed now.

LockConfiguration strict: bool -> style: enum.

---

pex/pex_info.py

The original `$PEX_ROOT/code/<code_hash>` cache scheme was broken since
the `<code_hash>` was calculated just using user code but the contents
of the cache included Pex's `__main__.py` and `PEX-INFO` files. The
latter was luckily never loaded by the Pex runtime to figure out how to
run and so the bug never surfaced.
With the introduction of the zipapp and packed runtime layout support,
these bad cache entries are now used and the `PEX-INFO` is read. This
means, for the case of PEXes with no user code that were also
`--not-zip-safe`, all such PEXes share the `PEX-INFO` of the 1st such
PEX executed in a given `$PEX_ROOT`. This leads to unexpected
dependencies and crashes when executing any such PEX other than the
seeding PEX.
Fix this by simply re-naming the `code/` cache dir root to …

Avoid re-using old `~/.pex/code/` caches.

---

pex/common.py
pex/layout.py
tests/integration/test_issue_1447.py
tests/test_common.py

Previously it was required that the zipapp be executable. In practice
this is not required since a zippapp can be executed by python instead
of being executed directly.
Fixes #1447

Fix zipapp layout identification.

---

tests/integration/test_integration.py
tests/integration/test_issue_729.py

The 3.18.0 release brought a new py2.py3 wheel that has Python 3 syntax
code in it; so avoid this release in tests.
See: https://github.com/protocolbuffers/protobuf/issues/8984

Pin protobuf in tests below 3.18.0.

---

pex/orderedset.py
pex/typing.py

The prior implementation of `Generic` at runtime did not allow for this
and upcoming work on Pex CLI command infrastructure will want to do
this.
This new formulation needs a custom metaclass and that causes a problem
for `OrderedSet` since it already has an (indirect) custom metaclass of
ABCMeta via MutableSet. Re-work the typing there to accomodate.

Support `class Sub(Base[Concrete]): pass`.

---

pex/tools/command.py
pex/tools/commands/__init__.py
pex/tools/commands/graph.py
pex/tools/commands/info.py
pex/tools/commands/interpreter.py
pex/tools/commands/repository.py
pex/tools/commands/venv.py
pex/tools/main.py
tests/test_packaging.py

This will allow almost all of its machinery to be re-used for commands
that do not necessarily operate on a built PEX and using a different
`__main__` than `PEX_TOOLS`.

Refactor `PEX_TOOLS` `Command` infrastructure.

---

pex/bin/pex.py
pex/interpreter.py
pex/pex_bootstrapper.py
pex/resolve/requirement_configuration.py
pex/resolve/requirement_options.py
pex/resolve/resolve_configuration.py
pex/resolve/resolve_options.py
pex/resolve/target_configuration.py
pex/resolve/target_options.py
pex/resolver.py
tests/resolve/conftest.py
tests/resolve/test_resolver_options.py
tests/resolve/test_target_configuration.py
tests/resolve/test_target_options.py
tests/test_pex_binary.py
tests/test_resolver.py

This was started in #1455, but many options and substantial target
configuration logic remained tied to `pex.bin.pex`. Lift all options
and configuration logic up to the `pex.resolve` package where the
`pex3` CLI will be able to share the implementation and add test
coverage.

Finish extracting resolve configuration.

---

pex/pex_builder.py
pex/resolve/testing.py
tests/integration/test_locked_resolve.py
tests/test_pex_builder.py

These will be needed for `pex3 lock {create,export}` testing.
Also address some PEX `.bootstrap/` sloppiness and elide testing support
files that live in the production tree only for importability by many
tests.
Work towards #1401 and #1414.

Extract `LockedResolve` test helpers.

---

pex/common.py
tests/test_common.py

This will be used for error messages when introducing sortability to
`Enum` and in lock file parsing.
Work towards #1401 and #1414.

Introduce a `qualified_name` utility.

---

pex/bin/pex.py
pex/common.py
pex/enum.py
pex/inherit_path.py
pex/layout.py
pex/pex_builder.py
pex/resolve/locked_resolve.py
pex/resolve/resolver_configuration.py
pex/venv_bin_path.py
tests/test_common.py
tests/test_enum.py
tests/test_interpreter.py
tests/test_pex.py
tests/test_util.py
tox.ini

Upcoming lock file work will benefit from this. Instead of just sorting
by the string value of an `Enum.Value`, introduce an ordinal to sort by
and take the opportunity to dry up the values method.
Work towards #1401 and #1414.

Make Enums sortable.

---

pex/environment.py
pex/resolver.py

Previously, the run-time `ResolveError` of `PEXEnvironment` was
confusingly re-exported from `pex.resolver`; so it read like a
build-time error. Introduce a dedicated `pex.resolver.ResolveError`
base exception type for build-time resolve errors.
Work towards #1412.

Differentiate resolve error types.

---

pex/cli/commands/lock.py
pex/cli/commands/lockfile/__init__.py

The `pex3 lock update` command will re-use this. Also factor out bits
of lock command setup for re-use by the forthcoming update command.
Work towards #1412.

Factor up `pex.cli.commands.lockfile.create`.

---

pex/compatibility.py
pex/pip.py
pex/tools/commands/virtualenv.py
tests/integration/test_issue_1479.py

Previously, under PyPy3, Python 3.5 and Python 3.6 Pex would error
attempting to re-write script shebangs for scripts containing non-ascii
characters when the default encoding did not accept those characters.
Work around this by treating scripts as binary.
Fixes #1479

Fix non-ascii script shebang re-writing.

---

pex/vendor/__main__.py

Ever since #1106 these were not being used.

Fix vendoring constraints.

---

docs/recipes.rst
pex/pex_builder.py
pex/tools/commands/venv.py
tests/test_pex_builder.py

This is now always exposed to Pex applications so they can uniformly
detect that they are running from a PEX vs. from a virtual environment
or similar.
Closes #1485

Introduce the `PEX` env var.

---

pex/bin/pex.py
pex/pex_bootstrapper.py
pex/testing.py
pex/tools/commands/repository.py
pex/tools/commands/venv.py
pex/tools/commands/virtualenv.py
pex/variables.py
tests/conftest.py
tests/integration/__init__.py
tests/integration/conftest.py
tests/integration/test_executuon_mode_venv.py
tests/integration/test_variables.py
tests/resolve/__init__.py
tests/test_bdist_pex.py
tests/tools/__init__.py
tests/tools/commands/__init__.py
tests/tools/commands/test_venv.py

The `PEX_TOOLS` `venv` tool gains a `--prompt` option and the underlying
infrastructure that supports this is used to give automatically created
`--venv`s in the `PEX_ROOT` human readable names pointing back to the
original PEX name when possible.

Add support for setting custom venv prompts.

---

pex/interpreter.py
pex/jobs.py
tests/test_interpreter.py

Instead of assuming an interpreter that exits 0 is valid, force the
purported interpreter to execute some code that outputs a file to
both prove it's a binary that can execute Python code and identify
itself.
Fixes #1494

Guard against fake interpreters.

---

pex/pex_bootstrapper.py
pex/tools/commands/venv.py
tests/integration/conftest.py
tests/integration/test_pex_bootstrapper.py

Previously this was non-atomic which would lead to artificial short link
creation collisions for venvs that consistently failed to populate.
Fixes #1504

Fix `--venv` mode short link creation.

---

pex/commands/command.py
tests/commands/test_command.py
tests/test_packaging.py

These are needed to even bootstrap Main properly. If a subcommand
registers options differently, and that subcommand is selected, its
registration will naturally win anyhow.
Fixes #1510

Always register global options.

---

tox.ini

The 8.11.0 release today uses f-strings and old pytest floats on this
dep.

Fix more-itertools breaking 2.7 & 3.5.

---

docs/recipes.rst
pex/tools/commands/venv.py
tests/tools/commands/test_venv.py

This is especially useful for installing a PEX in a container image.

Add venv `--remove {pex,all}` option.

---

pex/compatibility.py
pex/pex_bootstrapper.py
pex/tools/commands/venv.py
tests/integration/conftest.py
tests/integration/test_pex_bootstrapper.py

Previously `--venv` mode auto-venvs were constructed just like PEX_TOOLS
venvs - using hard links (or copies if needed). Although this is
required for robust PEX_TOOLS venvs that don't collapse when you delete
the PEX_ROOT, it is not required for `--venv` mode auto-venvs which are
themselves stored in the PEX_ROOT. Now we symlink all `--venv` mode
auto-venv 3rdparty distributions to save a minor amount of space over
hard linking individual `.py` files, but a significant amount of space
in the shared `.pyc` files generated when the venv is later executed in
the case where many venvs share 3rdparty distribution dependencies and
interpreter major/minor versions.

Improve space efficiency of `--venv` mode.

---

pex/bin/pex.py
pex/environment.py
pex/pex_builder.py
pex/resolver.py
tests/test_environment.py

Previously, installed wheels were re-hashed when adding them to a PEX.
This was wasted time and effort that showed up particularly strongly
when building a large PEX that used a fast --pex-repository resolve.
Fixes #1533

Do not re-hash installed wheels.

---

pex/pip.py
pex/resolve/resolver_options.py
tests/integration/conftest.py
tests/integration/test_integration.py
tests/integration/test_issue_1537.py

Previously, if the `--cert` path supplied was relative, `--isolated`
builds would fail when the `--cert` was passed to Pip via env var and
the isolated build needed to resolve `setup_requires` using the cert
since the isolated build would have a fresh new CWD. Add a failing test
for this and fix.
Fixes #1537

Always pass absolute cert path to Pip.

---

pex/bin/pex.py
pex/pex_bootstrapper.py
pex/pex_info.py
tests/integration/test_pex_bootstrapper.py

Previously, `--venv` mode PEXes always used symlinks for site-packages
dependencies; now there is a `--venv-site-packages-copies` option to
allow the choice of hard links / copies when symlinks are not understood
by projects installed in site-packages.
Fixes #1542

Add knob for `--venv` site-packages symlinking.

---

tests/integration/test_integration.py

The release added a warning that trips up a test. Pin low to avoid this
since setuptools version is incidental to the test.
See: https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6000

Work around setuptools 60 release in test.

---

.github/workflows/ci.yml

In #1545 I missed updating CI handling. Although this led to no errors,
the cache key bump at least, was needed to save cache space and purge
the old 3.8 pyenv interpreter stored there.

Update CI handling of pyenv IT interpreters.

---

pex/bin/pex.py
pex/resolver.py
tests/integration/test_issue_1550.py
tests/test_environment.py
tests/test_resolver.py

The only place Pex cares about this is at runtime when ranking
requirements to pick distributions to add to the `sys.path`. Since Pip
will have already resolved one unique distribution per requirement
family per relevant marker environment, we will be safe just picking the
highest ranked distribution.
Fixes #1550

Fix Pex to be duplicate requirement agnostic.

---

pex/tools/commands/venv.py
pex/tools/commands/virtualenv.py
tests/integration/tools/commands/test_venv.py

It's perfectly legitimate to have multiple distributions provide the
exact same file; namely, when the file is either a `pkgutil` or
`pkg_resources` namespace package `__init__.py`. Fix venv population
collision detection logic to not only consider the destination path,
but also the source content. Only consider a file contribution a
collision if it provides differing contents from a prior contribution.
Fixes #1570

Allow for duplicate files in venv population.

---

pex/cli/commands/lock.py

Allow update to use --indent just like create and parametrize the
lockfile option so that the help text is appropriate per the subcommand
being run.
Work towards #1402.

Cleanup lock options.

---

tox.ini

It's handy to be able to easily execute Pex's vendored versions of
tools when experimenting.

Add debug tox envs for vendored tools.

---

pex/interpreter_constraints.py
tests/test_interpreter_constraints.py

This will be used to filter distributions in platform agnostic resolves
when interpreter constraints are specified.
Work towards #1402.

Introduce iter_compatible_versions.

---

tests/integration/conftest.py

Previously this was flaky because the atomic directory was not actually
being used.

Fix the `pex_bdist` fixture.

---

pex/vendor/__init__.py
pex/vendor/_vendored/pip/pip/_vendor/packaging/__about__.py
pex/vendor/_vendored/pip/pip/_vendor/packaging/markers.py
pex/vendor/_vendored/pip/pip/_vendor/packaging/requirements.py
pex/vendor/_vendored/pip/pip/_vendor/packaging/specifiers.py
pex/vendor/_vendored/pip/pip/_vendor/packaging/tags.py
pex/vendor/_vendored/pip/pip/_vendor/packaging/utils.py
pex/vendor/_vendored/pip/pip/_vendor/vendor.txt

This picks up upstream support for mac universal2 wheels.
Fixes #1587

Update vendored Pip to 386a54f0.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.65 release.

---

docs/buildingpex.rst

Hello, I was playing with the `--platform` option while I've got this error:
```
root@f38a03ba9139:/# cat req.txt
fastapi==0.73.0; python_full_version >= "3.6.1"
root@f38a03ba9139:/# pex --requirement=./req.txt --platform manylinux1_x86_64-cp-38-cp38 -o /tmp/deletemelater.pex
ERROR: Exception:
File "/root/.pex/venvs/s/83c98751/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
status = self.run(options, args)
File "/root/.pex/venvs/s/83c98751/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
return func(self, options, args)
File "/root/.pex/venvs/s/83c98751/venv/lib/python3.8/site-packages/pip/_internal/commands/download.py", line 130, in run
requirement_set = resolver.resolve( …
```

Docs: Clarify that 'python_full_version' is not available if '--platform' is used.

---

pex/environment.py
tests/integration/test_issue_1598.py

There was a narrow case of loose layout PEXes that would not mount in
the `PEX_ROOT` (when set in the environment) that this fixes. That
narrow case was exercised by the `pip.pex` PEX that Pex itself creates
to perform resolves with.
Fixes #1598

Respect `PEX_ROOT` in `PEXEnvironment.mount`.

---

pex/bin/pex.py
pex/cli/command.py
pex/cli/commands/__init__.py
pex/cli/commands/interpreter.py
pex/cli/testing.py
pex/resolve/target_configuration.py
pex/resolve/target_options.py
tests/integration/cli/commands/test_interpreter_inspect.py
tests/integration/cli/commands/test_lock.py

This command can be used to get a full marker environment to
support #1597 complete remote platform specification. Its similar
to the `interpreter` PEX tool but works without having to point
at a PEX which will be what a user of #1597 will want.

Introduce `pex3 interpreter inspect`.

---

tests/integration/conftest.py

The MarkupSafe dependency had recently released, breaking tests
with a hung process since the test assumes mitmdump will start:
```
$ tox -epy310-integration -- -n0 -vvsk test_requirements_network_configuration
...
File "/tmp/tmpew1lj8a3/bin/mitmdump", line 8, in <module>
sys.exit(mitmdump())
...
File "/tmp/tmpew1lj8a3/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
File "/tmp/tmpew1lj8a3/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/tmp/tmpew1lj8a3/lib/python3.10/site-packages/markupsafe/__init__.py)
```

Lock the mitmproxy resolve to fix at known good.

---

docs/buildingpex.rst
pex/interpreter.py
pex/pep_508.py
pex/platforms.py
pex/resolve/target_options.py
pex/testing.py
tests/integration/test_issue_1597.py
tests/resolve/test_target_options.py
tests/test_pep_508.py
tests/test_platform.py

Although `--complete-platform` allows every foreign platform resolve with
available wheels to succeed, often `--platform` would be enough if the
`python_full_version` marker environment entry could be derived from it.
Expand the syntax accepted for the PYVER field to support dotted
versions and, when 3-component dotted version is supplied, create a
`python_full_version` marker environment entry.
This should prove to be a more workable corrective than creating and
consuming a `--complete-platform` as introduced in #1609 for most users 
affected by #1597.

Expand `--platform` syntax: support full versions.

---

pex/pep_508.py
pex/pip.py
tests/test_pep_508.py

We fail resolves that require unknown environment markers when building
a PEX via Pip and we should do the same when resolving from a PEX.
Although this case has not been knowingly exercised yet (Pants only
subsets for local interpreters and not foreign platforms), it is a both
inconsistent and incorrect behavior.
We'll have a similar need to resolve using platforms against lock files
shortly and all three forms of resolve should behave the same.

Never default marker environment entries.

---

pex/environment.py
pex/targets.py
tests/test_targets.py

This will be needed to resolve from lock files.

Lift `Requires-Python` evaluation to Target.

---

pex/environment.py
pex/pep_425.py
pex/pip.py
pex/rank.py
pex/resolve/locked_resolve.py
pex/resolve/lockfile/lockfile.py
pex/targets.py
tests/integration/test_issue_1597.py
tests/test_environment.py

Previously some parts of the codebase used larger ints to denote better
fits and others used smaller ints for this. This resulted in a
mix of sorts of ranked things in the codebase which could be confusing.
Push the ordering, choosing and sorting into Rank to help make sense of
all this and ensure subset rwsolve ranking works the same as lockfile
resolve ranking.

Introduce Rank and use it unify resolve ranking.

---

tox.ini

There was a Flit release yesterday that broke `tox -epackage`.
See: https://github.com/pypa/flit/issues/530

Work around a Flit bug.

---

pex/resolve/locked_resolve.py
tests/resolve/test_locked_resolve.py

The Lockfile class already has a source field that callers of
`LockedResolve.resolve` will be able to pass in.

Plumb a lock source to resolve error messages.

---

tests/integration/venv_ITs/test_issue_1637.py
tox.ini

Python 3 (Until a fix here in 3.9: https://bugs.python.org/issue13601)
switched from stderr being unbuffered to stderr being buffered by
default (See more here: https://bugs.python.org/issue13597). This can
lead to tests checking stderr failing to see what they expect if the
stderr buffer block has not been flushed. Force stderr line buffering
(which is what setting PYTHONUNBUFFERED nets you) so that tests can
rely on stderr lines being observable.

Force stderr to be unbuffered in tests.

---

pex/fetcher.py
tests/test_fetcher.py

This was added in #152 to fix #101 but has since been lost to vendored
Pip taking over for ~all network requests. Pex will be fetching
artifacts recorded in its lockfiles now; so it's time to restore this.
Work towards #1583.

Restore the Pex User-Agent.

---

pex/resolve/lockfile/__init__.py
pex/resolve/lockfile/download_manager.py
tests/integration/cli/commands/test_lock.py

For the local case of lock create and then later resolve, it will be
good to retain the (primary) artifacts downloaded by Pip for the local
interpreter when creating the lock in order to save downloading those
artifacts again when later resolving from the lock.
Work towards #1583.

Retain and index downloads when locking.

---

pex/bin/pex.py
pex/cli/commands/lock.py
pex/pip.py
pex/resolve/lock_resolver.py
pex/resolve/lockfile/__init__.py
pex/resolve/lockfile/download_manager.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
pex/resolver.py
pex/result.py
tests/integration/cli/commands/test_lock.py
tests/integration/test_lock_resolver.py
tests/resolve/test_resolver_options.py

The Pex CLI can now resolve from a lock file created via
`pex3 lock create` when creating PEX files.
Closes #1583

Introduce `--lock` resolves.

---

pex/resolve/lock_resolver.py
pex/resolve/lockfile/__init__.py
pex/resolve/requirement_configuration.py
pex/resolve/resolver_options.py
tests/integration/test_lock_resolver.py

Closes https://github.com/pantsbuild/pex/issues/1657.
A followup will make sure that we can support `pex --lock` when the lock is empty.

`--lock` without requirements installs the entire lock.

---

pex/pex_builder.py
pex/pip/__init__.py
pex/pip/runtime_patches.py
pex/pip/tool.py
pex/platforms.py
pex/resolve/lock_resolver.py
pex/resolver.py
pex/testing.py
tests/integration/test_issue_539.py
tests/test_dist_metadata.py
tests/test_finders.py
tests/test_pip.py
tox.ini

This moves the Pip tool into its own package and extracts the Pip runtime
patching code into a sibling resource that can be type-checked and linted.
Fixes #1581

Extract Pip runtime patches.

---

pex/interpreter_constraints.py
pex/pip/runtime_patches.py
pex/pip/tool.py
tests/integration/cli/commands/test_issue_1667.py

Previously any dependency that satisfied just one interpreter version
in an IC range would be picked which was problematic if that dependency
version did not satisfy all interpreters in the range. Force a universal
resolve with an IC range to satisfy every Python version in that range.
Fixes #1667

Ensure universal locks cover IC range.

---

pex/environment.py
pex/pex_builder.py
tests/integration/test_issue_1683.py

The switch from sha1 to sha256 hashes in #1661 did not cover this
feature. Simplify and use the existing machinery to get at a PEX's
distributions.
Fixes #1683

Fix `--requirements-pex`.

---

pex/environment.py
pex/resolve/locked_resolve.py
tests/resolve/test_locked_resolve.py
tests/tools/commands/test_venv.py

We had a robust utility for this, but it was the evolution of copy-pasta
and not all the instances of copy-pasta were cleaned up. Now they are.
Fixes #1676

Fix `--lock` resolve wheel tag parsing.

---

pex/resolver.py
tests/integration/cli/commands/test_issue_1688.py

Previously multiplatform PEXes built via a `--lock` that selected sdists
would fail to gather the wheel built from the sdist for each applicable
platform.
Fixes #1688

Fix `--lock` for multiplatform via sdists.

---

pex/hashing.py
pex/pep_376.py
pex/pex_info.py
pex/pip/tool.py
pex/pip/vcs.py
pex/requirements.py
pex/resolve/lock_resolver.py
pex/resolve/locked_resolve.py
pex/resolve/lockfile/__init__.py
pex/resolve/lockfile/download_manager.py
pex/resolve/lockfile/json_codec.py
pex/resolve/resolved_requirement.py
pex/resolve/resolver_options.py
pex/resolve/testing.py
pex/util.py
tests/integration/cli/commands/test_lock.py
tests/integration/cli/commands/test_vcs_lock.py
tests/integration/test_lock_resolver.py
tests/integration/test_locked_resolve.py
tests/resolve/lockfile/test_download_manager.py
tests/resolve/lockfile/test_json_codec.py
tests/resolve/test_locked_resolve.py
tests/test_hashing.py
tests/test_requirements.py

This supports all forms of VCS requirements Pip supports as direct or 
transitive requirements. VCS source archives fetched by Pip are sha256
hashed by Pex providing a stable & secure fingerprint even for VCS
requirements pointing to possibly mutable tags or branches or even
insecure commit ids.
Fixes #1556

Add support for locking VCS requirements.

---

CHANGES.rst
pex/version.py

Closes https://github.com/pantsbuild/pex/issues/1691.

Prepare the 2.1.75 release.

---

RELEASE.rst

Taken from https://stackoverflow.com/questions/41052538/git-error-gpg-failed-to-sign-data.

Add tip for releasing from macOS

---

pex/common.py
pex/enum.py
pex/resolve/lock_resolver.py
pex/resolve/lockfile/download_manager.py
tests/test_common.py
tests/test_enum.py

This avoids spurious deadlock detection errors under Linux.
Fixes #1693

Fix lock_resolver to use BSD file locks.

---

pex/bin/pex.py
pex/common.py
pex/pex_builder.py
tests/test_pex_builder.py

Support uncompressed PEXes.

---

pex/pip/tool.py
tests/integration/cli/commands/test_issue_1711.py

When we clear the database and a resolve back-tracks, we lose the
additional artifact urls needed to fill in the backtracked requirement
lock encountered later in the resolve.
Previously the clearing was done to relieve memory pressure during the
analysis but measurements show even moderately large resolves collect
only a handful of MBs worth of link data. We could collect 100x more
links in a very large resolve and still be OK here on all but the most
constrained machines. As such, we simply stop clearing the crawled link
database during analysis.
Fixes #1711

Don't clear lock link database during analysis.

---

pex/bin/pex.py
pex/cli/commands/lock.py
pex/compatibility.py
pex/pip/tool.py
pex/resolve/lock_resolver.py
pex/resolve/locked_resolve.py
pex/resolve/lockfile/__init__.py
pex/resolve/lockfile/json_codec.py
pex/resolve/path_mappings.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
tests/integration/cli/commands/test_issue_1413.py
tests/integration/test_lock_resolver.py
tests/resolve/lockfile/test_json_codec.py
tests/resolve/test_path_mappings.py

Although you can still create locks that contain absolute paths from the
local system, Pex now supports canonicalizing such paths for portable
locks with the `--path-mapping` option available when creating and
consuming locks.
The classic example where this is useful is a shared find-links repo
accessed as a network mount somewhere in the user's home directory. A 
portable lock for PEXes that get at least some of their distributions
resolved from such a find-links repo can be created like so:
```
pex3 lock create \
--find-links $HOME/corp/shares/find-links \
--path-mapping "\
CORP_FL|$HOME/corp/shares/find-links|\
The local path of the corporate find-links repo network mount.\
"
...
```
The lock file will have all paths beginning with
`$HOME/corp/shares/find-links` substituted with the …

Support canonicalizing absolute paths in locks.

---

pex/resolve/locked_resolve.py
tests/integration/test_lock_resolver.py

Previously, the first resolve of a multiply-required project would bake
in the extras resolved for that requirement and subsequent requirements
for the project in the resolve would not get their additional extras
resolved. The resolve graph walk is fixed to be extras aware.
Fixes #1717

Fix `--lock` resolver extras handling.

---

pex/resolver.py
tests/integration/test_issue_1726.py

Previously names were not always normalized per PEP-503 in version
compatibility checks.
Fixes #1726

Fix Pex resolve checking.

---

pex/cli/commands/lock.py
pex/resolve/target_configuration.py
tests/integration/cli/commands/test_issue_1667.py
tests/integration/cli/commands/test_issue_1711.py
tests/integration/cli/commands/test_issue_1734.py
tests/integration/cli/commands/test_lock.py
tox.ini

Previously the current interpreter was used to perform the lock resolve
(which is OK) and the resolve post-processing (which was not OK). Now
we force finding a local interpreter that meets ICs up-front and use
that for both the resolve and post-processing.
Fixes #1734

Fix universal lock creation for ICs.

---

pex/resolve/locked_resolve.py
tests/integration/cli/commands/test_issue_1741.py

Previously, valid pre-release version artifacts could be rejected when
resolving from a lock file.
Fixes #1741

Fix `--lock` handling of pre-release versions.

---

pex/commands/command.py
tests/commands/test_command.py
tests/test_packaging.py

They have no effect and are silently overwritten by
the same args (or their defaults) registered on each
subcommand.
Previously, `pex -v subcommand` would silently ignore the
arg in the global position because -v is also registered on
the subcommand (and similarly for all global args).
Now at least you get an error. With this change all args,
including global ones, must appear on the cmd-line after
the subcommand.

Don't register global args in global position.

---

pex/pex.py
tests/test_pex.py

Parse options args for interpreter options. If they are present re-exec passing the proper options to the interpreter. If they are not present run the code directly.

Re-exec with interpreter-options when set. (#1745)

---

.gitignore
pex/common.py
pex/pex.py
pex/venv/pex.py
tests/integration/venv_ITs/test_issue_1745.py
tests/test_pex.py

Apply @BrandonTheBuilder's work in #1746 to the `--venv` case and flesh
out complete support for Python interpreter emulation by adding `.` to
the `sys.path` when running as an interpreter and handling interpreter
execution of directories.
Fixes #1745

Complete support for PEX Python interpreter mode.

---

pex/testing.py
pex/vendor/_vendored/pip/pip-20.3.4.dist-info/METADATA
tests/test_bdist_pex.py

I'm not sure how the vendoring could have drifted. The tox vendor env
has pip, setuptools and wheel pinned. Since the drift is of no
consequence, I'm rolling with it for now.
Also Pin Pip lower then 22.1 since the 22.1 release a few days ago
breaks the bdist_pex tests.

Fix CI bitrot breaks.

---

pex/pip/tool.py
tests/integration/cli/commands/test_issue_1665.py

Previously the save was qualified against the download directory, but
this led to missed save identifications when the download directory was
relative to the CWD. Since there is only one type of save going on
during a download, just capture them all regardless of path since
they're all in the download directory anyhow.
Fixes #1758

Fix lock save detection to be more robust.

---

.github/workflows/ci.yml
pex/interpreter_constraints.py
pex/result.py
pyproject.toml
scripts/typecheck.sh
tests/bin/test_sh_boot.py
tests/integration/cli/commands/test_issue_1711.py
tests/integration/cli/commands/test_issue_1741.py
tests/integration/cli/commands/test_lock.py
tests/integration/test_integration.py
tests/integration/test_issue_1597.py
tests/integration/test_issue_1656.py
tests/integration/test_issue_1726.py
tests/integration/test_issue_539.py
tests/integration/test_lock_resolver.py
tests/integration/test_reproducible.py
tests/test_targets.py
tox.ini

Add 3.11 support.

---

pex/environment.py
pex/pex_bootstrapper.py
pex/pex_info.py
pex/tools/commands/interpreter.py
pex/tools/main.py
tests/integration/test_pex_bootstrapper.py
tests/test_pex_bootstrapper.py

Previously two proxies for interpreter applicability were used:
1. The shebang selected interpreter or the explicit interpreter used
to invoke the PEX.
2. Any embedded interpreter constraints.
This could lead to selecting an interpreter that was not actually able
to resolve all required distributions from within the PEX, which is the
only real criteria, and a failure to boot.
Fix the runtime interpreter resolution process to test an interpreter
can resolve the PEX before using it or re-execing to it.
In the use case, the resolve test performed is cached work and leads to
no extra overhead. In the re-exec case the resolve test can cost
O(100ms), but at the benefit of ensuring either the selected interpreter
will definitely work or no interpreters on the search path can work.
Fixes #1020

Select PEX runtime interpreter robustly.

---

pex/pip/tool.py

By forcing the temporary directories Pip creates to be on the same
filesystem as the Pip cache, we indirectly ensure the caching Pip does
is atomic and safe in the presence of parallel Pex runs.
Fixes #1776

Ensure Pip cache operations are atomic.

---

pex/pex_builder.py
pex/testing.py
tests/integration/test_integration.py
tests/integration/test_issue_1520.py
tests/test_environment.py
tests/test_pex.py
tests/test_pex_builder.py

This was only used by tests. The rest of Pex operates only on installed
wheels.
This is part of a series of a refactors needed to remove dependency
cycles in support of #1696.

Remove support for adding whl files to PEXBuilder.

---

pex/bin/sh_boot.py
pex/pex.py
pex/pex_builder.py
pex/venv/pex.py
tests/integration/test_sh_boot.py

Now `--sh-boot` mode PEXes have `sys.argv[0]` and the `PEX` environment
variable set consistently with all other modes of PEX execution.
Fixes #1782

Fix `--sh-boot` argv0.

---

.github/workflows/ci.yml
tests/integration/tools/commands/test_venv.py

Two fixes:
1. Fix dependency drift in test.
A protobuf release foiled the legacy resolver and this went
unchecked.
2. Bump 3.11 shards to latest beta.

CI maintenance.

---

pex/pex.py
pex/testing.py
tests/integration/test_issue_1809.py
tests/test_interpreter.py

Pro-actively fix `sys.displayhook` as well.
Fixes #1809

Fix PEX scrubbing to account for `sys.excepthook`.

---

pex/pex.py
pex/variables.py
tests/integration/test_issue_1802.py
tests/test_pex.py

For historical reasons that are no longer relevant, `PEX` accrued
complicated teardown code that, among other things, replaced
`sys.stderr` with `/dev/null`. This could lead to lost messages to
stderr. Simply remove the complicated and no-longer useful code.
Fixes #1802

Simplify `PEX` teardown / leave stderr in tact.

---

pex/resolve/downloads.py
pex/resolve/lock_resolver.py
tests/integration/test_issue_1817.py

As of Pex 2.1.93, sdists that built native extensions or used a PEP-517
build system would not be successfully downloaded when constructing a
PEX from a lock.
Fixes #1817

Fix `pex --lock ...` handling of sdists.

---

pex/cli/commands/lock.py
pex/resolve/locked_resolve.py
pex/resolve/locker.py
pex/resolve/locker_patches.py
pex/resolve/lockfile/json_codec.py
pex/resolve/lockfile/model.py
pex/resolve/lockfile/operations.py
pex/resolve/lockfile/updater.py
tests/integration/cli/commands/test_issue_1821.py
tests/resolve/lockfile/test_json_codec.py

Add the new `pex3 lock create --target-system {linux,mac,windows} ...`
option to restrict `--style universal` lock creation to dependencies
and artifacts compatible with the given target operating systems.
Fixes #1821

Support restricting universal lock target os.

---

pex/bin/sh_boot.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/venv/pex.py
tests/integration/test_integration.py
tests/integration/test_setproctitle.py
tests/integration/test_sh_boot.py
tests/tools/commands/test_repository.py

Re-work both ZIPAPP and --sh-boot execution of --venv PEXes to avoid shebang
length limits.

Avoid ENOEXEC for --venv shebangs.

---

pex/interpreter.py
pex/pex.py
pex/venv/pex.py
tests/integration/test_issue_1825.py

Previously PEXes were not behaving like a Python interpreter when
`PEX_EXTRA_SYS_PATH` was used to add entries to the `sys.path`. In a
traditional Python interpreter those would be added with `PYTHONPATH`
which subprocesses forked from the Python interpreter would inherit by
default.
Fixes #1825

Fix `PEX_EXTRA_SYS_PATH` propagation.

---

pex/venv/pex.py

Previously this used `PYTHONPATH` for propagation, which could lead to
issues executing foreign Pythons in subprocesses. Switch to using a
`.pth` file. Although the problem of polluting foreign Pythons in
subprocesses remains for zipapp PEXes, it is the case that `--venv` is
Pex's maximum compatibility mode and this can be viewed as yet another
case where a Pex feature breaking a Python app should be solved by using
`--venv` mode.
Fixes #1836

Fix `--venv` PEX `PEX_EXTRA_SYS_PATH` propagation.

---

pex/pip/foreign_platform.py

This was broken from the get-go in #1787. It's unclear to me how the
`test_create_universal_platform_check` test added in #1824 didn't fail
from the get-go, but it does now and this fix fixes that test for the
`--platform macosx_10.9_x86_64-cp-310-cp310 psutil==5.9.1` abbreviated
platform case.
Discovered in CI for #1845 as a failure unrelated to that change.

Tags should be patched for `--platform`.

---

pex/hashing.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pip/foreign_platform.py
pex/third_party/__init__.py
pex/util.py
tests/integration/test_pex_import.py

You can now use a PEX as a mostly normal `sys.path` entry. You do need
to activate it though and that can be done in two ways:
1. Perform an `import __pex__` before importing anything else you
might need that lives in a PEX `sys.path` entry.
2. Import what you need in one step via `from __pex__ import colors` in
the case where the PEX contains `ansicolors`, for example.
The second method is useful in cases where you can't influence which
python interpreter to run (In which case you could just specify the PEX
file itself), but you can influence the `sys.path`. The motivating
example of this is AWS Lambda functions for Python. One mode of
deploying these is in a zip. Here you can't pick the Python interpreter,
just its version, but you can specify the zip and an entry point. As
such you can …

Add support for importing from PEXes.

---

pex/resolve/downloads.py
pex/resolve/lock_resolver.py
pex/resolve/lockfile/create.py
tests/integration/test_downloads.py

Fix the `ArtifactDownloader` to re-use the tricks used for
`--style universal` locks to trick Pip into not rejecting artifacts
that are not compatible with the current interpreter.
FIxes #1849

Fix artifact downloads for foreign platforms.

---

pex/pep_376.py
pex/resolve/downloads.py
pex/resolve/lock_resolver.py
pex/resolve/lockfile/create.py
pex/venv/virtualenv.py

The lock resolver uses multiple threads to effect parallel downloads and
this was leading to errors in the non-thread-safe `fileinput.input` API
Pex uses as part of re-writing certain venv files when it tried to
initialize the Pip tool venv in multiple threads. Switch to a
thread-safe version of the `fileinput` API and also ensure the Pip tool
venv is created once in the main thread to avoid other multi-thread
issues.
Fixes #1852

Fix `pex --lock ...` concurrent download errors.

---

pex/resolve/locker.py
pex/resolve/locker_patches.py
pex/venv/pex.py
tests/integration/test_issue_1856.py

When this feature was added in #1821 the `sys_platform` and
`platform_system` environment markers were handled but the `os_name`
environment marker was missed. This allowed Windows-only deps to sneak
through and attempt to be locked even when passing
`--target-system linux --target-system mac`.
Fixes #1856

Fix lock creation `--target-system` handling.

---

pex/common.py
pex/vendor/__main__.py
tests/test_common.py

The function is only used by the vendoring script where its
non-robustness in the general case is fine and where its use instead of
`pex.venv.virtualenv.find_site_packages_dir` is necessitated by the
bootstrapping issues inherent in using vendored code while vendoring it.
Follow up to #1863

Inline `pex.common.find_site_packages`.

---

pex/pep_376.py
pex/pip/tool.py

This fixes a further corner-case detecting `--prefix` installation
`site-packages` directories surfaced by Red Hat based OSes where
"purelib" and "platlib" installation directories differ (`lib/` vs.
`lib64/`). We now simply check each `site-packages` directory found
under the installation `--prefix` for an installation `RECORD` and use
the first such one found. This is safe since we know
`pip install --no-deps --prefix <dist>` only installs one distribution
once.
Fixes #1866

Fix wheel installs: account for purelib & platlib.

---

.github/workflows/ci.yml
pex/pex.py
pex/pex_bootstrapper.py
tests/integration/test_issue_1031.py
tests/integration/test_issue_1870.py
tests/test_pex.py

Although runtime over-rides worked, e.g.:
`PEX_INHERIT_PATH=prefer ./my.pex`, build-time configuration via 
`--inherit-path={prefer,fallback}` did not.
Fixing this exposed #992 in tests which is also fixed here by skipping
un-import of virtualenv's `_virtualenv` `sys.meta_path` importer used
by it for patching `distutils`.
Fixes #1870
Fixes #992

Fix `--inhert-path` handling.

---

.github/workflows/ci.yml
pex/build_system/pep_518.py
scripts/package.py
tests/build_system/test_pep_518.py
tests/integration/build_system/test_pep_517.py
tests/integration/test_issue_1872.py
tox.ini

Previously locking would fail for local projects when attempted from a
Pex PEX.
Fixes #1872

Fix `pex3 lock ...` when run from the Pex PEX.

---

pex/layout.py
pex/pex_builder.py
tests/integration/test_issue_1879.py

This was historically how Pex worked when there was only one layout and it partly
worked with the introduction of the `loose` and `packed` layouts but failed either
silently or loudly when transitioning from a `zipapp` layout to a directory-based
layout or vice-versa.
Fixes #1879

Ensure `--output` always overwrites destination.

---

pex/compatibility.py
pex/fetcher.py
pex/resolve/lock_resolver.py
pex/resolve/pep_691/__init__.py
pex/resolve/pep_691/api.py
pex/resolve/pep_691/fingerprint_service.py
pex/resolve/pep_691/model.py
pex/resolve/resolvers.py
tests/integration/resolve/__init__.py
tests/integration/resolve/pep_691/__init__.py
tests/integration/resolve/pep_691/test_api.py
tests/resolve/pep_691/__init__.py
tests/resolve/pep_691/test_api.py
tests/resolve/pep_691/test_fingerprint_service.py
tests/resolve/pep_691/test_model.py

This is needed to support newer Pip where fingerprints are hidden from the
verbose logs Pex scrapes to build locks. The Pex fallback of downloading
every artifact locked and hashing it works but is just too expensive to
be the normal case.
Work towards #1805

Add support for PEP-691.

---

pex/resolver.py

Previously there was ambiguity in the key used to store built wheels when the
local OS (platform tag) could take on different values as is the case in
macOS Big Sur where 10.16 and 11.0 are synonyms.

Ensure locally built wheel is consumable locally.

---

pex/pex_builder.py

Avoid in-flight .pyc compiles of Pex bootstrap code.

---

pex/pip/vcs.py

This change works with both current vendored Pip and Pip 22.2.2.
Work towards #1805

Make vcs zip handling more robust.

---

pex/build_system/testing.py
pex/interpreter.py
pex/pip/installation.py
pex/pip/tool.py
pex/pip/version.py
pex/platforms.py
pex/resolve/configured_resolver.py
pex/resolve/downloads.py
pex/resolve/lock_resolver.py
pex/resolve/resolvers.py
pex/resolver.py
pex/testing.py
pex/third_party/__init__.py
tests/integration/cli/commands/test_issue_1801.py
tests/integration/test_issue_539.py
tests/test_dist_metadata.py
tests/test_finders.py
tests/test_pip.py

This is unused in this commit except in tests, but forms the heart of
support for newer Pip versions behind firewalls. Vendored Pip with all
user Pip configuration is used to fetch newer Pip.
Work towards #1805

Support dynamic Pip installations.

---

tests/integration/cli/commands/test_vcs_lock.py

The default WSL environment on Windows is Ubuntu 20.04 which has an old enough git to not support `git init -b`.

Make test tolerant of older git.

---

pex/common.py

Previously, in the astronomically unlikely case that two (or more) attempts at creating an atomic directory collided on their UUID4-based work directory, the colliding attempts would all succeed and possibly lead to a corrupt final target directory. Now work directory creation fails loudly when the work directory already exists. Re-try of the Pex command will ~always work in this case but we'll have a paper trail of a UUID4 collision.
Fixes #1901

Fail on atomic_directory work_dir collision.

---

tests/integration/build_system/test_pep_517.py

The poetry-core 1.2.0 release broke a floating dep in a poetry pre-release used by PEP 517 tests.

Fix CI break.

---

.github/workflows/ci.yml
pex/testing.py
pex/venv/virtualenv.py
tests/conftest.py
tests/integration/cli/commands/test_issue_1734.py
tests/integration/test_integration.py
tests/integration/test_interpreter_selection.py
tests/integration/test_issue_1031.py
tests/integration/test_issue_1202.py
tests/integration/test_issue_1422.py
tests/integration/test_issue_1560.py
tests/integration/test_issue_745.py
tests/integration/test_issue_898.py
tests/integration/test_issue_899.py
tests/integration/test_issue_996.py
tests/integration/test_pex_bootstrapper.py
tests/integration/test_pex_import.py
tests/integration/test_reexec.py
tests/integration/test_reproducible.py
tests/integration/test_sh_boot.py
tests/integration/test_shebang_length_limit.py
tests/integration/venv_ITs/test_virtualenv.py
tests/resolve/lockfile/test_lockfile.py
tests/resolve/test_pex_repository_resolver.py
tests/resolve/test_target_options.py
tests/test_interpreter.py
tests/test_pex.py
tests/test_pex_binary.py
tests/test_pex_bootstrapper.py
tests/test_resolver.py

This brings the set of canned pyenv interpreters to 2.7 and 3.{8,9,10},
paving the way for pyenv-win. PY27 use is minimized and made explicit
and lazy such that appropriate `pytest.skip()`s can be added in the
Windows port to skip over the handful of ramining integration tests that
truly mean to test against a Python 2.7 interpreter.

Migrate PY27 pyenv to PY39.

---

pex/requirements.py
tests/test_requirements.py

`urlparse` components are not unquoted. Without unquoting local version specifiers like `+cpu` are parsed as `%2Bcpu`.
Fixes #1919

Unquote path component of parsed url requirements

---

.github/workflows/ci.yml
pex/requirements.py
pex/resolve/downloads.py
pex/resolve/locker.py
pex/resolve/lockfile/create.py
tests/integration/resolve/test_issue_1918.py
tests/integration/test_locked_resolve.py
tests/resolve/test_locker.py
tox.ini

Previously redacted credentials from the Pip download log were embedded
in locked artifact URLs rendering the lock unusable. Now credentials are
fixed up before the lock file is written.
Fixes #1918

Fix locks for git+ssh with credentials.

---

pex/common.py
pex/ziputils.py
tests/test_zip_utils.py

This is not needed by Pex mainline but is needed to support Windows
console scripts which are realized as a sandwich of a windows PE stub,
a shebang line and a zipapp trailer. In this arrangement, the stub
executable header reads the zip trailer to find the sandwiched shebang
and then uses that shebang to pick a Python interpreter to run the
sandwich with. Pex needs to customize the sandwiched shebang just like
it needs to customize unix console script header shebangs so that the
venv interpreter is used to run the console script.

Add a Zip utility for manipulating zip headers.

---

pex/dist_metadata.py
pex/interpreter.py
pex/third_party/__init__.py

Large extras sets lead to an exponentially scaled collection of
fingerprinted distribution objects that need to be de-duped. The hash
codes calculated in doing so are expensive when the distribution
metadata contains a large number of requirements. Cache these hash codes
to improve boot time by two orders of magnitude.
In order to enable ergonomic caching of hash codes via attrs built in
feature for doing this, some new plumbing is added to the third party
vendored importer plumbing.
Fixes #1928

Fix slow PEX boot time when there are many extras.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.108 release.

---

pex/bin/pex.py
pex/cli/commands/interpreter.py
pex/cli/commands/lock.py
pex/dist_metadata.py
pex/interpreter.py
pex/interpreter_constraints.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pex_info.py
pex/resolve/resolver_configuration.py
pex/resolve/target_configuration.py
pex/resolve/target_options.py
pex/sh_boot.py
pex/tools/commands/graph.py
pex/tools/commands/interpreter.py
pex/tools/commands/repository.py
pex/util.py
tests/bin/test_sh_boot.py
tests/integration/cli/commands/test_issue_1734.py
tests/integration/cli/commands/test_lock.py
tests/integration/test_interpreter_selection.py
tests/integration/test_pex_bootstrapper.py
tests/integration/test_reexec.py
tests/test_interpreter.py
tests/test_pex_binary.py
tests/test_pex_bootstrapper.py
tests/test_pex_info.py
tests/tools/commands/test_interpreter_command.py

This work was initiated trying to fix #1928 when it appeared attrs 
cached_hash use was triggering a circular import. That turned out not to
be the case, but this work is still useful since it centralizes IC
behavior (OR semantics) and is needed to eventually fix #1580.

Extract an InterpreterConstraints type.

---

pex/variables.py
tests/integration/test_issue_1936.py
tests/test_variables.py

This fixes a regression reading the `PEX_PATH` variable introduced by
changes in #1902 that ended up attempting to add CWD as a PEX when 
`PEX_PATH` was set to the empty string in the environment.
Since `PEX_PATH` is closest in spirit to a `PATH` of files instead of a
`PATH` of directories like `PATH` and `PYTHONPATH`, the old relied-upon
behavior makes sense generally.
Fixes #1936

Don't treat `PEX_PATH=` as `.` like other PATHS.

---

pex/bootstrap.py
pex/interpreter.py
pex/pex.py
pex/pth.py
pex/util.py
tests/integration/test_pex_import.py
tests/test_interpreter.py
tests/test_pex.py
tests/test_pth.py
tests/test_util.py

All the calculations needed to support classification of `sys.path` entries as belonging to site-packages, extras paths or the stdlib are now completed during interpreter identification. This is both more efficient (5-10ms savings on zipapp PEX boot time), since several calculations now become cached for the lifetime of the interpreter installation on a machine, and more correct, since the interpreter identification is done in fresh Python subprocess executed with `-s`. This hardens `sys.path` from additions by external code calling into the PEX using the old pex_bootstrapper bootstrap_pex_env API or using a PEX as a `sys.path` entry as afforded by the `__pex__` import hook.
Fixes #1944

Fix `sys.path` scrubbing.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.110 release.

---

docs/recipes.rst
pex/bin/pex.py
pex/pex.py
pex/pex_info.py
pex/venv/pex.py
tests/integration/test_inject_env_and_args.py

Pex now supports setting defaults for environment variables and
injecting default arguments for the entry point chosen at PEX build
time. This eliminates the need for projects like
https://github.com/kwlzn/pyuwsgi_pex and makes it easy to package a
PEXed framework app where the main entry point is fixed in the framework
and the hooks are configured to point to user supplied entry points.
The `__pex__` import hook introduced in #1845 removed the need for
projects like https://github.com/pantsbuild/lambdex. This change removes
the last known legitimate API use of Pex and paves the way for Pex 3 to
be cut in good conscience with a CLI-only API that does not hinder any
known use cases.
Fixes #987

Support injecting args and env vars in a PEX.

---

pex/resolve/locked_resolve.py
pex/resolve/lockfile/json_codec.py
tests/integration/test_issue_1949.py

Previously, arbitrary equality could not be used in requirements when resolving against a lockfile when the project being resolved had a PEP-440 compatible version that was normalized.
Fixes #1949

Fix lock resolution to handle arbitrary equality.

---

.github/workflows/ci.yml
.github/workflows/release.yml

This gets ahead of the deprecation announced here:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Migrate from `::set-output` to `$GITHUB_OUTPUT`.

---

pex/atomic_directory.py
pex/common.py
pex/interpreter.py
pex/layout.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pip/installation.py
pex/platforms.py
pex/resolve/downloads.py
pex/resolve/lock_resolver.py
pex/resolve/lockfile/download_manager.py
pex/resolver.py
pex/testing.py
pex/third_party/__init__.py
pex/venv/virtualenv.py
tests/integration/conftest.py
tests/resolve/lockfile/test_download_manager.py
tests/test_common.py
tests/test_enum.py

Change `atomic_directory` to always grab an exclusive lock and use a
stable work directory per target directory to surface multiple lock
owners as up-front errors instead of possibly slow corruptions.

Re-work atomic_directory locking for faster / clearer failures.

---

pex/atomic_directory.py
tests/test_atomic_directory.py

This allows experimenting with making all Pex file locks use BSD style locks to help debug file locking issues. This environment variable knob can be removed at any time Pex sees fit.

Add a private `_PEX_FILE_LOCK_STYLE` knob.

---

pex/atomic_directory.py
pex/venv/pex.py
tests/test_atomic_directory.py
tests/test_common.py

This was broken by #1961 which did not account for the two unlocked
uses of AtomicDirectory by the pex.resolver for wheel building and
installing. Although those directories deserve a second look as
candidates for exclusive locking, we have seen no known issues with
those directories since introduction of AtomicDirectory up until #1961.
As such, this change just restores the prior behavior for those two
cases.
Fixes #1968

Restore AtomicDirectory non-locked good behavior.

---

pex/variables.py
pex/vendor/_vendored/attrs/attrs-21.5.0.dev0.dist-info/WHEEL
pex/vendor/_vendored/pip/pip-20.3.4.dist-info/WHEEL
pex/vendor/_vendored/setuptools/setuptools-44.0.0+3acb925dd708430aeaf197ea53ac8a752f7c1863.dist-info/WHEEL
tests/test_pip.py

fixes #1885 
Problem:
When the PEX_PYTHON_PATH contains paths to allowed interpreters that are symlinks to the real interpreter the venv_dir hash value doesn't end up including a valid interpreter. The is a particular problem for the pip.pex venvs that are created by `resolver.resolve` because those pip.pex have no interpreter constraints. they rely on the venv interpreter being the correct one matching the resolve target. If an existing pip.pex venv exists with the wrong venv interpterer the venv_dir paths can collide resulting in the `ensure_venv` returning a path to a pip.pex with the incorrect interpreter, and thus with different resolve behavior.
Solution:
Make sure that when computing the venv_dir if the PEX_PYTHON_PATH contains symlinks to interpreters those are resolved down to …

Map pex python path interpreter to realpath when creating venv dir hash.

---

pex/vendor/__main__.py
pex/vendor/_vendored/attrs/attrs-21.5.0.dev0.dist-info/METADATA
pex/vendor/_vendored/attrs/attrs-21.5.0.dev0.dist-info/WHEEL
pex/vendor/_vendored/pip/pip-20.3.4.dist-info/METADATA
pex/vendor/_vendored/pip/pip-20.3.4.dist-info/WHEEL
pex/vendor/_vendored/pip/pip-20.3.4.dist-info/entry_points.txt
pex/vendor/_vendored/setuptools/setuptools-44.0.0+3acb925dd708430aeaf197ea53ac8a752f7c1863.dist-info/WHEEL

This was all accounted for with `--no-build-isolation` and tox venv
pinning with an extensive comment about all this to boot. For some
reason unclear to me, I undid `--no-build-isolation` in
https://github.com/pantsbuild/pex/pull/1661 though.
This just re-instates that flag and re-runs vendoring to get back to
stable wheel versions.

Fix vendoring wheel dependency drift.

---

pex/pex.py
pex/venv/pex.py

Fixes https://github.com/pantsbuild/pex/issues/1983.
Note that this PR doesn't revert the code to use the prior code (`sys.path.extend(os.environ.get("PEX_EXTRA_SYS_PATH", "").split(os.pathsep))`) as that might still add `""` when `PEX_EXTRA_SYS_PATH` is not in the environment.
Also note that this doesn't change anything related to https://github.com/pantsbuild/pex/issues/1982 (whose outcome might be that `""` is in `sys.path`, but for other reasons and in unrelated cases).

Only insert `""` to head of `sys.path` if a venv PEX runs in interpreter mode

---

pex/cli/commands/lock.py
tests/integration/cli/commands/test_export.py

Fixes https://github.com/pantsbuild/pex/issues/1989 and matches `pip-compile`'s behavior.
Test fails before change, passes after.

Use raw version when exporting

---

pex/resolve/target_configuration.py
tests/resolve/test_target_options.py

This makes --resolve-local-platforms work better with --complete-platforms: if there's an external complete platform specified for a platform that matches a local interpreter, the local interpreter's complete platform is checked against that external complete platform. If the local interpreter supports any additional tags, the local interpreter is not used.
If the local interpreter/environment is newer (supports more tags), the old behaviour would risk including wheels that aren't compatible with the external complete platform. That is, execution will fail, see https://github.com/pantsbuild/pants/issues/17621 for an example.
Fixes #1899

Check for --complete-platforms match when --resolve-local-platforms

---

pex/interpreter_constraints.py
pex/sh_boot.py
tests/bin/test_sh_boot.py
tests/integration/test_issue_1995.py
tests/test_interpreter_constraints.py

Previously a bare specifier assumed CPython; now it does not.
Fixes #1995

Fix interpreter constraint parsing.

---

pex/tools/commands/venv.py
pex/venv/pex.py
tests/integration/tools/commands/test_venv.py

Closes #2004 
When the option is set, console scripts in the generated virtualenv will not pass `-sE` to `python` in their shebangs. This is needed to allow customization of `PYTHONPATH` when running tools like `pylint`.

Add `--non-hermetic-scripts` option to `venv` tool.

---

CHANGES.rst
pex/pex_builder.py
pex/version.py
tests/integration/test_issue_1730.py
tests/integration/test_issue_2006.py

Prepare the 2.1.118 release.

---

pex/variables.py
tests/test_variables.py

This is more robust than having to scrub the environment of all PEX_* vars before running a PEX.
Fixes #2013

Add PEX_DISABLE_VARIABLES to lock down a PEX run.

---

.github/workflows/ci.yml
pex/testing.py
tests/integration/test_issue_1017.py

One broke due to a recent pyenv bug.
Another broke when numpy published a new version.
And that's why you always pin your deps!

Fix tests that broke due to changes in the world.

---

.github/workflows/ci.yml
pex/pex.py
pex/variables.py
pex/venv/pex.py
tests/integration/test_integration.py

When running a REPL via Pex (e.g., with Pants's repl goal), it can be useful to support command history.
Python normally sets up command history by default when the interpreter imports `site`, but Pex bypasses that. So this change re-introduces the suggested idiom for loading and saving history, per https://docs.python.org/3/library/readline.html#example
Also replace a few hardcoded forward-slashed paths with os.path.sep.

Support REPL command history.

---

pex/resolve/target_configuration.py
tests/resolve/test_target_options.py

Fixes https://github.com/pantsbuild/pex/issues/2026.
Previously the interpreter resolution was more strict than necessary. The `supported_tags` were only checked if the most specific tag of the complete platform matched the platform of the local interpreter. This prevented resolution in cases when it was possible and safe (ie all `supported_tags` of the interpreter as present in the `supported_tags` of the complete-platform).
Added an additional test for the above case. Fixed existing code and also improved various existing tests by adding `expected_complete_platforms`.

Fix interpreter resolution when using --complete-platform with --resolve-local-platforms

---

pex/bin/pex.py
pex/pex.py
pex/pex_bootstrapper.py
tests/integration/test_issue_2023.py

Both packed and zipped PEXes undergo an unzip into the PEX_ROOT prior to
any other action, establishing a known private cache of their contents.
Loose PEXes skip this step and run directly from their loose contents.
This is fine and speedy for the "zipapp" execution mode, but leads to an
incorrect venv cache in symlink mode where venv entries symlink back out
to the loose PEX and can thus be invalidated by moves outside Pex
control. Force loose PEXes in `--venv` mode to use copies so that their
cached venv is robust to external moves.
Fixes #2023

Fix loose `--venv` PEXes to be robust to moves.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.120 release.

---

pex/compatibility.py
pex/pip/tool.py

This adds logging for `pip` invocations, to make it easier to understand how pex is calling `pip`, such as when a single invocation is taking a long time (https://github.com/pantsbuild/pex/issues/2036).
This mirrors similar logging for Python invocations: https://github.com/pantsbuild/pex/blob/1f8e25a714e52c45a50a6d6ab2ee7cb9e21a92bb/pex/interpreter.py#L713-L716

Log all pip invocations

---

pex/requirements.py
pex/resolver.py
tests/integration/test_issue_2038.py

This has been a very long standing bug. The root issue is that
`pip download`, although it processes these deps and fails if not
present on the local filesystem, only handles resolving recursive
dependencies and it does not "download" the local distribution from its
referenced path on the file system to the `pip download` download dir.
As such, the normal Pex post-processing is foiled for these deps.
The fix provided here is in common infra used by both normal Pex builds
and `--lock` builds and uses a recursive post-processing step that
gathers all such dependencies from the downloaded distributions and
injects them into the normal Pex post-processing chain.
Fixes #2038

Handle file:// URL deps in distributions.

---

pex/jobs.py
tests/integration/test_issue_1336.py

Although the thread was not leaked per-se, it could run after `execute_parallel` returned which could cause parallel atomic_directory posix locks to fail.
Fixes one case in #1969.

Fix `execute_parallel` "leaking" a thread.

---

pex/build_system/pep_517.py
pex/build_system/pep_518.py
pex/build_system/testing.py
pex/dist_metadata.py
pex/jobs.py
pex/resolve/lockfile/create.py
tests/integration/cli/commands/test_issue_2050.py
tests/integration/cli/commands/test_lock_update.py

PEP-517 specifies an optional `prepare-metadata-for-build-wheel` hook.
This can be used to extract metadata from an sdist without actually
building a wheel from the sdist when supported by the PEP-517 build
backend. Augment the Pex lock creation code to 1st try this and only
fall back to building a wheel when the optional hook is not present.
This allows locking sdist-only platform-specific projects that are
not compilable on the current platform by avoiding compiling them.
Fixes #2050

Lock sdists with `prepare-metadata-for-build-wheel`.

---

pex/resolve/locker_patches.py
tests/integration/cli/commands/test_issue_2059.py

Previously, the non-standard but compliant `pypy` tag was not accounted
for. Re-work python tag parsing to account for the spec by including
acceptance of `cpython` and `pypy` implementation names as well as
versions with trailing `_` portion (which is ignored).
Fixes #2059

Fix python tag handling in IC locks.

---

pex/build_system/__init__.py
pex/build_system/pep_517.py
pex/build_system/pep_518.py
tests/integration/build_system/test_issue_2063.py

PEP-518 only requires `requires` and PEP-517 mandates falling back to
the default introduced here.
Fixes #2063

Handle `[build-system]` with no build-backend.

---

pex/common.py
pex/dist_metadata.py
pex/pip/download_observer.py
pex/pip/tool.py
pex/pip/vcs.py
pex/resolve/downloads.py
pex/resolve/lock_resolver.py
pex/resolve/locked_resolve.py
pex/resolve/locker.py
pex/resolve/lockfile/create.py
pex/resolve/pep_691/fingerprint_service.py
pex/resolve/resolved_requirement.py
tests/integration/cli/commands/test_issue_2057.py
tests/integration/test_downloads.py

Previously, it was assumed that direct reference URLs were either VCS
URLs or else wheel or sdist URLs. This neglected two remaining cases,
both of which failed to lock with better or worse error messages. The
two missed cases were:
1. URLs of source archives not conforming to the sdist quasi-standard
naming convention of `<project name>-<version>.{.tar.gz,.zip}`.
2. Local `file://` URLs pointing at project directories.
A notable case of the 1st are project archives provided by GitHub.
A notable need for the 2nd case comes from Pants where Pip proprietary
requirement strings are not handled (e.g.: `/path/to/project`) and a
direct reference URL must be used instead (e.g.: `projectname @
file:///path/to/project`).
Fixes #2057

Handle locking all direct reference URL forms.

---

pex/bin/pex.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pex_info.py
pex/sh_boot.py
pex/tools/commands/venv.py
pex/venv/pex.py
tests/integration/venv_ITs/test_issue_2065.py

This provides the same option when building a PEX as the
`--non-hermetic-scripts` does when creating a venv from a PEX using
`pex-tools`. In addition, both means of creating a non-hermetic venv
are extended to the venv `pex` script itself.
Closes #2065

Introduce `--non-hermetic-venv-scripts`.

---

pex/atomic_directory.py

This is needed to have independent POSIX fcntl locks in the same process
by multiple threads and also needed whenever BSD flock locks silently
use fcntl emulation (exotic systems or under NFS mounts). Pex is
designed to avoid multi-threading when using POSIX locks; so this just
serves as a design-error backstop for those style locks. For silently
emulated BSD locks, this provides correctness.
Analysis of #2066 and #1969 do not point to this enhancement solving any
existing problems, but this is an improvement for the cases mentioned
should we hit them.
Work regarding #2066.

Wrap inter-process locks in in-process locks.

---

pex/resolve/lock_resolver.py
pex/resolve/lockfile/model.py
pex/resolver.py
tests/integration/cli/commands/test_issue_2057.py

Previously local project indexing was broken for subset resolves and
the operation would crash.
Fixes #2083

Fix lock subsetting for local projects.

---

pex/layout.py
pex/pex.py
pex/venv/pex.py
tests/integration/test_issue_2088.py

The change in #2033 that safeguarded loose `--venv` PEXes such that they
could be executed, moved and continue to execute properly from their new
location, silently broke zipapp and packed layout `--venv` PEX
symlinking. Although `--venv` PEXes for those layouts continued to work,
they used copying to build their venvs instead of symlinking even when
symlinking (the default for `--venv` PEXes) was the intended style.
Fixes #2088

Fix regression in venv symlinking.

---

pex/build_system/pep_517.py
pex/build_system/pep_518.py
pex/build_system/testing.py
pex/pip/local_project.py
pex/resolve/lock_resolver.py
pex/resolve/locker.py
pex/resolve/lockfile/create.py
pex/targets.py
tests/build_system/test_pep_517.py
tests/build_system/test_pep_518.py
tests/integration/build_system/test_pep_518.py
tests/integration/cli/commands/test_issue_2050.py
tests/integration/resolve/test_issue_2092.py
tests/test_targets.py

Previously the ambient Pex interpreter was used to perform VCS downloads
and perform PEP-517 builds instead of the target interpreter(s) selected
by `--python`, `--python-path` and `--interpreter-constraint`.
Fixes #2092

Fix VCS & local project locks to respect target.

---

tests/integration/resolve/test_issue_2092.py

Ideally Pex would be immune to this, but there is alot of work required
there. That work would be worthwhile - I think Pex would become the 1st
locker in the Python ecosystem robust in this way - but that is for
another day.
C.F.: #2100

Fix test broken by pdm-pep517 1.1.3 release.

---

pex/resolve/locker.py
tests/integration/cli/commands/test_issue_2098.py

Previously Pex could hit cases where an artifact expected to have been
just downloaded was found in the Pip cache instead and fail to hash the
artifact as a result. Delay hashing in this case to the post-analysis
phase.
Fixes #2098

Guard lock analysis against Pip-cached artifacts.

---

pex/commands/command.py
tests/commands/test_command.py

Previously JSON output under Python 2 included trailing whitespace after
list items unlike under Python 3.

Stabilize JSON output format across Python 2/3.

---

pex/tools/commands/venv.py
pex/venv/virtualenv.py
tests/integration/tools/commands/test_issue_2105.py

Now, when creating a venv using pex tools and the `--pip` option from a
PEX that includes pip or setuptools or both, those embedded versions
will be used in place of the conflicting versions installed via `--pip`
if `--collisions-ok` is also specified; otherwise the venv pex tool will
error.
Closes #2105

Support --pip overrides via PEX deps.

---

pex/pep_440.py
pex/pip/version.py
pex/resolve/resolver_options.py
tests/pip/test_version.py
tests/resolve/test_resolver_options.py

This allows an opt-in to always using the latest Pip supported by Pex
when upgrading through Pex versions. This is generally desirable for
most Pex consumers.

Add support for `--pip-version latest`.

---

.github/workflows/release.yml
scripts/package.py
tests/integration/test_issue_2038.py
tox.ini

I've already configured the publisher for Pex on PyPI as described here:
https://docs.pypi.org/trusted-publishers/adding-a-publisher/
This change addresses the GitHub side of things as described here:
https://docs.pypi.org/trusted-publishers/using-a-publisher/
I'll delete the PYPI_USERNAME and PYPI_PASSWORD secrets after a
successful release using this new system.
Prep work for #2121

Convert PyPI publishing to OIDC.

---

pex/build_system/pep_517.py
pex/build_system/pep_518.py
pex/interpreter.py
pex/venv/virtualenv.py
tests/build_system/test_issue_2125.py
tests/integration/build_system/test_issue_2125.py
tests/integration/test_issue_2038.py

This is required by the PEP-517 spec.
Fixes #2125

Use get_requires_for_build_wheel for metadata prep.

---

pex/compatibility.py
pex/pip/tool.py
pex/requirements.py
pex/resolve/downloads.py
pex/resolve/locked_resolve.py
pex/resolve/resolved_requirement.py
pex/resolver.py
tests/integration/test_issue_1730.py

The 2.12.0.dev3 release was deleted from PyPI to make room for the
latest batch of Pants releases; so switch to the Pants S3 bucket find
links repo.

Fix CI bitrot due to Pants 2.12.0.dev3 deletion.

---

.github/workflows/ci.yml
pex/compatibility.py
pex/pip/tool.py
pex/pip/version.py
pex/requirements.py
pex/resolve/downloads.py
pex/resolve/locked_resolve.py
pex/resolve/resolved_requirement.py
pex/resolver.py
tests/integration/test_issue_1730.py
tox.ini

The release notes are here:
https://pip.pypa.io/en/stable/news/#v23-1-1

Add Support for Pip 23.1.1.

---

pex/cli/commands/__init__.py
pex/cli/commands/venv.py
pex/dist_metadata.py
pex/interpreter.py
pex/venv/virtualenv.py
tests/integration/cli/commands/test_venv_inspect.py
tests/test_pyvenv_cfg.py

This command allows inspecting venvs created by Pex as well as those
created by other tools.
Work towards #1752 and #2110

Introduce `pex3 venv inspect`.

---

.github/workflows/ci.yml
pex/pip/version.py
tox.ini

Just a bump in vendored setuptools this time to undo a rollback done in
the 23.1.1 release.
The change-log is here:
https://pip.pypa.io/en/stable/news/#v23-1-2

Add support for Pip 23.1.2.

---

pex/cli/commands/venv.py
pex/pep_376.py
pex/pex_bootstrapper.py
pex/resolve/pex_repository_resolver.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
pex/targets.py
pex/tools/commands/venv.py
pex/venv/installer.py
pex/venv/installer_configuration.py
pex/venv/installer_options.py
tests/integration/cli/commands/test_venv_create.py
tests/integration/test_pex_bootstrapper.py
tests/integration/tools/commands/test_venv.py
tests/integration/venv_ITs/test_issue_1630.py
tests/integration/venv_ITs/test_issue_1637.py

This new sub-command can create either a venv or just populate a flat
`sys.path` directory entry (ala `pip install --target`) given a set of
requirements to resolve, potentially from a lock or an existing PEX
file, but otherwise from indexes and find links repos. Unlike the
sibling `venv` `pex-tool` sub-command, the target can be selected and, 
in the flat `sys.path` directory entry case, it can be a foreign 
platform.
Fixes #1752
Fixes #2110
Fixes #2111

Introduce `pex3 venv create`.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.135 release.

---

pex/cli/commands/lock.py
tests/integration/cli/commands/test_export_subset.lock.json
tests/integration/cli/commands/test_export_subset.py

Due to lack of foresight, `pex3 lock export` has a CLI that is poisoned
for use in a consistent way with the rest of PEX while at the same time
introducing subset support; so an `export-subset` sub-command is broken
out sharing the vast majority of the `export` code.
This is immediately useful to a-scie/lift for supporting Pex lock files
on Windows where there is no Pex support yet but seems useful in general
on the same interoperability front the `export` goal was introduced for:
speaking the ~lingua-franca of Pip.

Add `pex3 lock export-subset`.

---

pex/resolve/locked_resolve.py
tests/resolve/test_locked_resolve.py

There were two cases in Pex locks that could lead to `TypeError` being
raised:
1. A locked resolve with more than one locked requirement for a given
pin where each locked requirement had differing primary artifact
types.
2. A locked requirement with more than one additional artifact where
the additional artifact types were not homogeneous.
It's not clear how either of these cases can arise, but case 1. did in
the wild using the vendored Pip (20.3.4).
Fixes #2150

Fix inter-artifact comparisons.

---

.github/workflows/ci.yml
pex/venv/virtualenv.py
tests/integration/cli/commands/test_issue_1667.py
tests/integration/test_issue_1726.py

Several issues are fixed:
+ IPython can inject ~PS1-style prefixes depending on the IPython 
version and Python version in-play. Avoid having to worry about this
with a dedicated test communication channel separate from stdio.
+ The PyPy 7.3.12 release includes HPy in the stdlib (including its
dist-info) which highlights a bug in `Virtualenv` when iterating venv
distributions; so we stick to iterating distributions found in the
site-packages directories.
+ The setup-python action no longer supports Python 2.7; so we switch to
pyenv for that.
+ A test involving `jaraco-collections==3.5.1` is broken by the recent
pydantic 2.x release; so we bound low.

Fix CI bitrots.

---

.github/workflows/ci.yml
pex/pip/installation.py
pex/pip/tool.py
pex/venv/virtualenv.py
tests/integration/cli/commands/test_issue_1667.py
tests/integration/test_issue_1726.py

Isolate the Pip cache per Pip version.

---

.github/workflows/ci.yml
pex/cli/commands/venv.py
pex/venv/installer.py
pex/venv/virtualenv.py
tests/integration/cli/commands/test_issue_1667.py
tests/integration/test_issue_1726.py
tests/integration/venv_ITs/test_issue_2160.py
tox.ini

Previously namespace packages were handled only amongst 3rd-party deps.
Any ns-package also split across PEX user sources would lead to one of
the 3rd-party dep members of the namespace package getting its cached
wheel install contaminated with the PEX user source that was a member of
the ns-package.
Fixes #2160

Fix symlinked venv ns-package calcs.

---

.github/workflows/ci.yml

This also expands scope to cover all deprecated (or soon-to-be)
interpreters we use since GitHub has now proved they do yank support
eventually.

Properly cache pyenv interpreters.

---

pex/pex_builder.py
pex/third_party/__init__.py

Adapt to removed stdlib APIs in Python 3.12.

---

pex/build_system/testing.py
pex/pip/tool.py
pex/pip/version.py
pex/platforms.py
pex/resolve/configured_resolver.py
pex/resolve/lockfile/model.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
tests/build_system/test_pep_518.py
tests/integration/cli/commands/test_issue_1801.py
tests/integration/cli/commands/test_issue_2050.py
tests/integration/cli/commands/test_lock.py
tests/integration/resolve/test_issue_1918.py
tests/integration/test_downloads.py
tests/integration/test_integration.py
tests/test_environment.py
tests/test_pex.py
tests/test_resolver.py
tox.ini

A recent Pip commit has broken
`pip --use-deprecated legacy-resolver download ...` which is our
backwards-compatible default use case. Whether or not Pip decides to
fix, the legacy resolver will be yanked at some point and it seems
reasonable to just require any Pex user on Python 3.12 and thus Pip 23.2
to only use the Pip 2020 resolver.
See: https://github.com/pypa/pip/issues/12138

Prepare for Pip 23.2 release.

---

.github/workflows/ci.yml
pex/pip/version.py
tests/integration/test_issue_1316.py
tests/integration/test_issue_1817.py
tox.ini

Pip 23.2 is both the latest release and the only release that supports
Python 3.12.
The Pip 23.2 release notes are here:
https://pip.pypa.io/en/stable/news/#v23-2
Fixes #2173

Add official support for Python 3.12 / Pip 23.2.

---

pex/pip/version.py
pex/resolve/resolver_options.py
tests/integration/resolve/test_issue_1918.py
tests/resolve/test_resolver_options.py
tests/test_pip.py

This was an oversight in the commits that landed Pip 23.2 / Python 3.12
support.

Fail fast for Pip>=23.2 + pip-legacy-resolver.

---

pex/bootstrap.py
pex/pex.py
pex/pex_bootstrapper.py
tests/integration/test_issue_2183.py

Previously the PEX bootstrap code and third party vendored code were not
demoted and uninstalled respectively like they are for normal PEX
execution.
Fixes #2183

Fix `pex.pex_bootstrapper.bootstrap_pex_env` leak.

---

pex/bin/pex.py
pex/testing.py
tests/integration/test_issue_2134.py

This complements the existing `-D` / `--sources-directory` support for
adding local sources and resources with finer-grained control over
what files are included in the PEX file. Notably, this allows cleanly
packaging projects with no `setup.py` / `pyproject.toml` based build
when the projects have their Python code at the top level mixed with
other files that should not be included in the PEX (e.g.: build scripts,
CI configuration, documentation, etc.).
Fixes #2134

Add support for selecting packages and modules.

---

pex/bootstrap.py
pex/pex_bootstrapper.py
tests/integration/test_pex_import.py

This fixes #1954 by ensuring all vendored code is uninstalled from the
path and bootstrap code is demoted to the end of `sys.path` after
`__pex__` is imported.
Fixes #1954

Cleanup `sys.path` after `__pex__` is imported.

---

pyproject.toml

This was fallout from the CHANGES.rst -> CHANGES.md to support automated
release announcements in #2167.

Fixup CHANGES sdist inclusion and link.

---

tests/test_resolver.py
tox.ini

Pex learned how to parse distributions on its own some time back. Just
dogfood that support.

Remove un-needed test dep on pkg_info.

---

pex/common.py

It made me feel bad to see us redoing work, so I tried to fix it. I doubt this is a consequential performance improvement.

remove quadratic search when tagging a file in Chroot

---

pex/pex_builder.py
pex/vendor/__init__.py
tests/integration/test_issue_2203.py

When Pex is run from a read-only environment such as a venv that has
been made read-only after the fact or a nix environment, it must not
attempt to over-write its own vendored `.bootstrap` code in the process
of creating PEX runtime environments. Fix `.bootstrap` creation to only
write bootstrap files once.
Fixes #2203

Fix the Pex CLI to work when installed read-only.

---

pex/resolve/locker.py
tests/integration/cli/commands/test_issue_2211.py

A narrow range of pip-2020-resolver supporting Pip versions are robust
to build failures attempting to gather sdist metdata; namely
`>=20.3.2,!=20.3.3,<22`. Fix Pex to handle backtracks triggered by build
failures.
Fixes #2211

Handle backtracking due to sdist build errors.

---

.github/workflows/ci.yml

GitHub builds were released yesterday:
https://github.com/actions/python-versions/releases/tag/3.12.0-rc.1-5785015073

Upgrade to 3.12.0rc1 in CI.

---

pex/atomic_directory.py
tests/integration/test_issue_2087.py
tests/test_atomic_directory.py

The `AtomicDirectory` mechanism inflates the target directory file name
length when deriving a work directory name. In the case of unlocked 
operation in particular, this can lead to file name length violations
when the PEX_ROOT is the default `~/.pex` and the home dir is encrypted
with eCryptFS, which generally limits file name lengths to 143
characters. Guard against this explicitly.
Fixes #2087

Guard against too long filenames on eCryptFS.

---

pex/common.py
pex/pex_builder.py
testing/__init__.py
tests/test_common.py
tests/test_pex_builder.py

Addresses one part of #2155.
Adds a wrapper for `os.walk` that sorts directory entries as it traverses directories. As discussed in the issue, `os.walk` may yield directory entries in a different order depending on (possibly) the file system.
I don't know if the two `os.walk` calls that this PR replaces are enough for addressing this class of non-determinism in pex, but these were sufficient for solving the issue in my case. Happy to expand the use of the wrapper if there are other places that it should be used.

Traverse directories in stable order when building a PEX

---

pyproject.toml

flit-core is on version 3.9 now so I hope we can unpin this.

Raise the flit-core limit for Python 3

---

.github/workflows/ci.yml
docker/base/Dockerfile
docker/base/install_pythons.sh
docker/cache/Dockerfile
docker/cache/populate_cache.sh
docker/user/Dockerfile
dtox.sh
scripts/build_cache_image.py
testing/bin/run_tests.py
testing/devpi.py
tests/integration/cli/commands/test_local_project_lock.py
tests/integration/resolve/test_issue_1918.py
tests/integration/tools/commands/test_venv.py
tests/test_dist_metadata.py
tests/tools/commands/test_venv.py
tox.ini

The previous cache strategy is left in place for Mac, but it was too
expensive for the 10GB limit GitHub imposes on total cache size and was
leading to cache thrash.
The new strategy sidesteps the cache size limit by creating a cache
offline in a data-only image and switching the Linux CI jobs - the
lion's share - to run via docker / `./dtox.sh`. It takes ~3 minutes to
download the images now whereas loading the cache took ~30 seconds
previously, but there is no longer any worry about cache size limits.
Obviously running the same thing you run locally in CI is a big benefit
and was one of the goals when I introduced `./dtox.sh` in ~2018. The
downside of the image load times could possibly be overcome by using the
GH cache with docker save / load, but this is good enough for now.

Use a data-only image for cache in CI.

---

.github/workflows/ci.yml

Only write caches on main and include caching of docker images. This
should keep the cache size under 10GB at ~8GB and take the Linux Docker
overhead lower.

Improve CI caching.

---

.github/workflows/ci.yml

Without this, main is actively hitting disk-full when trying to cache 
the images, failing CI.

Free up disk space prior to caching docker images.

---

.github/workflows/ci.yml

The docker-cache step actually increased wall time by more than a
minute.

Remove docker-cache step.

---

pex/pex_bootstrapper.py
tests/integration/test_issue_2235.py

This PR fixes the bug  identified in https://github.com/pantsbuild/pex/issues/2235 when importing dependencies from a non executable pex  created with the `--venv ` flag. 
For example, the snippet
```
import sys
sys.path.append('flask.pex')  # via `pex Flask -o flask.pex --venv`
import __pex__
import flask
```
would mangle `sys.path` removing necessary paths such as `/usr/lib/python3.9` when executing against `/usr/bin/python3.9`.

Fix non executable venv sys path bug

---

pex/cli/commands/lock.py
pex/pip/tool.py
pex/resolve/configured_resolve.py
pex/resolve/configured_resolver.py
pex/resolve/lock_resolver.py
pex/resolve/lockfile/create.py
pex/resolve/lockfile/updater.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
pex/resolver.py
pex/venv/installer.py
testing/bin/run_tests.py
tests/integration/cli/commands/test_lock.py
tests/test_pip.py

When `--use-pip-config` is specified, both `PIP_*` env vars and Pip
configuration files will be read by the Pip Pex delegates to.
Fixes #336
Fixes #838

Add support for `--use-pip-config`.

---

tests/tools/commands/test_repository.py

This test waits indefinitely for me otherwise. On my MacOS 13.0 setup and 
asdf-installed Python 3.9.17, SIGQUIT doesn't cause the `find_links_server` 
to terminate. I checked the same happens with a regular repl or sending the 
signal through various means. Switching to SIGTERM fixes the problem

Fix repository test hanging

---

pex/pex.py
pex/venv/installer.py
tests/integration/venv_ITs/test_issue_2248.py
tests/test_pex.py

Fixes #2248 .
Hang is averted, but not all options work as they would be intended. For example `-q` is not quiet. But that can be separated to another issue.

Fix hang when running repl with python options

---

pex/bin/pex.py
pex/common.py
pex/pex_builder.py
tests/test_pex_builder.py

By default Pex now warns for un-useable PEX zipapps it creates, but it
can be made to error or do nothing at all.
Fixes #2247

Add `--check` support for zipapps.

---

pex/bin/pex.py
pex/common.py
pex/dist_metadata.py
pex/hashing.py
pex/pep_376.py
pex/pex_builder.py
pex/pip/vcs.py
pex/third_party/__init__.py
pex/util.py
pex/vendor/__init__.py
pex/venv/installer.py
testing/__init__.py
tests/integration/tools/commands/test_venv.py
tests/test_environment.py
tests/test_finders.py
tests/test_pex_builder.py

This supports an up coming refactor of `pex.{dist_metadata,pep_376}`
which also requires re-formulating the pyc filters from `Iterable` ->
`Iterable` form to boolean predicates to make typing easier at the
loss of ~nothing.

Migrate many types from str to Text.

---

pex/interpreter.py
pex/pex.py
pex/pip/version.py
pex/resolve/downloads.py
pex/resolve/target_options.py
pex/resolver.py
pex/vendor/__main__.py
tests/integration/test_issue_1232.py
tests/test_interpreter.py
tests/test_pex.py

Fix site-packages identification.
In the process of working a new feature, it was discovered that
`sys.path` manipulations leaked into `PythonInterpreter` when they were
performed before the `__pex__` import hook. This is fixed by always
going through the interpreter disk cache path, which has properly
isolated `sys.path` for quite some time, eliminating the one exception
for the current interpreter. Fixing this case caused several tests to
fail that exposed several eager uses of `PythonInterpreter.get()` that
would execute in import of various modules. Those cases are fixed to
either be lazy or use `sys.executable`.
Along the way, fix up the ~TODO for migrating from `distutils.sysconfig`
to `sysconfig` for determining the site-packages directories. This
should preempt issues with vendor …

Fix site-packages identification.

---

docs/rtd/requirements.txt

Sphinx is incompatible with Jinja2==3.1.0. 
RTD used to pin Jinja2 below that version, but they stopped
doing so when they changed the set of packages they install
by default:
https://blog.readthedocs.com/defaulting-latest-build-tools/
So now we must pin explicitly ourselves.

Fix ReadTheDocs generation.

---

pex/resolve/locker_patches.py
tests/integration/cli/commands/test_issue_2268.py
tests/integration/test_issue_539.py

The `none` ABI indicates no native ABI attachment; and so just the
standard guarantees of pure Python. In general this means no breaks
within a major version (just fixes and additions). Although it's known
CPython does deal breaks within a major version span (some deprecated
items are removed), the de-facto standard presented by PyPA's packaging
library indicate the `none` ABI is compatible for all minor versions in
the major version range (much like the `abi3` ABI for Python 3). As
such, fix universal lock handling to accept a `*<major>*-none-*.whl` for 
all minor versions of Python `<major>`.
Fixes #2268

Fix universal lock handling of the `none` ABI.

---

.readthedocs.yaml

This is now required as layed out here:
https://blog.readthedocs.com/migrate-configuration-v2/
Work towards #2267.

Fix RTD build by including config file.

---

pex/build_system/pep_517.py
pex/cli/commands/interpreter.py
pex/dist_metadata.py
pex/environment.py
pex/pep_376.py
pex/resolve/target_options.py
pex/venv/installer.py
pex/venv/virtualenv.py
tests/build_system/test_pep_518.py
tests/integration/cli/commands/test_interpreter_inspect.py
tests/integration/cli/commands/test_venv_create.py
tests/integration/test_interpreter_selection.py
tests/integration/test_issue_940.py
tests/integration/venv_ITs/test_virtualenv.py
tests/test_dist_metadata.py
tests/test_environment.py

This will allow inventorying system interpreters and venvs; which will
enable strict-checking support for PEX exlucions via `--provided` as 
well as more general resolving from venvs (i.e.: adding a new option to
the `--index`/`--find-links`, `--pex-repository` and `--lock` set of
resolve repository options).
The new `-d/--distributions` option is added to
`pex3 interpreter inspect` to support creating the aforementioned
inventories.

Support `.egg-info` dist metadata.

---

.github/workflows/ci.yml
pex/pip/version.py
pex/resolve/locker.py
pex/resolve/lockfile/create.py
pex/resolve/resolved_requirement.py
tests/integration/cli/commands/test_issue_1801.py
tox.ini

This required updating the locker parsing to account for differences in
23.3.x log output.
Although 23.3 has significant changes from 23.2.x, I was away during its
release and no one clamored for it; so I'm just moving ahead to the
small 23.3.1 update. The changelogs are here:
+ https://pip.pypa.io/en/stable/news/#v23-3-1
+ https://pip.pypa.io/en/stable/news/#v23-3

Add support for Pip 23.3.1.

---

pex/util.py
tests/test_util.py

This fixes #2285 by fixing a minor typo in f9a9d949d95efd0153452dc255625656d628ee17 / #2263 that caused the computation of a PEXes code hash to not recur into the correct directories.
I think this explains the symptoms in #2285 due to caching: if a PEX only contains files in subdirectories, the code hash will be `da39a3ee5e6b4b0d3255bfef95601890afd80709` (the sha256 hash of no data) and thus potentially the `venv create` might be referring to an incorrectly cached installation.

Exclude pyc dirs, not include, when hashing code

---

pex/pex.py

This was a relic of the days of egg zips; and the `dist.location` data
is now fully redundant with the `sys.path` element input to find the
dist in the 1st place.
Fixes #2289

Remove Pex runtime scrubbing dist discovery.

---

docker/base/install_pythons.sh
pex/build_system/pep_517.py
pex/common.py
pex/dist_metadata.py
pex/fetcher.py
pex/interpreter.py
pex/pep_376.py
pex/pep_427.py
pex/pip/installation.py
pex/pip/tool.py
pex/third_party/__init__.py
pex/vendor/__init__.py
pex/vendor/__main__.py
pex/venv/installer.py
pex/venv/virtualenv.py
tests/integration/test_pep_427.py
tests/test_interpreter.py
tests/tools/commands/test_repository.py
tox.ini

This sets the stage for doing runtime installation of wheels without
needing to ship a copy of Pip in every PEX file. To help prove the
robustness, convert the current build time installation of wheel chroots
to this mechanism.
Work towards #2292

Move wheel install logic into Pex.

---

pex/bin/pex.py
pex/pex_builder.py
pex/targets.py
tests/integration/test_issue_1540.py
tests/test_targets.py

Although it's not always possible to derive an appropriate shebang that
will work for multi-platform PEXes, we now do so when possible and warn
when we cannot.
Fixes #1540

Use appropriate shebang for multi-platform PEXes.

---

docker/base/install_pythons.sh
pex/interpreter_constraints.py
tests/integration/test_issue_1537.py

This picks up the 3.11.7 and 3.12.1 releases for both IC range checks
and dtox.sh hermetic builds.

Update Python versions.

---

pex/pex_builder.py
tox.ini

Although the transition to black in July 2020 fixed this for the Python
code, it never hit either code-strings - which Pex uses a few of - or
`tox.ini`. Fix these.

Fix 2-space indent stragglers.

---

pex/jobs.py
pex/layout.py
pex/pep_427.py
pex/pip/tool.py
pex/resolver.py
testing/__init__.py
tests/test_dist_metadata.py
tests/test_environment.py
tests/test_finders.py
tests/tools/commands/test_repository.py

Now both the build time resolve code and the run time layout code use
the same parallelization logic to install wheels using `pex.pep_427` via
a new pair of `pex.jobs.{imap,map}_parallel` functions.
Previously, both used `pex.jobs.execute_parallel`, which incurs a
fork/exec per processed item along with the ensuing overhead of
re-importing all the Pex code needed to do a `pex.pep_427` wheel
install. Although this makes sense for calling Pip, which shares no code
with Pex, it is wasted effort to call pure Pex code. Although early
experiments with parallelizing `pex.pep_427` wheel installs with a
thread pool showed `pex.jobs.execute_parallel` to perform consistently
better, I never experimented with multiprocessing process-based pools.
These perform better than both; and, in hindsight, for …

Remove `Pip.spawn_install_wheel` & optimize.

---

MANIFEST.in

This was no longer needed with the switch to the flit PEP-517 builder
back in #826 in 2019.

Kill unused `MANIFEST.in`.

---

pex/jobs.py
pex/pep_376.py
pex/resolver.py
pex/vendor/_vendored/attrs/.layout.json
pex/vendor/_vendored/packaging_20_9/.layout.json
pex/vendor/_vendored/packaging_21_3/.layout.json
pex/vendor/_vendored/packaging_23_1/.layout.json
pex/vendor/_vendored/pip/.layout.json
pex/vendor/_vendored/setuptools/.layout.json
pex/vendor/_vendored/toml/.layout.json

Previously, installing a wheel that was already installed incurred the
cost of hashing the installed wheel chroot every time. The overhead of
this wasted work for a warm cache was egregious for large distributions
like PyTorch, with gigabytes of files to hash taking seconds.
Work towards #2312.

Lower noop wheel install overhead.

---

CHANGES.md
pex/resolve/locked_resolve.py
pex/resolve/lockfile/updater.py
pex/version.py
tests/integration/test_issue_2324.py

Previously, a `pex3 lock update` would fail whenever bystander projects
(those projects in the lock but not targeted for update via `-p`) had an
sdist primary artifact.
Fixes #2324

Fix lock updates for locks with sdist bystanders.

---

.github/workflows/ci.yml
CHANGES.md
dtox.sh
pex/pex.py
pex/variables.py
pex/venv/installer.py
pex/version.py
tests/integration/conftest.py
tests/integration/test_integration.py
tox.ini

This works for all supported Python versions even when those versions
own REPL does not support tab-completion out of the box.

Add tab-completion support to PEX repls.

---

pex/interpreter.py
pex/third_party/__init__.py

This cleans up #2328 by fixing the root cause of the interpreter
identification leak of exposed `attrs`. The API to report exposed
`sys.path` elements, `third_party.exposed()`, worked at build time,
with a full Pex distribution available, but returned an empty iterator
at run time, with the subset of Pex available in the runtime
`.bootstrap/`.

Fix `third_party.exposed()`.

---

docs/rtd/requirements.txt

Our older pins were no longer compatible with production RTD.
Fixes #2337

Upgrade readthedocs requirements.

---

.github/workflows/ci.yml

I've confirmed the recent announcement by GitHub is true re beefier
Linux runners. We now consistently have 30GB free which is more than we
need. Removing this step saves ~1 minute of run time for each Linux
test shard.

Remove the free disk space CI step.

---

.github/workflows/release.yml

The org has changed; so the SLACK_BOT_TOKEN org secret is not available
and this is noise over there anyhow. Folks can watch this repo's
Releases or else follow the Announcements Discussions if they're
interested.

Remove Pantsbuild Slack Announce on release.

---

.github/workflows/ci.yml
.github/workflows/release.yml
scripts/package.py

The v2.1.164 release went smoothly except for the PyPI deploy. I had to
build and deploy manually from the v2.1.164 tag with:
```
$ rm -rf dist/
$ tox -epackage -- \
--additional-format sdist \
--additional-format wheel \
--embed-docs
$ pex twine -c twine -- upload -s dist/*
```
The action wants the dist/ dir to just contain the artifacts to deploy;
no more and no less.

Fix PyPI deploy.

---

CHANGES.md
pex/bin/pex.py
pex/cli/commands/docs.py
pex/commands/command.py
pex/docs/command.py
pex/docs/server.py
pex/version.py

The `pex --docs` shortcut should provide an ergonomic way to open the
local docs for most Pex CLI users (undoubtedly few use `pex3`). The
`pex3 docs` additional options allow for most of the control needed
though, and the help for the `pex --docs` option points there.

Add `pex --docs` and several `pex3 docs` options.

---

scripts/package.py

The deploy of v2.2.0 failed, much like v2.1.164, due to
`tox -epackage ...` leaving non-PyPI artifacts in the `dist/` dir. This
time the issue was `dist/.tmp`. Fix cleanup of this tmp dir and,
finally, fix the PyPI deploy in the release process.

Fix tmp dir cleanup.

---

.github/workflows/doc-site.yml
.github/workflows/release.yml
CHANGES.md
pex/version.py

This keeps the workflow separate to allow for manual doc site deployment
in PR forks and adds a gather step to the release that triggers that
workflow by dispatching an event at the tail of the release process.

Fix release ordering of the doc site deploy.

---

docker/base/install_pythons.sh
pex/interpreter_constraints.py
tests/integration/test_issue_2038.py

It was released on February 15th:
https://www.python.org/downloads/release/python-3130a4/

Upgrade to 3.13.0a4.

---

CHANGES.md
pex/pip/tool.py
pex/resolve/locked_resolve.py
pex/resolve/lockfile/create.py
pex/version.py
tests/integration/test_issue_2739.py
tests/test_pip.py

More generally, investigate what is out there (on PyPI) for sdists and
explicitly admit `.zip`, `.tar.gz`, `.tar.bz2` and `.tgz` as covering
99.999% of all known cases.
Fixes #2379

Handle `.tar.bz2` & `.tgz` sdists when locking.

---

docker/base/install_pythons.sh
testing/data/locks/mitmproxy.lock.json
tests/integration/conftest.py

Also cleanup now un-needed special handling of pypy2.7 that had been
carried forward from the pypy2.7-v7.3.12 release.

Upgrade CPython 3.13 to the a5 release.

---

tests/integration/test_issue_1537.py

The mitmproxy fixes in #2384 led to the `test_rel_cert_path` test in
`tests/integration/test_issue_1537.py` depositing the `cert` file in
the repo root.

Fix leak of `cert` file in test.

---

pex/resolve/lock_resolver.py
tests/integration/test_issue_2389.py

Since #2346 which was released in Pex 2.1.161, using `--no-build` with a 
`--lock` would fail fast even if the lock itself was created with
`--no-build`, which should be compatible.
Fixes #2389

Fix `pex --no-build --lock ...`.

---

pex/bin/pex.py
pex/dependency_manager.py
tests/integration/test_issue_2391.py

Pex cannot yet handle turning installed wheel chroots back into wheel
files (see #2299). As such, until that time, it must reject attempts
to combine PEXes with different wheel packaging.
Clarifies #2391

Guard against mismatched `--requirements-pex`.

---

docker/base/install_pythons.sh
docker/user/Dockerfile
dtox.sh

See the release announcement here:
https://www.pypy.org/posts/2024/04/pypy-v7316-release.html
Also fix and simplify dtox volume mount permissions adjustment in the
face of docker behavior changes. This new method should be robust to
subtle semantic shifts since it operates after a `docker build` and
fully in `docker run` context taking its cue from the `CACHE_MODE=pull`
method of doing this.

Upgrade to PyPy 7.3.16 release.

---

build-backend/pex_build/hatchling/metadata_hook.py
pyproject.toml
tests/bin/test_sh_boot.py
tox.ini

Although hatchling fixed a few issues that broke Pex packaging, it has
since more strictly adhered to PEP-621 which breaks the existing project
metadata customization scheme. Update the scheme to conform to PEP-621
strictures. Also update the tox configuration to work with modern
hatchling.
Picks up from #2403 by @ofek

Un-pin hatchling.

---

CHANGES.md
pex/fetcher.py
pex/version.py
testing/data/locks/issue-2415.lock.json
tests/integration/test_issue_2183.py
tests/integration/test_issue_2415.py
tests/integration/test_shebang_length_limit.py
tox.ini

This acts as an affordance for users of the gevent monkey patch system,
avoiding warnings about potential imports of `ssl` pre-monkey-patching.
Fixes #2415

Delay import of ssl in `pex.fetcher`.

---

pex/compatibility.py
pex/fetcher.py
testing/data/locks/issue-2415.lock.json
tests/integration/test_issue_2415.py

Previously the test could hang when the log fifo was closed by the
gunicorn server before the port was written to the log; now it fails
when this happens.
Follow up to #2417 which introduced the test and led to observed hangs
in CI.

Improve test_gevent_monkeypatch robustness.

---

CHANGES.md
pex/resolve/downloads.py
pex/resolve/locker.py
pex/version.py
testing/data/pip_logs/issue-2414.pip-23.2.log
testing/data/pip_logs/issue-2414.pip-23.3.1.log
tests/integration/cli/commands/test_issue_2414.py

When support for Pip 23.3.1 was added in #2276 a latent bug in artifact 
URL recording was exposed in cases where the index being used issued
re-directs. Fix up artifact URL recording to grab the primary index URL
and not subsequent re-directs.
Implementing the fix above led to a test failure that revealed another
bug whereby lock file artifact downloads were not respecting the locked
resolve target when it was a foreign platform, which is now fixed.
Finally, fixing the un-patched foreign platform target issue in lock 
file artifact downloads revealed that artifact URLs with hashes were not
being taken advantage of in all cases. Now, when there is a version of
an artifact URL seen that contains hashes - the best of those is always
used to prevent needless post-processing to download and …

Fix artifact URL recording for `pip>=23.3`.

---

pex/cli/commands/lock.py
tests/integration/cli/commands/test_export.py

Although Pex supports locking VCS requirements and local project
requirements, it does so with a be-spoke system for fingerprinting
each; as such, the `--hash`es emitted when exporting lock files
containing these types of requirements are not actually useable in
practice. Continue to support exporting this class of lock file, but
warn of the potential problems and offer a new `--format pip-no-hash`
mode for the daring. In addition, change the requirements output for
this class of lock file to match the input requirement for best
fidelity when actually attempting to use the resulting exported
requirement file without `--hash`es.
Fixes #2416

Fix `pex3 lock export` handling of exotic reqs.

---

pex/bin/pex.py
pex/build_system/pep_517.py
pex/pex_boot.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/pex_info.py
pex/sh_boot.py
tests/integration/test_inject_python_args.py

Support preserving and injecting Python args.
Pex now supports `--inject-python-args` similar to `--inject-args` but
for specifying arguments to pass to the Python interpreter as opposed to
arguments to pass to the application code. This is supported for both
zipapp and venv execution modes as well as standard shebang launching,
launching via a Python explicitly or via the `--sh-boot` mechanism.
In addition, PEX files now support detecting and passing through Python
args embedded in shebangs or passed explicitly on the command line for
all Pythons Pex supports save for `PyPy<3.10` where there appears to be
no facility to retrieve the original argv PyPy was executed with.
Closes #2422

Implement support for preserving and injecting Python args.

---

CHANGES.md
pex/pip/excludes/__init__.py
pex/pip/excludes/requires.py

+ Fix a missed item in the changelog.
+ Clean up the `--exclude` Pip patch and improve its logging.

Clean up after the 2.4.0 release.

---

CHANGES.md
pex/resolve/lock_resolver.py
pex/version.py
tests/integration/test_issue_2432.py

Since #2346, which was released in Pex 2.1.161, using `--only-binary X`
with a `--lock` would fail fast even if the lock itself was created with
`--only-binary X`, which should be compatible.
Fixes #2432

Fix `pex --only-binary X --lock ...`.

---

.github/workflows/ci.yml
CHANGES.md
pex/pip/foreign_platform/__init__.py
pex/pip/foreign_platform/markers.py
pex/pip/version.py
pex/resolve/locker_patches.py
pex/version.py
pyproject.toml
tests/integration/cli/commands/test_issue_1667.py
tests/integration/cli/commands/test_issue_2050.py
tests/integration/cli/commands/test_lock.py
tests/integration/test_integration.py
tests/integration/test_issue_2355.py
tests/test_pip.py
tox.ini

Pex has been testing against Python 3.13 alpha and then beta releases 
for a while now using a patched Pip with Python 3.13 support. Those
patches have made it into the Pip 24.1 release; so now Pex can
officially support Python 3.13.
The Pip 24.1 release notes: https://pip.pypa.io/en/stable/news/#v24-1
Closes #2406

Support `--pip-version 24.1` and Python 3.13.

---

pex/bin/pex.py
pex/interpreter_constraints.py
pex/pep_723.py
pex/resolve/requirement_configuration.py
pex/resolver.py
pex/targets.py
tests/integration/test_script_metadata.py
tests/test_pep_723.py

Pex now reads script metadata present in `--exe`s by default to augment
requirements and constrain allowed target Pythons. Pex can be instructed
to ignore this script metadata though with `--no-pep723` /
`--no-script-metadata`.
This apparently makes due on a promise no active Pex maintainer ever
made, as immortalized in PEP-723:
https://peps.python.org/pep-0723/#tooling-buy-in

Add support for PEP-723 script metadata to `--exe`.

---

.github/workflows/release.yml
CHANGES.md
pex/version.py

The addition of digital attestations in #2442 broke the GitHub Releases
release by moving from default permissions to more restrictive explicit
permission. Those permissions lacked the content write permission needed
to create the release and post its artifacts.

Fix GitHub Releases deployment.

---

.github/workflows/ci.yml
pex/pip/version.py
tox.ini

The changelog is here:
https://pip.pypa.io/en/stable/news/#v24-1-1

Add support for `--pip-version 24.1.1`.

---

pex/bin/pex.py
pex/cli/commands/lock.py
pex/dependency_manager.py
pex/pex_builder.py
pex/resolve/configured_resolver.py
pex/resolve/project.py
pex/resolve/resolvers.py
pex/resolver.py
pex/tracer.py
tests/integration/resolve/test_issue_2412.py

Although Pex already supported local project requirements, they worked
like any other requirement and were included in locks. In the typical
case, a project would rather maintain a lock of its third party
requirements separate from itself. For projects that used requirement
files to record their unlocked dependencies, `-r` could be used instead
of locking the local project. For projects that recorded their
dependencies in a `setup.py`, `setup.cfg` or `pyproject.toml`, the
dependency information needed to be extracted from those files to create
a lock that did not lock the project code itself. Just as bad, when
constructing a PEX the source code layout of the project recorded in
those same project files needed to be replicated in some combination of
`-D`, `-P` and `-M` since resolving from …

Support `--project` locking and PEX building.

---

CHANGES.md
pex/distutils/commands/bdist_pex.py
pex/version.py
tests/integration/test_issue_2412.py

This change produces the same results for existing invocations of
`python setup.py bdist_pex` but allows new uses passing locked project
requirements (either hashed requirement files or Pex lock files) via
`--pex-args`.
Fixes #2412

Fix `bdist_pex` to use `--project`.

---

.github/workflows/ci.yml
CHANGES.md
pex/pip/version.py
pex/version.py
tox.ini

The changelog is here:
https://pip.pypa.io/en/stable/news/#v24-1-2

Add support for `--pip-version 24.1.2`.

---

CHANGES.md
docs-requirements.txt
pex/requirements.py
pex/version.py
tests/integration/test_issue_2410.py
tests/test_requirements.py

Previously, editable requirements in requirements files were not parsed
properly by Pex. Although they did not trigger parse errors, PEXes
created from editable requirements would fail to import those
requirements at runtime despite the editable project distribution being
embedded in the PEX file.
Fixes #2410

Fix editable requirement parsing.

---

.github/workflows/ci.yml
CHANGES.md
dtox.sh
pex/bin/pex.py
pex/pex_bootstrapper.py
pex/platforms.py
pex/resolve/resolver_configuration.py
pex/scie/__init__.py
pex/scie/configure-binding.py
pex/scie/model.py
pex/scie/science.py
pex/targets.py
pex/variables.py
pex/venv/installer.py
pex/version.py
tests/integration/scie/__init__.py
tests/integration/scie/test_pex_scie.py
tox.ini

You can now specify `--scie {eager,lazy}` when building a PEX file and
one or more additional native executable PEX scies will be produced
along side the PEX file. These PEX scies will contain a portable CPython
interpreter from [Python Standalone Builds][PBS] in the `--scie eager`
case and will instead fetch a portable CPython interpreter just in time
on first boot on a given machine if needed in the `--scie lazy` case.
Although Pex will pick the target platforms and target portable CPython
interpreter version automatically, if more control is desired over which
platforms are targeted and which Python version is used, then
`--scie-platform`, `--scie-pbs-release`, and `--scie-python-version` can
be specified.
Closes #636
Closes #1007
Closes #2096
[PBS]: …

Add `--scie` option to produce native PEX exes.

---

pex/bin/pex.py
pex/cli/commands/venv.py
pex/common.py
pex/pep_376.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/tools/commands/venv.py
pex/venv/installer.py
pex/venv/installer_configuration.py
pex/venv/installer_options.py
testing/venv.py
tests/integration/cli/commands/test_issue_2313.py
tests/integration/tools/commands/test_venv.py
tests/test_pex_builder.py
tests/tools/commands/test_venv.py

When creating a venv external to the `PEX_ROOT` via either
`pex3 venv create ...` or `PEX_TOOLS=1 ./my.pex venv ...` you can now
specify `--site-packages-copies` to ensure all code populated in the
venv is isolated from the `PEX_ROOT` cache. Although this takes more
space on disk, it may make sense to use when you expect the venv might
be tampered with or used for experimentation that might alter its files;
otherwise contaminating the `PEX_ROOT` cache.
Fixes #2313

Add `--site-packages-copies` for external venvs.

---

pex/vendor/__init__.py
pex/vendor/_vendored/pip/.layout.json
pex/vendor/_vendored/pip/pip/_internal/utils/glibc.py
tests/integration/test_issue_2017.py

This pulls in a new vendored version of Pip with
the recent fix in https://github.com/pypa/pip/pull/12716 applied in
https://github.com/pex-tool/pip/pull/13. As a result, Pex can run using
vendored Pip under statically linked musl libc CPython interpreters.
This opens the door to bootstrapping newer unpatched Pip's that also
have this same fix (versions 24.2 and later; see: #2471).
Fixes #2017

Support statically linked CPython.

---

pex/build_system/pep_517.py
pex/dist_metadata.py
pex/interpreter.py
pex/jobs.py
pex/pip/dependencies/requires.py
pex/pip/log_analyzer.py
pex/pip/tool.py
pex/resolve/downloads.py
pex/resolve/lock_resolver.py
testing/__init__.py
tests/integration/cli/commands/test_issue_1801.py
tests/integration/cli/commands/test_lock.py
tests/integration/cli/commands/test_lock_resolve_auth.py
tests/integration/cli/commands/test_lock_update_issues_2332_2334.py
tests/integration/test_integration.py
tests/integration/test_issue_2113.py
tests/integration/test_pep_427.py
tests/pip/test_log_analyzer.py
tests/test_dist_metadata.py
tests/test_jobs.py
tests/tools/commands/test_repository.py
tox.ini

This makes several error paths that manifest when creating locks and
PEXes present better error details.
Several changes support this:
1. Jobs can now have a context label which is used, when set, to prefix
all job error output. This should help root cause the problem; i.e.:
is it fundamentally Pex or is it Pip or is it a problem with a bad
package?
2. When a Pip download errors, we now show all STDERR output instead of
just the last line whenever the last line contains "See above for
details", which Pip emits to indicate an error buried deeper in the
logs.
3. A new log analyzer is added to all Pip downloads that knows how to
spot sdist build errors and surface their details.
4. A fail-safe is added to the Pip download log scraper to just report
the full Pip log content when no better …

Add more context for Job errors.

---

.github/workflows/ci.yml
pex/pep_440.py
pex/pip/version.py
tests/integration/test_excludes.py
tests/integration/test_issue_2017.py
tox.ini

The changelog is here: https://pip.pypa.io/en/stable/news/#v24-2
Closes #2471

Add support for `--pip-version 24.2`.

---

CHANGES.md
pex/scie/science.py
pex/version.py
tests/integration/scie/test_pex_scie.py

Previously, invoking `pex pex -c pex --venv --scie eager -o pex` to
build the Pex PEX scie would error deep inside the science scie build
process due to the name collision. Since the user has no control over
the lift manifest, this was not able to be corrected.

Handle all output file names when building scies.

---

CHANGES.md
docs/scie.md
pex/bin/pex.py
pex/scie/__init__.py
pex/scie/model.py
pex/scie/science.py
pex/version.py
tests/integration/scie/test_pex_scie.py

Science 0.5.0 was released with support for stripped PBS distributions
and Science 0.6.0 was released with support for PyPy distributions via
a new PyPy provider. Update Pex to take advantage of both.
When targeting CPython you can now specify `--scie-pbs-stripped` to get
smaller PEX scie binaries at the cost of stripped debug symbols.
If you target PyPy, you now can ship a PEX scie.
Closes #2486
Closes #2487

Support `--scie` for PyPy & support stripped CPython.

---

pex/globals.py
pex/interpreter.py
pex/pex.py
pex/pex_boot.py
pex/pex_bootstrapper.py
pex/pex_builder.py
pex/scie/science.py
pex/venv/installer.py
testing/scie.py
tests/integration/scie/test_pex_scie.py
tests/integration/test_issue_2249.py
tests/tools/commands/test_venv.py

Previously PEXes did not behave like a Python interpreter when invoked
with either `-i` or with `PYTHONINSPECT=x`; now they do.
Fixes #2249

Fix PEXes for `-i` / `PYTHONINSPECT=x`.

---

pex/bin/pex.py
pex/cli_util.py
pex/compatibility.py
pex/repl/__init__.py
pex/repl/custom.py
pex/repl/pex_repl.py
pex/venv/installer.py
pex/venv/venv_pex.py
tests/integration/test_issue_157.py
tests/integration/venv_ITs/test_issue_2248.py
tests/test_pex.py

This extracts the large venv PEX formatted code blob to its own file for
standard formatting, linting and type check treatment. Also clean up
small bits of PEX venv repl code from #2496.

Clean up venv installation code.

---

CHANGES.md
pex/repl/custom.py
pex/repl/pex_repl.py
pex/version.py
tests/integration/test_issue_157.py

Previously the ansi terminal escape sequences were being displayed raw
instead of being interpreted as color codes by the terminal. This was
noticed when using a PEX scie since the Linux PBS CPython builds use a
an un-patched version of libedit that does not handle ansi terminal 
escape sequences unless finessed like we do now.

Fix PEX repl prompt for Linux PBS libedit.

---

docs/buildingpex.rst
pex/finders.py

In the process, fix up non-console-script script handling to surface
syntax errors appropriately as brought to light by the boto mturk
example in `buildingpex.rst`.
Fixes #784

Fix `buildingpex.rst` examples.

---

pex/repl/custom.py
tests/integration/test_issue_157.py

The Pex REPL now respects common conventions surrounding terminal output.

Respect NO_COLOR, FORCE_COLOR & TERM=dumb.

---

tests/integration/cli/commands/test_lock.py

This test started failing to find `find` and it appears to have been
completely removed as a project from PyPI (although its files links
remain).

Replace `find` with `psutil` in test.

---

CHANGES.md
pex/build_system/pep_517.py
pex/pip/installation.py
pex/pip/tool.py
pex/pip/version.py
pex/version.py
tests/integration/cli/commands/test_lock_sync.py
tests/integration/cli/commands/test_lock_update.py
tests/integration/test_issue_2343.py
tests/integration/test_keyring_support.py
tests/test_bdist_pex.py
tests/test_pip.py
tests/tools/commands/test_repository.py

When using non-vendored Pip (i.e.: specifying a custom `--pip-version`),
you can now override the versions of setuptools and wheel Pex bootstraps
for Pip with the existing `--extra-pip-requirement` option and the
override will be respected. Trying to override setuptools or wheel for
vendored Pip will raise an error however since its versions are
specialized to support all Pex resolve features under Python 2.7.
Fixes #1895

Support custom setuptools & wheel versions.

---

pex/scie/__init__.py
pex/scie/model.py
pex/scie/science.py
tests/integration/scie/test_pex_scie.py

This plumbs the `science lift build --hash` option.

Support shasum file gen via `--scie-hash-alg`.

---

pex/bin/pex.py
pex/resolve/lockfile/subset.py
pex/resolve/project.py
tests/integration/resolve/test_issue_2412.py

When specifying `--project` as a source of requirements, you can now
include extras; e.g. `--project this/project-dir[extra1,extra2]`.

Support `--project` extras.

---

CHANGES.md
pex/scie/science.py
pex/version.py
scripts/create-packages.py
tests/integration/scie/test_discussion_2516.py
tests/integration/scie/test_pex_scie.py

This required bumping our `science` floor to the just released 0.8.0
which adds support for explicitly requesting `--no-use-platform-suffix`.
Fixes #2516

Fix `--scie-name-style platform-parent-dir`.

---

testing/bin/run_tests.py
tests/test_interpreter.py
tests/test_pex.py
tests/tools/commands/test_repository.py
tox.ini

This was mostly already working save for a few tests that needed
adjustment to be able to run consistently in isolation or under xdist
or both.

Get unit tests running stably under xdist.

---

CHANGES.md
pex/resolve/resolvers.py
pex/version.py
tests/integration/resolve/test_issue_2532.py

The addition of a wheel tag compatibility check to the overall
post-resolve check in #2512 regressed users of abbreviated `--platform`
in some cases by failing PEX builds that would otherwise succeed and,
later, actually work at runtime. Keep the spirit of #2512 by emitting a
detailed warning at build time with remediation steps instead of failing
the build outright.
Fixes #2532

Warn when `--platform` resolves fail tag checks.

---

pex/atomic_directory.py
testing/__init__.py

The new setup allows for safe upgrades by just bumping pyenv Python
versions. Also re-work atomic_directory to support this cleanly, allow
obtaining an independent lock on an atomic directory after it has been
established. This can be useful when reads of the directory contents all
happen in the same code path as the writes.

Re-work testing pyenv management.

---

pex/cli/commands/lock.py
pex/pip/tool.py
pex/resolve/configured_resolve.py
pex/resolve/lockfile/create.py
pex/resolve/lockfile/updater.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
pex/resolver.py
testing/__init__.py

Although `--pip-log` is just an alias for the pre-existing
`--preserve-pip-download-log` option, the option gains the ability to
accept an optional log path value. In addition to this pro-active means
of starting a debuggable Pex session with Pip, the log is also made more
useful in the face of a multi-target resolve by serializing the log on
targets and prefixing log lines per target. The log now also includes
the compatibility tags calculated via `pip -v debug ...` for any 
abbreviated `--platform`s used in the resolve.

Add the ability to specify the `--pip-log` path.

---

pex/build_system/pep_517.py
tests/build_system/test_issue_2125.py

I've not had a report in the wild, but CI intermittently fails in
PEP-517 tests, not finding the json communication file on the read end.
This exposes a race where the PEP-517 process completes before the
temporary file context manager is exited and the communication file,
with the results therein, is deleted before it can be read. Switch from
a temporary file that deletes on context exit (it's amazing this worked
as reliably as it did - it was a bug from day 1!) to one that deletes
only upon the Pex process exit.

Fix intermittent PEP-517 failures.

---

.github/workflows/ci.yml
CHANGES.md
pex/version.py
tests/integration/resolve/test_issue_1907.py
tests/integration/test_integration.py
tests/integration/test_issue_1179.py
tests/integration/test_issue_940.py
tests/test_resolver.py

Also turn on CI IT sharding for a ~40% wall time reduction, fixing up
some existing test issues this smoked out.

Prepare the 2.20.0 release.

---

CHANGES.md
pex/interpreter_constraints.py
pex/specifier_sets.py
pex/version.py
tests/resolve/test_target_options.py
tests/test_interpreter_constraints.py
tests/test_specifier_sets.py

When `--interpreter-constraint`s are specified that are unsatisfiable,
Pex now either errors if all given interpreter constraints are
unsatisfiable or else warns and continues with only the remaining valid
interpreter constraints after culling the unsatisfiable ones.
Fixes #432

Pre-emptively cull unsatisfiable interpreter constraints.

---

CHANGES.md
pex/common.py
pex/layout.py
pex/version.py
tests/integration/test_issue_298.py
tests/test_common.py
tests/test_enum.py

Previously, zips with non-ASCII file names could cause extraction errors
under Python 2.7 on Linux.
Fixes #298

Fix Zip extraction UTF-8 handling for Python 2.7.

---

pex/cache/dirs.py
pex/cli/commands/cache/command.py
pex/resolve/pep_691/fingerprint_service.py
tests/resolve/pep_691/test_fingerprint_service.py

Use a `dbs` cache entry for all databases starting with PEP-691
fingerprints and hide this cache entry as a choice when purging
individual entries using `pex3 cache purge`.
Work towards #2528.

Re-structure PEP-691 fingerprints db.

---

CHANGES.md
pex/bin/pex.py
pex/build_system/pep_517.py
pex/build_system/pep_518.py
pex/cache/dirs.py
pex/cli/commands/lock.py
pex/common.py
pex/pip/installation.py
pex/pip/tool.py
pex/resolve/configured_resolver.py
pex/resolve/lockfile/json_codec.py
pex/resolve/lockfile/model.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
pex/resolve/resolvers.py
pex/tools/commands/repository.py
pex/version.py
tests/integration/cli/commands/test_export.py
tests/integration/cli/commands/test_lock.py
tests/integration/cli/commands/test_lock_reproducibility_hash_seed.py
tests/test_pip.py

This helps reduce cache sizes where sdists are built into wheels as well
as expanding the set of sdists Pex can lock reproducibly.

Plumb reproducible build env vars more thoroughly.

---

pex/bin/pex.py
pex/build_system/pep_517.py
pex/build_system/pep_518.py
pex/common.py
pex/hashing.py
pex/pep_376.py
pex/pex_builder.py
pex/pip/installation.py
pex/third_party/__init__.py
pex/wheel.py
tests/test_pex_builder.py

The internal PEP-517/518 build system PEXes and the Pip PEXes now both
uniformly use the equivalent of `--layout loose --venv` where
distribution dependencies are always symlinks to the `installed_wheels`
cache. This helps cut down on overall cache size slightly, but also
improves the uniformity of the dogfood.

Regularize dogfood PEX cache use.

---

pex/resolve/lockfile/updater.py

When a lock update only asks for deletes, we now process the "resolve"
offline without consulting Pip.
Fixes #2566

Optimize pure delete lock updates.

---

pex/common.py

Fix `safe_mkdir` swallowing non-`EEXIST` errors.

---

pex/cache/dirs.py
pex/interpreter.py
pex/pex_bootstrapper.py
tests/integration/test_pex_bootstrapper.py

Previously, the work dir path of the `atomic_directory` used to create
the venv would leak into various cached paths in the `PythonInterpreter`
`INTERP-INFO` file. Now, these paths are corrected at creation time.
This is work towards `pex3 cache prune --last-access` which will need to
iterate cached interpreters to find any associated with venvs such that
the interpreter can be pruned when the venv is pruned.

Fix `--venv` cached Python interpreter info.

---

.github/workflows/ci.yml
CHANGES.md
pex/pip/version.py
pex/version.py
tox.ini

The changelog is here: https://pip.pypa.io/en/stable/news/#v24-3-1

Add support for `--pip-version 24.3.1`.

---

CHANGES.md
pex/cache/access.py
pex/cache/dirs.py
pex/cache/prunable.py
pex/cli/commands/cache/command.py
pex/common.py
pex/layout.py
pex/pex_bootstrapper.py
pex/pip/installation.py
pex/venv/installer.py
pex/version.py
tests/integration/cli/commands/test_cache_prune.py

Previously, performing a `pex3 cache prune` would bump the last access
time of all un-pruned cached Pips artificially. If you ran
`pex3 cache prune` in a daily or weekly cron job, this would mean Pips
would never be pruned.

Fix `pex3 cache prune` handling of cached Pips.

---

tests/integration/test_reproducible.py

The setuptools 75.4.0 release on 11/11 led to the test project in `test_reproducible_build_c_flag_from_source` having a non-reproducible wheel build.
See: #2594

Fix `test_reproducible_build_c_flag_from_source`.

---

pex/commands/command.py
pex/common.py
pex/jobs.py
testing/__init__.py
tests/integration/cli/commands/test_cache_prune.py
tests/integration/test_integration.py
tests/integration/test_issue_157.py
tests/resolve/test_target_options.py
tests/test_atomic_directory.py
tests/test_interpreter.py
tests/test_pex.py
tests/test_pip.py
tests/test_requirements.py
tests/test_variables.py

Previously we were forcing use of fork for all OSes to try to juice
performance at the cost of running into threading issues at some point
when things got more complex. They may have reached that point with CI
lockups happening on macOS. Revert to the default pool setup to attempt
to fix macOS hangs.
To support this, also propagate any CLI global `Variables` adjustments
to subprocesses. Previously these were only propagated for the current
process; now the adjustments propagate through the environment so that
subprocesses see the same adjustments. In particular, this ensures
subprocesses use the same `PEX_ROOT` when a fallback has to be used to
work around lack of write perms.

Use the default multiprocessing pool configuration.

---

.github/workflows/ci.yml
.github/workflows/doc-site.yml
.github/workflows/release.yml

These are seeded with copies of the latest `expose-pythons` and
`run-tox` actions from `pantsbuild/actions`.

Migrate to `pex-tool/actions`.

---

pex/resolve/lock_downloader.py
pex/resolve/lock_resolver.py

This both makes the code easier to read (arguable) and allows re-use of
this logic for downloading locked build system artifacts.

Factor out a `LockDownloader`.

---

CHANGES.md
package/pex-scie.lock
pex/cli/commands/lock.py
pex/resolve/lock_downloader.py
pex/resolve/locked_resolve.py
pex/resolve/lockfile/create.py
pex/resolve/lockfile/json_codec.py
pex/resolve/lockfile/model.py
pex/resolve/lockfile/requires_dist.py
pex/resolve/lockfile/updater.py
pex/version.py
scripts/gen-scie-platform.py
tests/integration/cli/commands/test_export.py
tests/integration/cli/commands/test_lock.py
tests/integration/cli/commands/test_lock_elide_unused_requires_dist.py
tests/resolve/lockfile/test_requires_dist.py

This cuts down lock file size without changing any observable result of
using the lock file. It should cut down on lock subset times since there
is both less to parse and less dependencies to rule out after the parse,
but this effect is unmeasured at present.

Add `--elide-unused-requires-dist` lock option.

---

CHANGES.md
pex/resolve/lockfile/model.py
pex/resolve/lockfile/requires_dist.py
pex/version.py
tests/resolve/lockfile/test_requires_dist.py

The feature released broken in 2.25.0 for any locked requirement that
had dependencies that would never be activated due to non-"extra"
environment markers.

Fix `--elide-unused-requires-dist` for inactive deps.

---

pex/repl/custom.py
pex/repl/pex_repl.py
tests/integration/test_issue_157.py

Previously both PS1 and PS2 incorporated color. This interfered with
readline support in some configurations and did not provide much value
otherwise; so the color is removed to give working readline support in
all configurations.

Fix Pex REPL prompt.

---

CHANGES.md
pex/resolve/lockfile/model.py
pex/resolve/lockfile/requires_dist.py
pex/version.py
tests/resolve/lockfile/test_requires_dist.py

A combination of `extra` environment marker evaluation and trimming of
any requires-dists that are not locked is used to fully prune the locked
graph of unused requires-dist entries.

Fix `--elide-unused-requires-dist`: don't expose partial extras.

---

pex/variables.py

Looks like this + is misplaced, as it means `PEX_PYTHON=3.+` would be accepted but it rejects and warns for `PEX_PYTHON=python3.11`.
Leads to this funky warning message telling us to use the setting we already have :)
```
PEXWarning: Using a venv selected by PEX_PYTHON=python3.11 for <snip>.pex at  ...
To avoid this warning, either specify a Python binary with major and minor version
in its name, like PEX_PYTHON=python3.11 or ...
```

Fix incorrect regex for PEX_PYTHON precision warning

---

pex/variables.py

In almost all codepaths, a `pex_root` will be a realpath. See, e.g.,
https://github.com/pex-tool/pex/blob/06b8850f35ae67377ad2fe31d62ee1f71ba61eea/pex/pex_info.py#L511
https://github.com/pex-tool/pex/blob/06b8850f35ae67377ad2fe31d62ee1f71ba61eea/pex/variables.py#L320
However there was one codepath by which a non-realpath could
be obtained, namely `boot()` calling`Variables.PEX_ROOT.value_or()` 
with a `raw_pex_root` given as the fallback value.
This change ensures that `Variables.PEX_ROOT` is always a realpath.
This manifested as a bug at pex boot time in the presence of a
symlinked cache dir: https://github.com/pantsbuild/pants/issues/21321

Ensure that the PEX_ROOT is always a realpath.

---

CHANGES.md
pex/scie/science.py
pex/version.py
tests/integration/scie/test_pex_scie.py

Related to https://github.com/a-scie/lift/issues/116/

Upgrade `science` minimum requirement to 0.10.1.

---

tests/test_pex.py

The sysconfig module became a package in 3.13; so the test strategy for
ammending getsitepackages was broken. Robustify with a sys.path common
prefix match against the sysconfig module location.

Fix test for Python >=3.13.

---

.gitattributes
.gitignore
compatible-tox-hack/pyproject.toml
pex/pyenv.py
scripts/format.py
tox.ini

Re-jigger configuration for tox and git to support Windows dev / CI.
As part of this, fix `pex.pyenv` to work with `pyenv-win`.
CF: https://github.com/tox-dev/tox/issues/3136#issuecomment-2638029551

Windows Build Fixes.

---

.github/workflows/ci.yml
docker/base/install_pythons.sh

This pulls in a beta release of a 3.11 interpreter.
We don't switch to that yet though.
See: https://pypy.org/posts/2025/02/pypy-v7318-release.html

Upgrade PyPy to 7.3.18.

---

.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
build-backend/pex_build/setuptools/build.py
pex/os.py
pex/pex_builder.py
pex/scie/__init__.py
pex/scie/model.py
pex/scie/science.py
pex/sysconfig.py
pex/venv/venv_pex.py
pex/windows/__init__.py
testing/__init__.py
testing/bin/run_tests.py
testing/scie.py
tests/integration/cli/commands/test_cache_prune.py
tests/integration/scie/test_discussion_2516.py
tests/integration/scie/test_pex_scie.py
tests/integration/test_excludes.py
tests/test_environment.py

Use the stubs generated by the uv project for this. The lineage extends
back to distutils through the Posy project. The API is setup and
manually tested to produce working Windows scripts and the packaging
system is updated to embed these stubs in the Pex PEX, wheel and scies.
Actually using the API to create scripts when creating venvs on Windows
is still left to do.
Work towards #2658.

Add a system to produce Windows script `.exe`s.

---

pex/cache/dirs.py
pex/dist_metadata.py
pex/environment.py
pex/layout.py
pex/pep_427.py
pex/scie/configure-binding.py
pex/scie/science.py
pex/sysconfig.py
pex/windows/__init__.py

Use Windows scripts stubs.

---

.github/workflows/build-cache-image.yml
.github/workflows/ci.yml
docker/cache/Dockerfile
scripts/build-cache-image.py
testing/__init__.py
tox.ini

Use this support to alter the CI job into a multi-sharded cache image
build job.
Fixes #2233.

Support for merging the cache image from shards.

---

CHANGES.md
pex/cli/commands/lock.py
pex/resolve/lockfile/model.py
pex/resolve/lockfile/requires_dist.py
pex/version.py
testing/data/locks/issue-2683.lock.json
tests/integration/cli/commands/test_lock_subset.py

Lock subsetting could crash previously. Also fix
`pex3 lock {create,sync,update} --elide-unused-requires-dist`, which
would not crash, but would fail to elide some dists.
Fixes #2683

Fix `pex3 lock subset`.

---

pex/cli/commands/lock.py
pex/dist_metadata.py
pex/docs/server.py
pex/pep_723.py
pex/repl/pex_repl.py
pex/resolve/downloads.py
pex/resolve/lockfile/updater.py
pex/resolver.py
pex/venv/venv_pex.py
pex/ziputils.py
scripts/analyze-CI-shard-timeout.py
scripts/build-cache-image.py
scripts/create-packages.py
tests/integration/cli/commands/test_lock.py
tests/integration/scie/test_pex_scie.py
tests/resolve/test_pex_repository_resolver.py
tests/test_interpreter.py

It's up to tests to use `os.linesep` when reading and testing outputs.
Many tests still are not fixed, but all production outputs are.

Consistently use `\n` for EOL in output.

---

tests/integration/test_integration.py
tests/integration/venv_ITs/test_issue_2065.py

Tests: `os.execv` -> `sys.exit(subprocess.call())`.

---

tests/test_pex.py
tests/test_pex_bootstrapper.py

Fix inappropriate `":"` -> `os.pathsep` in tests.

---

tests/integration/conftest.py

Skip tests that use pexpect on Windows.

---

testing/bin/run_tests.py
tests/integration/cli/commands/test_lock_resolve_auth.py

Windows will serve from 0.0.0.0 but does not like connecting to 0.0.0.0 
as a TCP client.

Use a devpi host Windows can handle.

---

CHANGES.md
pex/environment.py
pex/version.py
tests/integration/test_issue_2706.py

Previously, using root requirements of `foo[bar] foo[baz]` would produce
the same PEX as `foo[bar,baz]`, (save for the root requirements list)
but the former PEX would not properly activate both the `bar` and `baz`
extras during boot. This is now fixed.
Fixes #2706.

Fix dup requirement extra merging during PEX boot.

---

docker/base/install_pythons.sh

3.11 may be high enough quality to switch to with this release.
See the blog post here:
https://pypy.org/posts/2025/02/pypy-v7319-release.html

Upgrade PyPy to the v7.3.19 release.

---

tests/integration/cli/commands/test_cache_prune.py

This buys time for mainline CI while the lock hang is investigated.

Skip `test_cache_prune` on Windows.

---

pex/common.py

Allow the full range of PEXes under the Zip64 limit even on old Pythons.

Enable true Zip64 support.

---

pex/bin/pex.py
tests/integration/scie/test_pex_scie.py

Previously, this combination of arguments would lead to no output at all
since the PEX would be unlinked but the PEX had the same name as the
final scie; so the scie itself was unlinked.

Fix `--scie-only` for `-o` not ending in `.pex`.

---

CHANGES.md
pex/scie/science.py
pex/version.py
tests/integration/scie/test_pex_scie.py

The embedded PEX now has the executable bit set and it retains the name
requested by the user in nearly all cases.

Fix PEX scie contents when split.

---

CHANGES.md
pex/scie/science.py
pex/version.py
tests/integration/scie/test_pex_scie.py

This saves ~5MB for eager scies targeting 64 bit systems.

Do not include `ptex` in `--scie eager` scies.

---

CHANGES.md
pex/scie/science.py
pex/version.py
tests/integration/scie/test_pex_scie.py

C.F.: https://github.com/a-scie/lift/issues/127

Upgrade to `science` 0.12.2 to fix PBS rate limits.

---

CHANGES.md
pex/pep_723.py
pex/version.py
tests/test_pep_723.py

This pre-emptively fixes the issue reported here:
https://github.com/astral-sh/uv/issues/12303

Fix PEP-723 script metadata parsing.

---

CHANGES.md
pex/sh_boot.py
pex/version.py
tests/integration/test_sh_boot.py

This patch stops the "execute venv entrypoint directly" fast-path from happening when the user has set `PEX_TOOLS=1` with a `--sh-boot` PEX, mimicking the similar check performed for Python bootstrapping:
https://github.com/pex-tool/pex/blob/17bd416647eaca978e538408f1ec21813ab26335/pex/pex_boot.py#L204-L205
This change ensures that `PEX_TOOLS=1 ./some.pex` always works, no matter the state of the `PEX_ROOT` cache.
Fixes #2725

Avoid fast-path in --sh-boot script when PEX_TOOLS=1

---

CHANGES.md
package/complete-platforms/linux-aarch64.json
package/complete-platforms/linux-armv7l.json
package/complete-platforms/linux-x86_64.json
package/complete-platforms/macos-aarch64.json
package/complete-platforms/macos-x86_64.json
pex/version.py
scripts/gen-scie-platform.py

Add the final fixes for the gen-scie-platform script / workflow and
update the Pex PEX scies to use CPython 3.13.3.

Prepare the 2.33.8 release.

---

CHANGES.md
pex/pex_boot.py
pex/scie/science.py
pex/version.py
tests/integration/scie/test_issue_2740.py

The PEX scie argv0 fix in #2738 regressed the ability to treat a PEX
scie with no entrypoint as a Python interpreter in `pex --python ...`
invocations. This is now fixed.
Fixes #2740

Fix entrypoint-less PEX scies used as `--python`

---

.github/workflows/ci.yml
CHANGES.md
pex/pep_425.py
pex/pip/version.py
pex/resolve/locker_patches.py
pex/resolve/resolver_options.py
pex/version.py
scripts/gen-scie-platform.py
testing/devpi.py
tests/integration/cli/commands/test_lock.py
tests/integration/test_integration.py
tests/integration/test_lock_resolver.py
tests/integration/test_pex_bootstrapper.py
tests/resolve/test_resolver_options.py
tests/test_pip.py

Also add support for `--pip-version latest-compatible`. The
`latest-compatible` version will be the latest `--pip-version`
supported by Pex compatible with the current interpreter running Pex.

Add support for `--pip-version 25.1`.

---

CHANGES.md
build-backend/pex_build/setuptools/build.py
pex/pip/vcs.py
pex/resolve/locker.py
pex/version.py
tests/integration/cli/commands/test_issue_1665.py
tests/integration/cli/commands/test_lock_requirements_file.py
tests/integration/conftest.py
tests/integration/test_integration.py

Previously, locking VCS requirements would fail for projects with
non-normalized project names, e.g.: PySocks vs its normalized form of
pysocks.
Additionally, locking would fail when the requirements were specified
at least in part via requirements files (`-r` / `--requirements`) and
there was either a local project or a VCS requirement contained in the
requirements files.

Fix Pex locking for source requirements.

---

pex/resolve/target_options.py

These pre-dated `--complete-platform`s and now account for those.

Update `--resolve-local-platforms` docs.

---

tests/integration/resolve/test_issue_1918.py

It was not compensated for the new plumbing of requirement urls in lock
handling.

Fix `test_redacted_requirement_handling` test.

---

.github/workflows/ci.yml
docker/user/Dockerfile
pex/cache/dirs.py
pex/venv/venv_pex.py
pex/windows/__init__.py

We're getting rate-limited in CI despite sending a bearer token; so
cache these more aggressively.

Cache windows console script stubs.

---

CHANGES.md
pex/resolve/configured_resolve.py
pex/resolve/lock_resolver.py
pex/resolve/lockfile/pep_751.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
pex/version.py
tests/integration/cli/commands/test_pep_751.py
tests/resolve/lockfile/test_pep_751.py

Introduce `pex --pylock ... --pylock-extra+ --pylock-group+`. This is
only supported for Python 3.8 or newer.

Support PEP-751 extras and dependency groups.

---

CHANGES.md
pex/version.py

Pexcz can use the Windows fixes in its own tests.

Prepare the 2.40.2 release.

---

CHANGES.md
pex/cli/commands/__init__.py
pex/cli/commands/download.py
pex/resolve/lock_resolver.py
pex/version.py
tests/integration/cli/commands/test_download.py

Allow downloading distributions directly instead of building a PEX or
creating a venv from a resolve.
Closes #2790

Add `pex3 download`.

---

pex/cli_util.py
tests/integration/resolve/test_issue_2772.py
tests/integration/scie/test_issue_2740.py
tests/integration/test_issue_2706.py

This fixes production use of a PEX repl as well as all PEX_TOOLS.

Fix more `commonpath` uses; use `safe_commonpath`.

---

.github/workflows/ci.yml
CHANGES.md
pex/cli/commands/docs.py
pex/docs/command.py
pex/fetcher.py
pex/http/__init__.py
pex/http/server.py
pex/scie/__init__.py
pex/scie/model.py
pex/scie/science.py
pex/venv/venv_pex.py
pex/version.py
testing/data/locks/mitmproxy.lock.json
testing/mitmproxy.py
testing/scie.py
tests/integration/conftest.py
tests/integration/scie/test_issue_2810.py
tests/integration/scie/test_pex_scie.py

Introduce `--scie-assets-base-url` which can be used to point to a
science asset mirror previously populated with `ptex`, `scie-jump` and
interpreter providers via `science download ...`.
Also fix PEX scie creation to use either of `--proxy` or `--cert` if set
when building scies. Previously, these options were only honored when
downloading the `science` binary itself but not when running it
subsequently to build scies.
Finally, bump the minimum required `science` version to 0.12.4 to pick
up a fix for building UNIX scies on Windows.
Fixes #2810

Add `--scie-assets-base-url` & honor `--{proxy,cert}`.

---

CHANGES.md
pex/common.py
pex/os.py
pex/pex_info.py
pex/pex_root.py
pex/variables.py
pex/version.py
tests/integration/conftest.py
tests/integration/test_issue_2819.py
tests/integration/test_issue_2822.py
tests/test_common.py
tests/test_pex_root.py

Do not clean fallback `PEX_ROOT` prematurely.

---

CHANGES.md
pex/cli/commands/lock.py
pex/dependency_configuration.py
pex/pex_info.py
pex/pip/dependencies/__init__.py
pex/pip/dependencies/requires.py
pex/pip/tool.py
pex/resolve/configured_resolver.py
pex/resolve/lock_resolver.py
pex/resolve/locked_resolve.py
pex/resolve/locker.py
pex/resolve/lockfile/create.py
pex/resolve/lockfile/download_manager.py
pex/resolve/lockfile/json_codec.py
pex/resolve/lockfile/model.py
pex/resolve/lockfile/pep_751.py
pex/resolve/lockfile/requires_dist.py
pex/resolve/resolvers.py
pex/resolve/target_system.py
pex/resolver.py
pex/version.py
tests/integration/cli/commands/test_issue_1821.py
tests/integration/test_downloads.py
tests/integration/test_override_replace.py
tests/test_dependency_configuration.py

Instead of just accepting PEP-508 requirement strings for `--override`
values, Pex now also accepts values of the form
`<project name>=<requirement>` to override any transitive requirement
on one project with a requirement on a completely different project.
This can be useful when you need to supply a patch to an existing
published project and would prefer to depend on wheels you pre-build
instead of using a VCS source dependency `--override`, which can be slow
to build.
Addresses #2891 and completes the suggested use cases in #2425 for which
`--override` was originally introduced.

Support dependency replacement with `--override`.

---

tests/integration/cli/commands/test_pep_751.py

The change in https://github.com/tox-dev/tox/pull/3578 causes
`tox --version` to blow up when there is a setup.cfg in the CWD with no
tox:tox section.

Fixup pdm interop test to work with modern tox.

---

CHANGES.md
pex/resolve/package_repository.py
pex/resolve/resolver_options.py
pex/version.py
tests/integration/test_scoped_repos.py
tests/resolve/test_package_repository.py

This should help make common case command lines smaller and easier to
grok and maintain.

Support regexes for `--source` project matching.

---

CHANGES.md
pex/bin/pex.py
pex/cli/commands/venv.py
pex/dependency_configuration.py
pex/dist_metadata.py
pex/environment.py
pex/pep_425.py
pex/pep_427.py
pex/pip/installation.py
pex/pip/tool.py
pex/resolve/configured_resolve.py
pex/resolve/configured_resolver.py
pex/resolve/pex_repository_resolver.py
pex/resolve/resolver_configuration.py
pex/resolve/resolver_options.py
pex/resolve/resolvers.py
pex/resolve/target_options.py
pex/resolve/venv_resolver.py
pex/resolver.py
pex/targets.py
pex/vendor/__main__.py
pex/version.py
pex/wheel.py
testing/__init__.py
tests/integration/resolve/test_issue_1361.py
tests/integration/venv_ITs/test_install_wheel_multiple_site_packages_dirs.py
tests/test_dist_metadata.py
tests/test_environment.py
tests/test_finders.py

Add a new `--venv-repository` resolution source. This allows creating a
PEX from a preexisting venv. By default, all installed venv 
distributions are included in the PEX, but by specifying requirements,
the venv can be subset.
The `--venv-repository` source is also supported by `pex3 venv create`, 
allowing sub-setting an existing venv directly into a new venv as well.
Closes #1361

Add support for `--venv-repository` resolver.

---

CHANGES.md
pex/cli/commands/lock.py
pex/resolve/target_system.py
pex/version.py
tests/integration/cli/commands/test_split_universal_locks.py
tests/integration/test_scoped_repos.py

Fix two bugs handling split universal resolves:
1. Previously, when a universal resolve was split by markers other than
`python_version` and `python_full_version` and no interpreter
constraints were specified, locking would fail.
2. Additionally, when a split lock had differing transitive
dependencies in splits, lock sub-setting would fail.
Both issues are now corrected.

Fix split universal lock corner cases.

---

docker/base/install_pythons.sh

They were slower than devpi on the rc3 release but have since caught up.

Switch back to deadsnakes for PI.
