pex-tool/pex

MANIFEST.in

Seems to fix the missing files and directories.  Issue #51

Expand MANIFEST.in to include missing files.  Fixes issue #51

---

pex/environment.py
pex/pex_info.py

Also fixed a bug introduced at fe895b2e2 that breaks boolean PEX_*
environment variable overrides.  Will be fixed when wickman/13 lands.

Reimplement PEX_IGNORE_ERRORS.  Fixes #82.

---

pex/pex.py
tests/test_pex.py

Print error messages from SystemExit to stderr

---

pex/bin/pex.py
pex/pex.py
pex/tracer.py
pex/variables.py
tox.ini

Make access to PEX_* environment variables consistent.

---

CHANGES.rst
pex/interpreter.py
pex/version.py

https://rbcommons.com/s/twitter/r/2586/

Accommodate OSX `Python` python binaries.

---

CHANGES.rst
pex/http.py

Add pex-identifying User-Agent to requests sessions.

---

tests/test_util.py
tox.ini

Fix missed mock of safe_mkdir.

---

pex/version.py
scripts/coverage.sh

Bump setuptools version pinning.

---

pex/pex_builder.py

Repair issue #220.

---

pex/bin/pex.py
tox.ini

Adds a test to reveal and fixes the main() entrypoint breakage.
Fixes #252.

Repair main() entrypoint.

---

pex/pex.py
tests/test_inherits_path_option.py

How do people feel about also inheriting the user site when `--inherit-path` is used?

Inherit user site with --inherit-path

---

README.rst

linkedin's pygradle produces pex files

---

pex/version.py
scripts/coverage.sh

Part of a larger play to modernize our use of setuptools in pex/pants.

Bump setuptools range to latest.

---

.travis.yml
tox.ini

Add py36 environments for tox/travis.

---

CHANGES.rst
pex/version.py

Release 1.2.5

---

CHANGES.rst
pex/version.py

Quick release containing just #367.

Release 1.2.6

---

pex/pex_bootstrapper.py
tests/test_integration.py

Bugfix for entry point targeting + integration test

---

.travis.yml

Fixes #461 
(h/t @CMLivingston for the discovery)

Fixup PATH handling in travis.yml.

---

pex/pex_info.py
tests/test_integration.py
tests/test_pex_info.py

Fix failing tests in master that have gone undetected (as a result of bad PATH setting in #427).

Fix failing tests in master

---

tests/test_integration.py

Temporary relief for #461, #470

Skip two failing integration tests.

---

pex/resolver.py
tests/test_integration.py

Repair environmental marker platform setting.

---

docker/base/Dockerfile

This is needed to bootstrap pyenv.

Add missing git dep.

---

README.rst

In particular, license, version, python versions and wheel status.

Add more badges to README.

---

CHANGES.rst
pex/version.py

Prepare the 1.4.6 release.

---

CHANGES.rst
pex/version.py
setup.py

Prepare the 1.4.7 release.

---

tests/test_integration.py

Fixup test_jupyter_appnope_env_markers.

---

CHANGES.rst
pex/version.py

Prepare the 1.4.8 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.4.9 release.

---

CHANGES.rst
pex/resolver.py
pex/version.py

Prepare the 1.5.0 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.5.1 release.

---

pex/common.py

Docstring typo I came across while looking through the source.

Small Docstring Fix

---

CHANGES.rst
pex/version.py

Prepare the 1.5.2 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.0 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.1 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.3 release.

---

tests/test_platform.py

I'm not sure how this snuck in master, but cleans it up.

Fix stray bad isort.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.4 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.5 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.6 release.

---

pex/commands/bdist_pex.py

Leftover code from https://github.com/pantsbuild/pex/pull/624.

Remove unused bdist_pex.py helper function

---

CHANGES.rst
pex/version.py

Prepare the 1.6.8 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.9 release.

---

.travis.yml
setup.py
tox.ini

Remove support for python versions that are EOL.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.10 release.

---

CHANGES.rst
pex/version.py

Prepare the 1.6.11 release.

---

CHANGES.rst
pex/version.py

Prepare the v1.6.12 release.

---

CHANGES.rst
pex/version.py

Prepare the pex 2.0.0 release.

---

pex/bin/pex.py

Fixing issue #794, every build failed using --index-url option

Fix #794 issue by add missing return statement in __str__

---

CHANGES.rst
pex/version.py

Prepare the 2.0.1 release.

---

tests/test_pex_binary.py

Previously rendering was broken but fixed in #795. Add a test of that
fix.

Add a test of pypi index rendering.

---

CHANGES.rst
pex/version.py

Prepare the 2.0.2 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.0.3 release.

---

.travis.yml

Support python 3.8 in CI.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.0 release.

---

pex/environment.py
tests/test_environment.py

Previously, Pex would erroneously warn about needing to expose vendored
`pkg_resources` for distributions that had present but empty
`namespace_packages.txt` metadata. A test is added and the warning
message improved for the legitimate cases.
Fixes #840

Fix Pex to handle empty ns package metadata.

---

pex/interpreter.py

This speeds up interpreter discovery by a factor of ~10 on cache hits.
Fixes #782

Introduce an interpreter cache.

---

tests/test_integration.py
tox.ini

Subsequent changes will fix the underlying issues, once
we fully understand them.

Temporarily skip a couple of tests, to get CI green.

---

pex/resolver.py

[resolver] Fix issue with wheel when using --index-url option

---

CHANGES.rst
pex/version.py

 Prepare the 2.1.1 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.2 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.3 release.

---

pex/pip.py
tests/test_resolver.py

As described in #892, when the Pex resolver API is used in-process, a
sufficiently antagonistic PYTHONPATH could lead to a failure to launch
the pip PEX we delegate resolving to. Fix this by scrubbing PYTHONPATH
from the pip PEX environment pre-launch.
Fixes #892

Fix Pex resolver API PYTHONPATH hermeticity.

---

README.rst

Preview at https://github.com/jhermann/pex/tree/patch-1#readme
BTW, the GH "Website" setting should point to https://pex.readthedocs.io, see the top of the preview page.

readme: adding a TOC

---

CHANGES.rst
pex/version.py

Prepare the 2.1.4 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.5 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.6 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.8 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.9 release.

---

pex/util.py

Closes https://github.com/pantsbuild/pex/issues/942.

Fix deprecation warning for `rU` mode

---

CHANGES.rst
pex/version.py

Prepare the 2.1.10 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.11 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.12 release.

---

pex/bin/pex.py

Improve and fix --platform help.

---

CHANGES.rst
pex/version.py

Prepare 2.1.13 release.

---

CHANGES.rst
pex/version.py

Closes https://github.com/pantsbuild/pex/pull/1011

Prepare 2.1.14

---

pex/interpreter.py
pex/interpreter_constraints.py
pex/pip.py
pex/third_party/__init__.py
tests/test_integration.py
tests/test_pex.py
tests/test_pex_info.py
tox.ini

This fixes (arguably) incorrect docstring formatting (indentation).
Other changes are just part of ceding control.

Upgrade Black.

---

pex/interpreter_constraints.py
tests/test_pex_bootstrapper.py

Handle the case when there are no candidates and add a test for this.

Fix UnsatisfiableInterpreterConstraintsError.

---

pex/util.py
tests/test_integration.py

Previously direct (or indirect) sys.path manipulation via import lines
in .pth files would not be detected and scrubbed. We now detect these
modifications and scrub them as appropriate.
Fixes #1025

Scrub direct sys.path manipulations by .pth files.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.16 release.

---

pex/third_party/__init__.py

Fix resource leak in Pex self-isolation.

---

pex/pex_info.py

This is a bandaid fix only. Appropriate comments have been added to
help prevent re-regression with a longer term fix tracked by #1055.
Fixes #1054

Fix `--unzip` performance regression.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.17 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.18 release.

---

README.rst

Fixup freeze recipe for Pex 2.x.

---

CHANGES.rst
pex/version.py

Closes https://github.com/pantsbuild/pex/issues/1069.

Prepare 2.1.19

---

CHANGES.rst
pex/version.py

Closes https://github.com/pantsbuild/pex/issues/1089.

Prepare 2.1.20

---

pex/bin/pex.py
pex/pex_builder.py

Deprecate `-R`/`--resources-directory`.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.21 release.

---

pex/compatibility.py
pex/network_configuration.py
pex/pip.py
pex/requirements.py
pex/resolver.py
tests/test_network_configuration.py
tests/test_requirements.py

This is a prerequisite for fixing ##899, implementing #1108 and the API
will also be useful to Pants which currently can only handle a subset
of requirements, forcing edits of existing requirment files to use
alternative requirement forms.

Implement full featured requirment parsing.

---

pex/testing.py
tests/test_integration.py
tests/test_interpreter.py

Add a test of proxy handling with auth and custom ca certs.
Follows up on #1114 converting most manual testing into an IT.

Add URLFetcher IT.

---

pex/environment.py

Default the pex_info to that contained in the pex.

Improve PEXEnvironment constructor ergonomics.

---

pex/common.py

Previously we would fail to unlock when we lost the atomic directory
creation race.
Fixes #1119

Exclusive atomic_directory always unlocks.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.22 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.23 release.

---

.travis.yml
pyproject.toml
tests/test_dist_metadata.py
tests/test_integration.py
tests/test_resolver.py

Also bump the 3.9 we test with in CI to 3.9.1.
Fixes #1141

Fix python requirement to include full 3.9 series.

---

CHANGES.rst
pex/version.py

Prepare 2.1.24 release.

---

pex/pex_info.py
tests/test_pex_info.py

Fix PexInfo.copy.

---

pex/requirements.py
tests/test_integration.py
tests/test_requirements.py

Work towards #899, #1020 and #1108.

Add support for parsing extras and specifiers.

---

pex/environment.py
pex/orderedset.py
pex/pex.py

Since Python 2.7 has OrderedDict, just use that for the implementation
and add typing support.

Refresh and type OrderedSet.

---

pex/interpreter.py
pex/interpreter_constraints.py
pex/jobs.py
pex/pex_bootstrapper.py
tests/test_interpreter.py

Type SpawnedJob.

---

pex/common.py

Type AtomicDirectory.

---

pex/resolver.py

Type BuildAndInstallRequest.

---

pex/pip.py
tests/test_integration.py

Previously this was not working for Python 2.7.
Fixes #1179

Fix plumbing of 2020-resolver to Pip.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.26 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.27 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.28 release.

---

.github/workflows/ci.yml
tox.ini

This allows DRYing up the CI config a good bit.

Leverage GH actions job matrix.

---

.github/workflows/ci.yml
pex/testing.py
pyproject.toml
tests/test_environment.py
tests/test_integration.py
tests/test_pex.py
tox.ini

Bring up PyPy 3 with 5 test failures xfailed for follow-up in #1210.

Add PyPy3 to CI.

---

docker/base/Dockerfile

This had drifted away from CI images which are now Ubuntu 20.04.

Update ./dtox hermetic dev env.

---

.github/actions/run-tox/action.yml
.github/workflows/release.yml

This makes sure we install the tox version specified in tox.ini.

Fix run-tox action tox version.

---

.github/workflows/release.yml

Switch to using canned create-release and upload-release-asset actions.

Fixup Pex PEX upload.

---

pex/tools/commands/venv.py
tests/tools/commands/test_venv.py

Venv scripts aren't relocatable without edits since their shebangs
record the absolute path of the venv interpreter. However, they should
work when invoked indirectly by the moved venv's interpreter. This
already worked for venv console scripts but it did not work for the
`pex` venv script, which re-execs when invoked with an unexpected
interpreter.
Add a relocation test that fails and fix the `pex` venv script to be
more flexible in its venv interpreter identification.

Support venv relocation.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.31 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.32 release.

---

pex/pex_builder.py
pex/tools/command.py
pex/tools/commands/__init__.py
pex/tools/commands/interpreter.py
pex/tools/commands/repository.py
pex/tools/main.py
pex/util.py
pex/vendor/__init__.py
tests/tools/commands/test_repository.py

This allows inspecting a PEX file's distributions as well as exporting
them as wheels.

Introduce the repository PEX_TOOL.

---

pex/pip.py
tests/test_integration.py

Ensure Pip logs to stderr.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.34 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.35 release.

---

.github/workflows/ci.yml
tox.ini

Previously the check only included distribution building; now it
includes building of the Pex PEX for distribution as well.

Fix Packaging check to be complete.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.36 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.38 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.39 release.

---

CHANGES.rst

Quite a few had accumulated over time.

Fix bad PR links.

---

pex/pex_builder.py
pex/pex_info.py
pex/tools/commands/venv.py
pex/variables.py
tests/test_integration.py
tests/tools/commands/test_venv.py

Fix Pex venv mode to respect `--strip-pex-env`.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.40 release.

---

CHANGES.rst
pex/version.py

Prepare 2.1.41 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.42 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.43 release.

---

pex/pip.py
tests/test_pip.py

The interface now accepts extra env vars instead of a complete
environment which avoids needless issues with ambient environment
variable collisions in ENV **kwargs.
A failing test is added that this fix corrects.
Fixes #1387

Fix Pip handling of internal env vars.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.44 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.45 release.

---

CHANGES.rst
pex/version.py

Prepare v2.1.46 release.

---

pex/variables.py
tests/test_variables.py

This supports some up-coming test changes in the fix for #1422.

Support deletion of Variables via patch.

---

pex/pip.py

Previously only erroring jobs partook in log analysis. To support lock
file generation, we'll need to support analysis for successful
downloads.
Works towards #1401.

Allow Pip log analysis for successful jobs.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.48 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.49 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.50 release.

---

pex/tools/commands/README.venv.md
pex/tools/commands/virtualenv.py
pex/tools/commands/virtualenv_16.7.12_py
scripts/embed_virtualenv.sh

This brings a few fixes:
https://github.com/pypa/virtualenv/blob/16.7.12/docs/changes.rst#v16712-2020-07-22
Work towards #1451

Upgrade to virtualenv 16.7.12.

---

pex/tools/commands/virtualenv.py
tests/test_resolver.py

Scrub PYTHONPATH when creating venvs.

---

pex/argparse.py
pex/bin/pex.py
pex/resolve/__init__.py
pex/resolve/resolve_configuration.py
pex/resolve/resolve_options.py
tests/resolve/test_resolve_options.py
tests/test_pex_binary.py

This sets the stage for PEX_TOOLs that can invoke resolves using the
standard CLI flags users have come to rely on.

Factor out resolve configuration.

---

pex/cli/__init__.py
pex/cli/__main__.py
pex/cli/command.py
pex/cli/pex.py
pex/commands/__init__.py
pex/commands/command.py
pex/pex_builder.py
pex/tools/commands/__init__.py
pex/tools/commands/graph.py
pex/tools/commands/info.py
pex/tools/commands/interpreter.py
pex/tools/commands/repository.py
pex/tools/commands/venv.py
pex/tools/main.py
pyproject.toml

This will clear space for build-time commands and be the new interface for
the Pex CLI in Pex 3.

Factor up command infra and introduce pex3.

---

pex/bin/pex.py
pex/enum.py
pex/inherit_path.py
pex/layout.py
pex/locked_resolve.py
pex/pex_builder.py
pex/pip.py
pex/resolve/resolve_options.py
pex/tools/commands/venv.py
pex/venv_bin_path.py
tests/integration/test_integration.py
tests/integration/test_issue_1018.py
tests/integration/test_layout.py
tests/test_enum.py
tests/test_execution_mode.py
tests/test_pex_builder.py

There were alot of these in circulation.

DRY up ~enums.

---

pex/sorted_tuple.py
tests/test_sorted_tuple.py

This will be used for structures that must be sorted to be correct
in Pex lockfile work.
Work towards #1401 and #1414.

Introduce SortedTuple.

---

pex/cli/commands/lock.py
pex/cli/commands/lockfile/json_codec.py
pex/cli/commands/lockfile/lockfile.py
tests/cli/commands/lockfile/test_json_codec.py
tests/cli/commands/lockfile/test_lockfile.py

This is needed in order to reproduce the lock setup in an update.
Work towards #1412.

Include LockStyle in Lockfile.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.51 release.

---

.github/workflows/ci.yml

This will be used as the single status check in GH branch protection
rules.

Add a fan-in aggregate status step.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.53 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.54 release.

---

docs/rtd/requirements.txt

Fix RTD generation by pinning docutils low.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.55 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.56 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.58 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.59 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.60 release.

---

pex/tools/commands/venv.py
tests/integration/test_pex_bootstrapper.py

This reverts to old `--venv` behavior which is compatible with more
distributions found in the wild.
Closes #1555

Merge packages for `--venv-site-packages-copies`.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.61 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.62 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.63 release.

---

pex/interpreter.py
pex/tools/commands/virtualenv.py
tests/integration/tools/commands/test_virtualenv.py

Support iterating a venv's distributions.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.66 release.

---

CHANGES.rst
pex/version.py
tests/test_pep_508.py

Prepare the 2.1.67 release.

---

pex/pip.py
pex/resolve/locked_resolve.py
pex/resolve/lockfile/json_codec.py
pex/resolve/resolved_requirement.py
pex/resolver.py
tests/integration/cli/commands/test_lock.py
tests/integration/test_locked_resolve.py
tests/resolve/lockfile/test_json_codec.py

Also re-shuffle related types and clean up the Locker interaction.

Move ResolvedRequirement to `pex.resolve` package.

---

pex/resolve/locked_resolve.py
tests/resolve/test_locked_resolve.py

This was broken when only wheel artifacts were available to rank and
those wheels had different tags.

Fix prefer_older_binary.

---

pex/cli/command.py
pex/cli/commands/interpreter.py
pex/cli/commands/lock.py
pex/cli/pex.py
pex/commands/command.py
pex/resolve/locked_resolve.py
pex/resolve/lockfile/__init__.py
pex/resolve/lockfile/updater.py
pex/result.py
pex/tools/command.py
pex/tools/commands/graph.py
pex/tools/commands/info.py
pex/tools/commands/interpreter.py
pex/tools/commands/repository.py
pex/tools/commands/venv.py
pex/tools/main.py
tests/commands/test_command.py
tests/resolve/test_locked_resolve.py

This code is now more widely used than in just leaf command
implementations.

Move the Result family out of command.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.68 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.69 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.70 release.

---

pex/resolve/locked_resolve.py
tests/resolve/test_locked_resolve.py

Honor constraints in `LockedResolve.resolve`.

---

pex/resolve/lock_resolver.py
pex/resolve/lockfile/json_codec.py
tests/integration/test_lock_resolver.py
tests/resolve/lockfile/test_json_codec.py

Closes https://github.com/pantsbuild/pex/issues/1659.

Support lockfiles with no requirements

---

CHANGES.rst
pex/version.py

Prepare the 2.1.71 release.

---

pex/pip.py
tests/integration/cli/commands/test_issue_1665.py

Fix Locker to prune un-downloaded entries.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.72 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.73 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.74 release.

---

tests/integration/cli/commands/test_issue_1665.py

See https://github.com/psf/black/issues/2963

Bump black to 22.3.0 in integration test

---

CHANGES.rst
pex/version.py

Prepare the 2.1.76 release.

---

pex/pip/runtime_patches.py

For `universal` locks using the `pip-2020-resolver` and
`--interpreter-constraint` we could hit pathologically slow resolves
when there were many transitive requirements and / or many of these
were resolved as sdists. The issue was narrowed to `Requires-Python`
evaluation and this is fixed here to still be correct, but to do the
minimal amount of evaluation and backtracking.
Fixes #1706

Fix pathologic lock creation slowness.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.77 release.

---

RELEASE.rst

Document PGP release pre-reqs.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.78 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.79 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.80 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.81 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.82 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.83 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.84 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.85 release.

---

CHANGES.rst
pex/testing.py
pex/vendor/_vendored/pip/pip-20.3.4.dist-info/METADATA
pex/version.py
tests/test_bdist_pex.py

Prepare the 2.1.86 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.87 release.

---

pex/auth.py
tests/integration/cli/commands/test_lock_resolve_auth.py

Just warn when `~/.netrc` can't be loaded.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.88 release.

---

pex/compatibility.py
pex/environment.py
pex/interpreter_constraints.py
pex/pex_bootstrapper.py
tests/integration/cli/commands/test_issue_1734.py
tests/integration/test_pex_bootstrapper.py
tests/resolve/test_pex_repository_resolver.py
tests/test_compatibility.py

The fix for #1020 did not add language for the new resolve check
failures.

Fix runtime interpreter selection failure message.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.89 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.90 release.

---

pex/pip/log_analyzer.py
pex/pip/tool.py

This is part of a series of a refactors needed to remove dependency
cycles in support of #1696.

Extract Pip log analysis bases.

---

tests/integration/test_issue_1520.py

The May 25th release of protobuf 4.21.0 breaks mypy-protobuf 2.4

Fix test with dependency drift.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.93 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.94 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.95 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.96 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.97 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.98 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.99 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.100 release.

---

pex/pep_376.py
pex/pip/tool.py
pex/venv/virtualenv.py
tests/integration/test_issue_1861.py

We already had robust and well tested code for this; so just re-plumb a
bit and use it.
Fixes #1861

Make wheel install site-packages detection robust.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.101 release.

---

.github/workflows/ci.yml
CHANGES.rst
pex/pex.py
pex/pex_bootstrapper.py
pex/version.py
tests/integration/test_issue_1031.py
tests/integration/test_issue_1870.py
tests/test_pex.py

Prepare the 2.1.102 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.103 release.

---

pex/resolve/locker.py

Fixes #facepalm.
Work towards #1805

Remove unused Pip log scraping.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.104 release.

---

.readthedocs.yml

Add support for offline downloads (#1524)

---

scripts/embed_virtualenv.py
scripts/format.py
scripts/typecheck.py

No longer display backtraces from checked subprocess tool invocations.

Cleanup script error exits.

---

pex/venv/pex.py
pex/venv/virtualenv.py
pyproject.toml
tests/integration/cli/commands/test_lock.py

Both the detection of the venv site-packages directory and the
installation of Pip in the venv now handle a wider range of
configurations.

Make Virtualenv more robust.

---

pex/compatibility.py
pex/tools/main.py
tests/integration/test_integration.py
tests/integration/test_pex_bootstrapper.py
tests/test_compatibility.py
tests/test_pex_builder.py
tests/test_third_party.py

Add `os.path.commonprefix` backport.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.106 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.107 release.

---

pex/pex_info.py

The introduction of the InterpreterConstraints type in #1931 and the top-level import of it in PexInfo degraded PEX boot times by ~100ms. Make the import lazy to gain that boot time back.
Fixes #1940

Optimize PexInfo import time.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.109 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.113 release.

---

README.rst

The current tox links lead to a 404.

fix tox links

---

CHANGES.rst
pex/version.py

Prepare the 2.1.114 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.115 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.116 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.117 release.

---

pex/pex_builder.py
tests/integration/test_issue_1730.py
tests/integration/test_issue_2006.py

Remove un-needed realpathing of `sys.argv[0]`.

---

pex/tools/commands/venv.py
tests/integration/test_issue_2001.py

Fixes https://github.com/pantsbuild/pex/issues/2001

ignore compile error for PEX_TOOLS=1

---

CHANGES.rst
pex/version.py

Prepare the 2.1.119 release.

---

pex/pip/log_analyzer.py

Fixes #2027 (verified the fix on the platform that exhibits the issue)

Check for the pip log before attempting to read it.

---

.github/workflows/ci.yml
pex/testing.py
tests/integration/cli/commands/test_lock.py
tests/integration/test_integration.py
tests/integration/test_issue_1933.py
tests/integration/test_issue_539.py
tests/integration/test_reproducible.py
tests/test_environment.py
tests/test_interpreter.py

Doesn't actually set up aarch64 CI, as this is not perceived to be necessary at this time.

Some tweaks to get tests passing on aarch64

---

pex/requirements.py
tests/test_requirements.py

Support space separated markers in URL reqs.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.121 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.122 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.123 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.124 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.125 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.126 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.127 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.128 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.129 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.130 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.131 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.132 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.133 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.134 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.136 release.

---

CHANGES.rst
pex/version.py

Prepare the 2.1.137 release.

---

.github/workflows/ci.yml
CHANGES.rst
pex/venv/virtualenv.py
pex/version.py
tests/integration/cli/commands/test_issue_1667.py
tests/integration/test_issue_1726.py

Prepare the 2.1.138 release.

---

tests/integration/test_reproducible.py

CI uses `tox -e py312-pip23_2-integration`, but for local dev runs
`tox -e py312-integration` is more typical. Get this green by ensuring
the reproducible build tests use a consistent Pip version since
`pip wheel` has varying output for certain metadata files (line order
and whitespace vary) across Pip / Setuptools / Wheel versions.

Get `tox -e py312-integration` passing.

---

CHANGES.md
pex/version.py

Prepare the 2.1.139 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.140 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.141 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.142 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.143 release.

---

docker/base/Dockerfile
docker/base/install_pythons.sh
docker/user/Dockerfile
docker/user/create_docker_image_user.sh
dtox.sh

This ensures the dev env is useable for running tests, inspecting test
failures and iterating. It also fills out the Python interpreter set to
cover all interpreters Pex supports.

Refresh the ./dtox.sh dev env.

---

CHANGES.md
pex/version.py

Prepare the 2.1.144 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.145 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.146 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.147 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.148 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.149 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.150 release.

---

CHANGES.md
pex/version.py

Prepare the 2.1.151 release.

---

.github/workflows/ci.yml
pex/pip/version.py
tox.ini

The changelog is here: https://pip.pypa.io/en/stable/news/#v23-3-2

Add support for Pip 23.3.2.

---

.github/workflows/ci.yml
pex/pip/version.py
tests/resolve/test_pex_repository_resolver.py
tox.ini

The release notes are here:
https://pip.pypa.io/en/stable/news/#v24-0

Add support for Pip 24.0.

---

.github/workflows/ci.yml
pex/cli/commands/lock.py
pex/resolve/downloads.py
pex/resolve/lock_resolver.py
pex/resolve/locked_resolve.py
pex/resolve/locker.py
pex/resolve/lockfile/json_codec.py
pex/resolve/lockfile/updater.py
pex/resolve/resolved_requirement.py
tests/integration/cli/commands/test_issue_1413.py
tests/integration/cli/commands/test_issue_1688.py
tests/integration/cli/commands/test_issue_1711.py
tests/integration/cli/commands/test_issue_1801.py
tests/integration/cli/commands/test_issue_1821.py
tests/integration/cli/commands/test_lock_update.py
tests/integration/cli/commands/test_vcs_lock.py
tests/integration/resolve/test_issue_1918.py
tests/integration/test_issue_2348.py
tests/resolve/lockfile/test_download_manager.py
tests/resolve/lockfile/test_json_codec.py
tests/resolve/test_locked_resolve.py
tests/resolve/test_pex_repository_resolver.py
tests/resolve/test_resolved_requirement.py

Fix URL escaping for lock artifacts.

---

.github/workflows/ci.yml
.github/workflows/doc-site.yml
.github/workflows/release.yml

This eliminates node16 warnings / prepares for the spring when node16
goes away.

Upgrade actions.

---

docker/base/install_pythons.sh
pex/interpreter_constraints.py
tests/integration/test_lock_resolver.py
tests/test_pex_builder.py

Also upgrade all other pythons to latest point releases.

Upgrade Python 3.13 to alpha 6.

---

.github/workflows/release.yml

See: https://github.blog/changelog/2024-06-25-artifact-attestations-is-generally-available/

Add artifact attestations for release.

---

CHANGES.md
pex/dist_metadata.py
pex/version.py
testing/dist_metadata.py
tests/integration/test_issue_2441.py
tests/test_dist_metadata.py

Improve errors for invalid distribution metadata.

---

.github/workflows/release.yml
CHANGES.md
pex/version.py

Permissions should now be correct per:
https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions

Fix GitHub Releases deployment.

---

CHANGES.md
pex/build_system/pep_518.py
pex/cli/commands/lock.py
pex/pip/installation.py
pex/tools/commands/repository.py
pex/venv/installer.py
pex/venv/virtualenv.py
pex/version.py
testing/__init__.py
tests/integration/cli/commands/test_interpreter_inspect.py
tests/integration/cli/commands/test_local_project_lock.py
tests/integration/cli/commands/test_lock_sync.py
tests/integration/test_excludes.py
tests/integration/test_issue_2203.py
tests/integration/test_issue_2413.py
tests/integration/test_pep_427.py
tests/integration/tools/commands/test_issue_2105.py
tests/integration/venv_ITs/test_virtualenv.py
tests/test_bdist_pex.py

Improve venv creation robustness when adding Pip.

---

CHANGES.md
pex/bin/pex.py
pex/cli/commands/venv.py
pex/pex_bootstrapper.py
pex/pex_info.py
pex/tools/commands/venv.py
pex/venv/installer_configuration.py
pex/venv/installer_options.py
pex/venv/virtualenv.py
pex/version.py
tests/integration/venv_ITs/test_issue_1973.py

Support `--system-site-packages` when creating venvs.

---

docker/base/install_pythons.sh

See the release announcement here:
https://pypy.org/posts/2024/08/pypy-v7317-release.html

Upgrade to PyPy 7.3.17 release.

---

docker/base/install_pythons.sh
pex/interpreter_constraints.py

A bunch of releases yesterday - all active versions were bumped:
+ 3.8.20
+ 3.9.20
+ 3.10.15
+ 3.11.10
+ 3.12.6
+ 3.13.0rc2

Upgrade to the latest batch of CPythons.

---

pex/repl/custom.py

This is new CPython env var knob in Python 3.13.

Add repl support for `PYTHON_COLORS`.

---

package/complete-platforms/linux-aarch64.json
package/complete-platforms/linux-x86_64.json
package/complete-platforms/macos-aarch64.json
package/complete-platforms/macos-x86_64.json
package/package.toml

Updated `package/package.toml` and then ran:
`tox -e gen-scie-platform -- --all`.

Upgrade Pex scie to PBS 20241002 / CPython 3.12.7.

---

.github/workflows/ci.yml
CHANGES.md
pex/pip/version.py
pex/version.py
tox.ini

The changelog is here: https://pip.pypa.io/en/stable/news/#v24-3

Add support for `--pip-version 24.3`.

---

tests/integration/test_reproducible.py

The prior fix was a hand-wave. Now the original issue is fully
understood and solved in a future-proof way.
Fixes #2594

Fix `test_reproducible_build_c_flag_from_source`.

---

CHANGES.md
docs/scie.md
pex/fetcher.py
pex/scie/__init__.py
tests/integration/scie/test_pex_scie.py
tests/integration/test_issue_2017.py
tests/integration/test_issue_2355.py

This tracks the ownership transfer from indygreg to astral-sh.

Update PBS GitHub repo URLs.

---

pex/common.py
pex/pep_376.py
pex/resolver.py

This is work towards #2658 which will need to tackle falling back from
symlinks when there are insufficient permissions to create them.

Consolidate relative symlink creation.

---

.github/workflows/ci.yml
pex/commands/command.py
pex/docs/server.py
pex/fs/_posix.py
pex/os.py
pex/pex.py
pex/repl/custom.py
pex/subprocess.py
pytest.ini
scripts/build-docs.py
testing/devpi-server.lock
testing/devpi.py
tests/integration/test_issue_298.py
tests/integration/test_shebang_length_limit.py
tests/tools/commands/test_repository.py
tox.ini

Initial Windows CI setup.

---

.github/workflows/windows-test-report.yml

Don't attempt Windows test report gen in forks.

---

pex/interpreter.py
testing/__init__.py
tests/integration/cli/commands/test_venv_inspect.py
tests/integration/test_issue_1025.py
tests/integration/test_issue_1031.py
tests/integration/test_issue_1809.py
tests/integration/test_issue_455.py
tests/integration/test_issue_745.py
tests/integration/venv_ITs/test_issue_1630.py
tests/integration/venv_ITs/test_issue_1973.py
tests/test_interpreter.py
tests/tools/commands/test_repository.py

Fixup `ensure_*` for pyenv-win and make_project.

---

dtox.sh

Fix `CACHE_MODE=pull` for images created via import.

---

pex/docs/server.py
pex/subprocess.py
testing/devpi.py
tests/integration/test_sh_boot.py
tests/integration/test_shebang_length_limit.py

Fix Windows test skips and daemon launches.

---

.github/workflows/ci.yml

Windows is currently extremely slow; help it out.

Shard Windows tests 4 ways.

---

pex/commands/command.py
pex/docs/command.py
pex/docs/server.py
pex/os.py
pex/tools/commands/graph.py

A bit hacky, but this seems to work well. Hack tracked in #2699.

Fix docs server for Windows.

---

pex/cli/commands/venv.py
pex/executables.py
pex/interpreter.py
pex/windows/__init__.py
pex/ziputils.py
tests/test_executables.py
tests/test_windows.py

Fix script detection for Windows.

---

pex/bin/pex.py
pex/distutils/commands/bdist_pex.py
pex/interpreter.py
pex/sh_boot.py
tests/integration/test_inject_python_args.py

Fix `test_inject_python_args` for Windows.

---

.github/workflows/ci.yml
tox.ini

Fix cryptography builds on Windows.

---

pex/cache/dirs.py
pex/cache/root.py
pex/cli/commands/lock.py
pex/compatibility.py
pex/pep_427.py
pex/pex_builder.py
pex/repl/pex_repl.py
pex/venv/virtualenv.py
tests/integration/cli/commands/test_issue_2059.py
tests/integration/cli/commands/test_issue_2098.py
tests/integration/cli/commands/test_issue_2268.py
tests/integration/cli/commands/test_venv_create.py
tests/integration/resolve/test_issue_1918.py
tests/integration/test_excludes.py
tests/integration/test_integration.py
tests/integration/test_interpreter.py
tests/integration/test_issue_1336.py
tests/integration/test_issue_1949.py
tests/integration/test_issue_2087.py
tests/integration/test_issue_2088.py
tests/integration/test_issue_2183.py
tests/integration/test_issue_2432.py
tests/integration/test_issue_455.py
tests/integration/test_setproctitle.py
tests/test_pex.py
tests/test_pex_builder.py
tests/test_third_party.py

Fix cross-drive `commonpath` on Windows.

---

CHANGES.md
pex/scie/science.py
pex/venv/venv_pex.py
pex/version.py
testing/pex_dist.py
tests/integration/cli/commands/test_lock_reproducibility_hash_seed.py
tests/integration/scie/test_issue_2733.py

Fix argv0 in PEX scies to point to the scie itself.

---

CHANGES.md
pex/scie/science.py
tests/integration/scie/test_issue_2733.py

Fix PEX scie argv0 to be the scie absolute path.

---

CHANGES.md
pex/requirements.py
pex/version.py
tests/test_requirements.py

Fix requirement file includes relative path handling.

---

CHANGES.md
pex/resolve/lockfile/pep_751.py
pex/version.py
tests/integration/resolve/test_issue_2772.py
tests/resolve/lockfile/test_pep_751.py

Fix `--pylock` handling of sdist and wheel `name`.

---

pex/environment.py
tests/integration/cli/commands/test_pep_751.py

@frostming got fixes for the pdm issues surfaced in #2770 quickly:
+ https://github.com/pdm-project/pdm/pull/3519
+ https://github.com/pdm-project/pdm/pull/3520
Thanks Frost!

Update pdm PEP-751 interop tests to use pdm fixes.

---

CHANGES.md
docs/buildingpex.rst
pex/pep_508.py
pex/version.py
tests/test_pep_508.py
tests/test_platform.py

Add `--platform` support for Windows.

---

CHANGES.md
pex/atexit.py
pex/common.py
pex/layout.py
pex/os.py
pex/version.py
tests/integration/test_issue_2819.py
tests/test_atexit.py

Fix temp dir leak on boot of `--no-pre-install-wheels` PEX.

---

CHANGES.md
pex/os.py
pex/scie/__init__.py
pex/scie/model.py
pex/scie/science.py
pex/version.py
tests/integration/scie/test_issue_2827.py

Add `--scie-base` to control PEX's scie cache dir.

---

.gitignore
CHANGES.md
build-backend/pex_build/setuptools/build.py
pex/cli/commands/__init__.py
pex/cli/commands/interpreter.py
pex/cli/commands/run.py
pex/cli/commands/venv.py
pex/commands/command.py
pex/hashing.py
pex/interpreter.py
pex/pex_boot.py
pex/pex_info.py
pex/variables.py
pex/version.py
tests/integration/cli/commands/test_lock_requirements_file.py
tests/integration/cli/commands/test_run.py
tests/integration/test_integration.py
tests/integration/test_setproctitle.py

Add `pex3 run`.

---

.github/workflows/ci.yml

CI times are creeping up towards 2 hours for the long pole shard.

Expand Windows from 4 shards to 5.

---

CHANGES.md
pex/resolve/lockfile/pep_751.py
pex/resolve/lockfile/tarjan.py
pex/version.py
tests/integration/test_issue_2862.py
tests/test_tarjan.py

Fix `pylock.toml` cycle handling.

---

CHANGES.md
pex/pex_info.py
pex/scie/science.py
pex/version.py
tests/integration/scie/test_issue_2827.py

Fix PEX scie `--runtime-pex-root` handling.

---

CHANGES.md
pex/cli/commands/run.py
pex/resolve/requirement_options.py
pex/version.py
tests/integration/cli/commands/test_run.py

The final work for the inital release of `pex3 run` in #2840.

Support requirement files & constraints in `pex3 run`.

---

CHANGES.md
pex/build_system/pep_517.py
pex/version.py
tests/integration/build_system/test_issue_2913.py

Fix sdist build of local projects using `uv_build`.
